export const LocalStorageProperties = {
    CurrentUserId: 'CurrentUserId',
    CurrentUser: 'CurrentUser',
    CurrentCulture: 'CurrentCulture',
    CompanyId: 'CompanyId',
    CompanyName: 'CompanyName',
    CompanyMainLogo:'CompanyMainLogo',
    CompanyMiniLogo:'CompanyMiniLogo',
    DefaultDashboard: 'DefaultDashboard',
    CompanyDetails: 'CompanyDetails',
    FromLogIn: 'FromLogIn',
    CompanyTheme: 'CompanyTheme',
    SearchClick: 'SearchClick',
    RoleFeatures:'RoleFeatures',
    EntityRoleFeatures:'EntityRoleFeatures',
    SoftLabels: 'SoftLabels',
    RecentSearches: 'RecentSearches',
    Dashboards: 'Dashboards',
    ExpensesFileCount: 'ExpensesFilesCount',
    UserRoleFeatures: 'UserRoleFeatures',
    Environment: 'Environment',
    Modules:'Modules',
    UserModel: 'UserModel',
    UserIp: 'UserIp',
}