export const timeZoneCollection = [
    { TimeZoneName: "Afghanistan Time", TimeZoneAbbrevation: "AFT", CountryCode:"AF", CountryName : "Afghanistan", TimeZone:"Asia/Kabul", GMTOffset:"+0430" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"AL", CountryName : "Albania", TimeZone:"Europe/Tirane", GMTOffset:"+0200" },
    { TimeZoneName: "Central European Time", TimeZoneAbbrevation: "CET", CountryCode:"DZ", CountryName : "Algeria", TimeZone:"Africa/Algiers", GMTOffset:"+0100" },
    { TimeZoneName: "Samoa Standard Time", TimeZoneAbbrevation: "SST", CountryCode:"AS", CountryName : "American Samoa", TimeZone:"Pacific/Pago_Pago", GMTOffset:"-1100" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"AD", CountryName : "Andorra", TimeZone:"Europe/Andorra", GMTOffset:"+0200" },
    { TimeZoneName: "West Africa Time", TimeZoneAbbrevation: "	WAT", CountryCode:"AO", CountryName : "Angola", TimeZone:"Africa/Luanda", GMTOffset:"+0100" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"AI", CountryName : "Anguilla", TimeZone:"America/Anguilla", GMTOffset:"-0400" },
    { TimeZoneName: "Casey Time", TimeZoneAbbrevation: "CAST", CountryCode:"AQ", CountryName : "Antarctica", TimeZone:"Antarctica/Casey", GMTOffset:"+1100" },
    { TimeZoneName: "Davis Time", TimeZoneAbbrevation: "DAVT", CountryCode:"AQ", CountryName : "Antarctica", TimeZone:"Antarctica/Davis", GMTOffset:"+0700" },
    { TimeZoneName: "Dumont-d'Urville Time ", TimeZoneAbbrevation: "DDUT", CountryCode:"AQ", CountryName : "Antarctica", TimeZone:"Antarctica/DumontDUrville", GMTOffset:"+1000" },
    { TimeZoneName: "Mawson Time", TimeZoneAbbrevation: "MAWT", CountryCode:"AQ", CountryName : "Antarctica", TimeZone:"Antarctica/Mawson", GMTOffset:"+0500" },
    { TimeZoneName: " New Zealand Daylight Time", TimeZoneAbbrevation: "NZDT", CountryCode:"AQ", CountryName : "Antarctica", TimeZone:"Antarctica/McMurdo", GMTOffset:"+1300" },
    { TimeZoneName: "Chile Summer Time", TimeZoneAbbrevation: "CLST", CountryCode:"AQ", CountryName : "Antarctica", TimeZone:"Antarctica/Palmer", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AQ", CountryName : "Antarctica", TimeZone:"Antarctica/Rothera", GMTOffset:"-0300" },
    { TimeZoneName: "Syowa Time", TimeZoneAbbrevation: "SYOT", CountryCode:"AQ", CountryName : "Antarctica", TimeZone:"Antarctica/Syowa", GMTOffset:"+0300" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"AQ", CountryName : "Antarctica", TimeZone:"Antarctica/Troll", GMTOffset:"+0200" },
    { TimeZoneName: "Vostok Time", TimeZoneAbbrevation: "VOST", CountryCode:"AQ", CountryName : "Antarctica", TimeZone:"Antarctica/Vostok", GMTOffset:"+0600" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"AG", CountryName : "Antigua and Barbuda", TimeZone:"America/Antigua", GMTOffset:"-0400" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/Buenos_Aires", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/Catamarca", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/Cordoba", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/Jujuy", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/La_Rioja", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/Mendoza", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/Rio_Gallegos", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/Salta", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/San_Juan", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/San_Luis", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/Tucuman", GMTOffset:"-0300" },
    { TimeZoneName: "Argentina Time", TimeZoneAbbrevation: "ART", CountryCode:"AR", CountryName : "Argentina", TimeZone:"America/Argentina/Ushuaia", GMTOffset:"-0300" },
    { TimeZoneName: "Armenia Time", TimeZoneAbbrevation: "AMT", CountryCode:"AM", CountryName : "Armenia", TimeZone:"Asia/Yerevan", GMTOffset:"+0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"AW", CountryName : "Aruba", TimeZone:"America/Aruba", GMTOffset:"-0400" },
    { TimeZoneName: "Australian Eastern Daylight Savings Time", TimeZoneAbbrevation: "AEDT", CountryCode:"AU", CountryName : "Australia", TimeZone:"Antarctica/Macquarie", GMTOffset:"+1100" },
    { TimeZoneName: "Australian Central Daylight Saving Time", TimeZoneAbbrevation: "ACDT", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Adelaide", GMTOffset:"+1030" },
    { TimeZoneName: "Australian Eastern Standard Time", TimeZoneAbbrevation: "AEST", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Brisbane", GMTOffset:"+1000" },
    { TimeZoneName: "Australian Central Daylight Saving Time", TimeZoneAbbrevation: "ACDT", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Broken_Hill", GMTOffset:"+1030" },
    { TimeZoneName: "Australian Eastern Daylight Savings Time", TimeZoneAbbrevation: "AEDT", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Currie", GMTOffset:"+1100" },
    { TimeZoneName: "Australian Central Standard Time", TimeZoneAbbrevation: "ACST", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Darwin", GMTOffset:"+0930" },
    { TimeZoneName: "Austrslian Central Western Standard Time", TimeZoneAbbrevation: "ACWST", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Eucla", GMTOffset:"+0845" },
    { TimeZoneName: "Australian Eastern Daylight Savings Time", TimeZoneAbbrevation: "AEDT", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Hobart", GMTOffset:"+1100" },
    { TimeZoneName: "Australian Eastern Standard Time", TimeZoneAbbrevation: "AEST", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Lindeman", GMTOffset:"+1000" },
    { TimeZoneName: "Lord Howe Standard Time", TimeZoneAbbrevation: "LHST", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Lord_Howe", GMTOffset:"+1100" },
    { TimeZoneName: "Australian Eastern Daylight Savings Time", TimeZoneAbbrevation: "AEDT", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Melbourne", GMTOffset:"+1100" },
    { TimeZoneName: "Australian Western Standard Time", TimeZoneAbbrevation: "AWST", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Perth", GMTOffset:"+0800" },
    { TimeZoneName: "Australian Eastern Daylight Savings Time", TimeZoneAbbrevation: "AEDT", CountryCode:"AU", CountryName : "Australia", TimeZone:"Australia/Sydney", GMTOffset:"+1100" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"AT", CountryName : "Austria", TimeZone:"Europe/Vienna", GMTOffset:"+0200" },
    { TimeZoneName: "Azerbaijan Time", TimeZoneAbbrevation: "AZT", CountryCode:"AZ", CountryName : "Azerbaijan", TimeZone:"Asia/Baku", GMTOffset:"+0400" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"BS", CountryName : "Bahamas", TimeZone:"America/Nassau", GMTOffset:"-0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"BH", CountryName : "Bahrain", TimeZone:"Asia/Bahrain", GMTOffset:"+0300" },
    { TimeZoneName: "British Summer Time", TimeZoneAbbrevation: "BST", CountryCode:"BD", CountryName : "Bangladesh", TimeZone:"Asia/Dhaka", GMTOffset:"+0600" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"BB", CountryName : "Barbados", TimeZone:"America/Barbados", GMTOffset:"-0400" },
    { TimeZoneName: "Moscow Time", TimeZoneAbbrevation: "MSK", CountryCode:"BY", CountryName : "Belarus", TimeZone:"Europe/Minsk", GMTOffset:"+0300" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"BE", CountryName : "Belgium", TimeZone:"Europe/Brussels", GMTOffset:"+0200" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"BZ", CountryName : "Belize", TimeZone:"America/Belize", GMTOffset:"-0600" },
    { TimeZoneName: "West Africa Time", TimeZoneAbbrevation: "WAT", CountryCode:"BJ", CountryName : "Benin", TimeZone:"Africa/Porto-Novo", GMTOffset:"+0100" },
    { TimeZoneName: "Atlantic Daylight Time", TimeZoneAbbrevation: "ADT", CountryCode:"BM", CountryName : "Bermuda", TimeZone:"Atlantic/Bermuda", GMTOffset:"-0300" },
    { TimeZoneName: "Bhutan Time", TimeZoneAbbrevation: "BTT", CountryCode:"BT", CountryName : "Bhutan", TimeZone:"Asia/Thimphu", GMTOffset:"+0600" },
    { TimeZoneName: "Bolivia Time", TimeZoneAbbrevation: "BOT", CountryCode:"BO", CountryName : "Bolivia, Plurinational State of", TimeZone:"America/La_Paz", GMTOffset:"-0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"BQ", CountryName : "Bonaire, Sint Eustatius and Saba", TimeZone:"America/Kralendijk", GMTOffset:"-0400" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"BA", CountryName : "Bosnia and Herzegovina", TimeZone:"Europe/Sarajevo", GMTOffset:"+0200" },
    { TimeZoneName: "Central Africa Time", TimeZoneAbbrevation: "CAT", CountryCode:"BW", CountryName : "Botswana", TimeZone:"Africa/Gaborone", GMTOffset:"+0200" },
    { TimeZoneName: "Brasília time", TimeZoneAbbrevation: "BRT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Araguaina", GMTOffset:"-0300" },
    { TimeZoneName: "Brasília time", TimeZoneAbbrevation: "BRT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Bahia", GMTOffset:"-0300" },
    { TimeZoneName: "Brasília time", TimeZoneAbbrevation: "BRT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Belem", GMTOffset:"-0300" },
    { TimeZoneName: "Armenia Time", TimeZoneAbbrevation: "AMT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Boa_Vista", GMTOffset:"-0400" },
    { TimeZoneName: "Armenia Time", TimeZoneAbbrevation: "AMT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Campo_Grande", GMTOffset:"-0400" },
    { TimeZoneName: "Brasília time", TimeZoneAbbrevation: "BRT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Cuiaba", GMTOffset:"-0400" },
    { TimeZoneName: "Australian Central Time", TimeZoneAbbrevation: "ACT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Eirunepe", GMTOffset:"-0500" },
    { TimeZoneName: "Brasília time", TimeZoneAbbrevation: "BRT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Fortaleza", GMTOffset:"-0300" },
    { TimeZoneName: "Brasília time", TimeZoneAbbrevation: "BRT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Maceio", GMTOffset:"-0300" },
    { TimeZoneName: "Armenia Time", TimeZoneAbbrevation: "AMT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Manaus", GMTOffset:"-0400" },
    { TimeZoneName: "Fernando de Noronha Time", TimeZoneAbbrevation: "FNT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Noronha", GMTOffset:"-0200" },
    { TimeZoneName: "Armenia Time", TimeZoneAbbrevation: "AMT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Porto_Velho", GMTOffset:"-0400" },
    { TimeZoneName: "Brasília time", TimeZoneAbbrevation: "BRT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Recife", GMTOffset:"-0300" },
    { TimeZoneName: "Australian Central Time", TimeZoneAbbrevation: "ACT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Rio_Branco", GMTOffset:"-0500" },
    { TimeZoneName: "Brasília time", TimeZoneAbbrevation: "BRT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Santarem", GMTOffset:"-0300" },
    { TimeZoneName: "Brasília time", TimeZoneAbbrevation: "BRT", CountryCode:"BR", CountryName : "Brazil", TimeZone:"America/Sao_Paulo", GMTOffset:"-0300" },
    { TimeZoneName: "Indian Chagos Time", TimeZoneAbbrevation: "IOT", CountryCode:"IO", CountryName : "British Indian Ocean Territory", TimeZone:"Indian/Chagos", GMTOffset:"+0600" },
    { TimeZoneName: "Brunei Darussalam Time", TimeZoneAbbrevation: "BNT", CountryCode:"BN", CountryName : "Brunei Darussalam", TimeZone:"Asia/Brunei", GMTOffset:"+0800" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"BG", CountryName : "Bulgaria", TimeZone:"Europe/Sofia", GMTOffset:"+0300" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "GMT", CountryCode:"BF", CountryName : "Burkina Faso", TimeZone:"Africa/Ouagadougou", GMTOffset:"+0000" },
    { TimeZoneName: "Central Africa Time", TimeZoneAbbrevation: "CAT", CountryCode:"BI", CountryName : "Burundi", TimeZone:"Africa/Bujumbura", GMTOffset:"+0200" },
    { TimeZoneName: "Indochina Time", TimeZoneAbbrevation: "ICT", CountryCode:"KH", CountryName : "Cambodia", TimeZone:"Asia/Phnom_Penh", GMTOffset:"+0700" },
    { TimeZoneName: "West Africa Time", TimeZoneAbbrevation: "WAT", CountryCode:"CM", CountryName : "Cameroon", TimeZone:"Africa/Douala", GMTOffset:"+0100" },
    { TimeZoneName: " Eastern Standard Time", TimeZoneAbbrevation: "EST", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Atikokan", GMTOffset:"-0500" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Blanc-Sablon", GMTOffset:"-0400" },
    { TimeZoneName: "Mountain Daylight Time", TimeZoneAbbrevation: "MDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Cambridge_Bay", GMTOffset:"-0600" },
    { TimeZoneName: "Mountain Standard Time", TimeZoneAbbrevation: "MST", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Creston", GMTOffset:"-0700" },
    { TimeZoneName: "Pacific Time Zone", TimeZoneAbbrevation: "PDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Dawson", GMTOffset:"-0700" },
    { TimeZoneName: "Mountain Standard Time", TimeZoneAbbrevation: "MST", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Dawson_Creek", GMTOffset:"-0700" },
    { TimeZoneName: "Mountain Daylight Time", TimeZoneAbbrevation: "MDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Edmonton", GMTOffset:"-0600" },
    { TimeZoneName: "Mountain Standard Time", TimeZoneAbbrevation: "MST", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Fort_Nelson", GMTOffset:"-0700" },
    { TimeZoneName: "Atlantic Daylight Time", TimeZoneAbbrevation: "ADT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Glace_Bay", GMTOffset:"-0300" },
    { TimeZoneName: "Atlantic Daylight Time", TimeZoneAbbrevation: "ADT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Goose_Bay", GMTOffset:"-0300" },
    { TimeZoneName: "Atlantic Daylight Time", TimeZoneAbbrevation: "ADT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Halifax", GMTOffset:"-0300" },
    { TimeZoneName: "Mountain Daylight Time", TimeZoneAbbrevation: "MDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Inuvik", GMTOffset:"-0600" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Iqaluit", GMTOffset:"-0400" },
    { TimeZoneName: "Atlantic Daylight Time", TimeZoneAbbrevation: "ADT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Moncton", GMTOffset:"-0300" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Nipigon", GMTOffset:"-0400" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Pangnirtung", GMTOffset:"-0400" },
    { TimeZoneName: "Central Daylight Time", TimeZoneAbbrevation: "CDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Rainy_River", GMTOffset:"-0500" },
    { TimeZoneName: "Central Daylight Time", TimeZoneAbbrevation: "CDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Rankin_Inlet", GMTOffset:"-0500" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Regina", GMTOffset:"-0600" },
    { TimeZoneName: "Central Daylight Time", TimeZoneAbbrevation: "CDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Resolute", GMTOffset:"-0500" },
    { TimeZoneName: "Newfoundland Daylight Time", TimeZoneAbbrevation: "NDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/St_Johns", GMTOffset:"-0230" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Swift_Current", GMTOffset:"-0600" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Thunder_Bay", GMTOffset:"-0400" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Toronto", GMTOffset:"-0400" },
    { TimeZoneName: "Pacific Time Zone", TimeZoneAbbrevation: "PDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Vancouver", GMTOffset:"-0700" },
    { TimeZoneName: "Pacific Time Zone", TimeZoneAbbrevation: "PDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Whitehorse", GMTOffset:"-0700" },
    { TimeZoneName: "Central Daylight Time", TimeZoneAbbrevation: "CDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Winnipeg", GMTOffset:"-0500" },
    { TimeZoneName: "Mountain Daylight Time", TimeZoneAbbrevation: "MDT", CountryCode:"CA", CountryName : "Canada", TimeZone:"America/Yellowknife", GMTOffset:"-0600" },
    { TimeZoneName: "Cape Verde Time", TimeZoneAbbrevation: "CVT", CountryCode:"CV", CountryName : "Cape Verde", TimeZone:"Atlantic/Cape_Verde", GMTOffset:"-0100" },
    { TimeZoneName: " Eastern Standard Time", TimeZoneAbbrevation: "EST", CountryCode:"KY", CountryName : "Cayman Islands", TimeZone:"America/Cayman", GMTOffset:"-0500" },
    { TimeZoneName: "West Africa Time", TimeZoneAbbrevation: "WAT", CountryCode:"CF", CountryName : "Central African Republic", TimeZone:"Africa/Bangui", GMTOffset:"+0100" },
    { TimeZoneName: "West Africa Time", TimeZoneAbbrevation: "WAT", CountryCode:"TD", CountryName : "Chad", TimeZone:"Africa/Ndjamena", GMTOffset:"+0100" },
    { TimeZoneName: "Chile Summer Time", TimeZoneAbbrevation: "CLST", CountryCode:"CL", CountryName : "Chile", TimeZone:"America/Punta_Arenas", GMTOffset:"-0300" },
    { TimeZoneName: "Chile Summer Time", TimeZoneAbbrevation: "CLST", CountryCode:"CL", CountryName : "Chile", TimeZone:"America/Santiago", GMTOffset:"-0300" },
    { TimeZoneName: "Easter Island Summer Time", TimeZoneAbbrevation: "EASST", CountryCode:"CL", CountryName : "Chile", TimeZone:"Pacific/Easter", GMTOffset:"-0500" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"CN", CountryName : "China", TimeZone:"Asia/Shanghai", GMTOffset:"+0800" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "URUT", CountryCode:"CN", CountryName : "China", TimeZone:"Asia/Urumqi", GMTOffset:"+0600" },
    { TimeZoneName: "Christmas Island Time", TimeZoneAbbrevation: "CXT", CountryCode:"CX", CountryName : "Christmas Island", TimeZone:"Indian/Christmas", GMTOffset:"+0700" },
    { TimeZoneName: "Cocos Islands Time", TimeZoneAbbrevation: "CCT", CountryCode:"CC", CountryName : "Cocos (Keeling) Islands", TimeZone:"Indian/Cocos", GMTOffset:"+0630" },
    { TimeZoneName: "Colombia Time", TimeZoneAbbrevation: "COT", CountryCode:"CO", CountryName : "Colombia", TimeZone:"America/Bogota", GMTOffset:"-0500" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"KM", CountryName : "Comoros", TimeZone:"Indian/Comoro", GMTOffset:"+0300" },
    { TimeZoneName: "West Africa Time", TimeZoneAbbrevation: "WAT", CountryCode:"CG", CountryName : "Congo", TimeZone:"Africa/Brazzaville", GMTOffset:"+0100" },
    { TimeZoneName: "West Africa Time", TimeZoneAbbrevation: "WAT", CountryCode:"CD", CountryName : "Congo, the Democratic Republic of the", TimeZone:"Africa/Kinshasa", GMTOffset:"+0100" },
    { TimeZoneName: "Central Africa Time", TimeZoneAbbrevation: "CAT", CountryCode:"CD", CountryName : "Congo, the Democratic Republic of the", TimeZone:"Africa/Lubumbashi", GMTOffset:"+0200" },
    { TimeZoneName: "Cook Island Time", TimeZoneAbbrevation: "CKT", CountryCode:"CK", CountryName : "Cook Islands", TimeZone:"Pacific/Rarotonga", GMTOffset:"-1000" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"CR", CountryName : "Costa Rica", TimeZone:"America/Costa_Rica", GMTOffset:"-0600" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"HR", CountryName : "Croatia", TimeZone:"Europe/Zagreb", GMTOffset:"+0200" },
    { TimeZoneName: "Central Daylight Time", TimeZoneAbbrevation: "CDT", CountryCode:"CU", CountryName : "Cuba", TimeZone:"America/Havana", GMTOffset:"-0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"CW", CountryName : "Curaçao", TimeZone:"America/Curacao", GMTOffset:"-0400" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"CY", CountryName : "Cyprus", TimeZone:"Asia/Famagusta", GMTOffset:"+0300" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"CY", CountryName : "Cyprus", TimeZone:"Asia/Nicosia", GMTOffset:"+0300" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"CZ", CountryName : "Czech Republic", TimeZone:"Europe/Prague", GMTOffset:"+0200" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "GMT", CountryCode:"CI", CountryName : "Côte d'Ivoire", TimeZone:"Africa/Abidjan", GMTOffset:"+0000" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"DK", CountryName : "Denmark", TimeZone:"Europe/Copenhagen", GMTOffset:"+0200" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"DJ", CountryName : "Djibouti", TimeZone:"Africa/Djibouti", GMTOffset:"+0300" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"DM", CountryName : "Dominica", TimeZone:"America/Dominica", GMTOffset:"-0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"DO", CountryName : "Dominican Republic", TimeZone:"America/Santo_Domingo", GMTOffset:"-0400" },
    { TimeZoneName: "Ecuador Time", TimeZoneAbbrevation: "ECT", CountryCode:"EC", CountryName : "Ecuador", TimeZone:"America/Guayaquil", GMTOffset:"-0500" },
    { TimeZoneName: "Galapagos Time", TimeZoneAbbrevation: "GALT", CountryCode:"EC", CountryName : "Ecuador", TimeZone:"Pacific/Galapagos", GMTOffset:"-0600" },
    { TimeZoneName: "Eastern European Time", TimeZoneAbbrevation: "EET", CountryCode:"EG", CountryName : "Egypt", TimeZone:"Africa/Cairo", GMTOffset:"+0200" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"SV", CountryName : "El Salvador", TimeZone:"America/El_Salvador", GMTOffset:"-0600" },
    { TimeZoneName: "West Africa Time", TimeZoneAbbrevation: "WAT", CountryCode:"GQ", CountryName : "Equatorial Guinea", TimeZone:"Africa/Malabo", GMTOffset:"+0100" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"ER", CountryName : "Eritrea", TimeZone:"Africa/Asmara", GMTOffset:"+0300" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"EE", CountryName : "Estonia", TimeZone:"Europe/Tallinn", GMTOffset:"+0300" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"ET", CountryName : "Ethiopia", TimeZone:"Africa/Addis_Ababa", GMTOffset:"+0300" },
    { TimeZoneName: "Falkland Islands Time", TimeZoneAbbrevation: "FKT", CountryCode:"FK", CountryName : "Falkland Islands (Malvinas)", TimeZone:"Atlantic/Stanley", GMTOffset:"-0300" },
    { TimeZoneName: "Western European Summer Time", TimeZoneAbbrevation: "WEST", CountryCode:"FO", CountryName : "Faroe Islands", TimeZone:"Atlantic/Faroe", GMTOffset:"+0100" },
    { TimeZoneName: "Fiji Time", TimeZoneAbbrevation: "FJT", CountryCode:"FJ", CountryName : "Fiji", TimeZone:"Pacific/Fiji", GMTOffset:"+1200" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"FI", CountryName : "Finland", TimeZone:"Europe/Helsinki", GMTOffset:"+0300" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"FR", CountryName : "France", TimeZone:"Europe/Paris", GMTOffset:"+0200" },
    { TimeZoneName: "French Guiana Time", TimeZoneAbbrevation: "GFT", CountryCode:"GF", CountryName : "French Guiana", TimeZone:"America/Cayenne", GMTOffset:"-0300" },
    { TimeZoneName: "Gambier Time", TimeZoneAbbrevation: "GAMT", CountryCode:"PF", CountryName : "French Polynesia", TimeZone:"Pacific/Gambier", GMTOffset:"-0900" },
    { TimeZoneName: "Marquesas Time", TimeZoneAbbrevation: "MART", CountryCode:"PF", CountryName : "French Polynesia", TimeZone:"Pacific/Marquesas", GMTOffset:"-0930" },
    { TimeZoneName: "Tahiti Time", TimeZoneAbbrevation: "TAHT", CountryCode:"PF", CountryName : "French Polynesia", TimeZone:"Pacific/Tahiti", GMTOffset:"-1000" },
    { TimeZoneName: "French Southern and Antarctic Time ", TimeZoneAbbrevation: "TFT", CountryCode:"TF", CountryName : "French Southern Territories", TimeZone:"Indian/Kerguelen", GMTOffset:"+0500" },
    { TimeZoneName: "West Africa Time", TimeZoneAbbrevation: "WAT", CountryCode:"GA", CountryName : "Gabon", TimeZone:"Africa/Libreville", GMTOffset:"+0100" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "GMT", CountryCode:"GM", CountryName : "Gambia", TimeZone:"Africa/Banjul", GMTOffset:"+0000" },
    { TimeZoneName: "Georgia Standard Time", TimeZoneAbbrevation: "GET", CountryCode:"GE", CountryName : "Georgia", TimeZone:"Asia/Tbilisi", GMTOffset:"+0400" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"DE", CountryName : "Germany", TimeZone:"Europe/Berlin", GMTOffset:"+0200" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"DE", CountryName : "Germany", TimeZone:"Europe/Busingen", GMTOffset:"+0200" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "GMT", CountryCode:"GH", CountryName : "Ghana", TimeZone:"Africa/Accra", GMTOffset:"+0000" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"GI", CountryName : "Gibraltar", TimeZone:"Europe/Gibraltar", GMTOffset:"+0200" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"GR", CountryName : "Greece", TimeZone:"Europe/Athens", GMTOffset:"+0300" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "GMT", CountryCode:"GL", CountryName : "Greenland", TimeZone:"America/Danmarkshavn", GMTOffset:"+0000" },
    { TimeZoneName: "Western Greenland Summer Time", TimeZoneAbbrevation: "WGST", CountryCode:"GL", CountryName : "Greenland", TimeZone:"America/Nuuk", GMTOffset:"-0200" },
    { TimeZoneName: "Eastern Greenland Summer Time", TimeZoneAbbrevation: "EGST", CountryCode:"GL", CountryName : "Greenland", TimeZone:"America/Scoresbysund", GMTOffset:"+0000" },
    { TimeZoneName: "Atlantic Daylight Time", TimeZoneAbbrevation: "ADT", CountryCode:"GL", CountryName : "Greenland", TimeZone:"America/Thule", GMTOffset:"-0300" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"GD", CountryName : "Grenada", TimeZone:"America/Grenada", GMTOffset:"-0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"GP", CountryName : "Guadeloupe", TimeZone:"America/Guadeloupe", GMTOffset:"-0400" },
    { TimeZoneName: "Chamorro Standard Time", TimeZoneAbbrevation: "CHST", CountryCode:"GU", CountryName : "Guam", TimeZone:"Pacific/Guam", GMTOffset:"+1000" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"GT", CountryName : "Guatemala", TimeZone:"America/Guatemala", GMTOffset:"-0600" },
    { TimeZoneName: "British Summer Time", TimeZoneAbbrevation: "BST", CountryCode:"GG", CountryName : "Guernsey", TimeZone:"Europe/Guernsey", GMTOffset:"+0100" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "GMT", CountryCode:"GN", CountryName : "Guinea", TimeZone:"Africa/Conakry", GMTOffset:"+0000" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "GMT", CountryCode:"GW", CountryName : "Guinea-Bissau", TimeZone:"Africa/Bissau", GMTOffset:"+0000" },
    { TimeZoneName: "Guyana Time", TimeZoneAbbrevation: "GYT", CountryCode:"GY", CountryName : "Guyana", TimeZone:"America/Guyana", GMTOffset:"-0400" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"HT", CountryName : "Haiti", TimeZone:"America/Port-au-Prince", GMTOffset:"-0400" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"VA", CountryName : "Holy See (Vatican City State)", TimeZone:"Europe/Vatican", GMTOffset:"+0200" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"HN", CountryName : "Honduras", TimeZone:"America/Tegucigalpa", GMTOffset:"-0600" },
    { TimeZoneName: "Hong Kong Time", TimeZoneAbbrevation: "HKT", CountryCode:"HK", CountryName : "Hong Kong", TimeZone:"Asia/Hong_Kong", GMTOffset:"+0800" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"HU", CountryName : "Hungary", TimeZone:"Europe/Budapest", GMTOffset:"+0200" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "GMT", CountryCode:"IS", CountryName : "Iceland", TimeZone:"Atlantic/Reykjavik", GMTOffset:"+0000" },
    { TimeZoneName: "Indian Standard Time", TimeZoneAbbrevation: "IST", CountryCode:"IN", CountryName : "India", TimeZone:"Asia/Kolkata", GMTOffset:"+0530" },
    { TimeZoneName: "Western Indonesia Time", TimeZoneAbbrevation: "WIB", CountryCode:"ID", CountryName : "Indonesia", TimeZone:"Asia/Jakarta", GMTOffset:"+0700" },
    { TimeZoneName: "Eastern Indonesia Time", TimeZoneAbbrevation: "WIT", CountryCode:"ID", CountryName : "Indonesia", TimeZone:"Asia/Jayapura", GMTOffset:"+0900" },
    { TimeZoneName: "Central Indonesia Time", TimeZoneAbbrevation: "WITA", CountryCode:"ID", CountryName : "Indonesia", TimeZone:"Asia/Makassar", GMTOffset:"+0800" },
    { TimeZoneName: "Western Indonesia Time", TimeZoneAbbrevation: "WIB", CountryCode:"ID", CountryName : "Indonesia", TimeZone:"Asia/Pontianak", GMTOffset:"+0700" },
    { TimeZoneName: "Iran Daylight Time", TimeZoneAbbrevation: "IRDT", CountryCode:"IR", CountryName : "Iran, Islamic Republic of", TimeZone:"Asia/Tehran", GMTOffset:"+0330" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"IQ", CountryName : "Iraq", TimeZone:"Asia/Baghdad", GMTOffset:"+0300" },
    { TimeZoneName: "Ireland Standard Time", TimeZoneAbbrevation: "IST", CountryCode:"IE", CountryName : "Ireland", TimeZone:"Europe/Dublin", GMTOffset:"+0100" },
    { TimeZoneName: "British Summer Time", TimeZoneAbbrevation: "BST", CountryCode:"IM", CountryName : "Isle of Man", TimeZone:"Europe/Isle_of_Man", GMTOffset:"+0100" },
    { TimeZoneName: "Israel Daylight Time", TimeZoneAbbrevation: "IDT", CountryCode:"IL", CountryName : "Israel", TimeZone:"Asia/Jerusalem", GMTOffset:"+0300" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"IT", CountryName : "Italy", TimeZone:"Europe/Rome", GMTOffset:"+0200" },
    { TimeZoneName: " Eastern Standard Time", TimeZoneAbbrevation: "EST", CountryCode:"JM", CountryName : "Jamaica", TimeZone:"America/Jamaica", GMTOffset:"-0500" },
    { TimeZoneName: "Japan Standard Time", TimeZoneAbbrevation: "JST", CountryCode:"JP", CountryName : "Japan", TimeZone:"Asia/Tokyo", GMTOffset:"+0900" },
    { TimeZoneName: "British Summer Time", TimeZoneAbbrevation: "BST", CountryCode:"JE", CountryName : "Jersey", TimeZone:"Europe/Jersey", GMTOffset:"+0100" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"JO", CountryName : "Jordan", TimeZone:"Asia/Amman", GMTOffset:"+0300" },
    { TimeZoneName: "Alma-Ata Time", TimeZoneAbbrevation: "ALMT", CountryCode:"KZ", CountryName : "Kazakhstan", TimeZone:"Asia/Almaty", GMTOffset:"+0600" },
    { TimeZoneName: "Moscow Daylight Time", TimeZoneAbbrevation: "MSD+1", CountryCode:"KZ", CountryName : "Kazakhstan", TimeZone:"Asia/Aqtau", GMTOffset:"+0500" },
    { TimeZoneName: "Aqtobe Time", TimeZoneAbbrevation: "AQTT", CountryCode:"KZ", CountryName : "Kazakhstan", TimeZone:"Asia/Aqtobe", GMTOffset:"+0500" },
    { TimeZoneName: "Moscow Daylight Time", TimeZoneAbbrevation: "MSD+1", CountryCode:"KZ", CountryName : "Kazakhstan", TimeZone:"Asia/Atyrau", GMTOffset:"+0500" },
    { TimeZoneName: "Oral Summer Time", TimeZoneAbbrevation: "ORAST", CountryCode:"KZ", CountryName : "Kazakhstan", TimeZone:"Asia/Oral", GMTOffset:"+0500" },
    { TimeZoneName: "Qyzylorda Summer Time", TimeZoneAbbrevation: "QYZST", CountryCode:"KZ", CountryName : "Kazakhstan", TimeZone:"Asia/Qostanay", GMTOffset:"+0600" },
    { TimeZoneName: "Moskow Standard Time", TimeZoneAbbrevation: "MSK+2", CountryCode:"KZ", CountryName : "Kazakhstan", TimeZone:"Asia/Qyzylorda", GMTOffset:"+0500" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"KE", CountryName : "Kenya", TimeZone:"Africa/Nairobi", GMTOffset:"+0300" },
    { TimeZoneName: "Phoenix Island Time", TimeZoneAbbrevation: "PHOT", CountryCode:"KI", CountryName : "Kiribati", TimeZone:"Pacific/Enderbury", GMTOffset:"+1300" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "LINT", CountryCode:"KI", CountryName : "Kiribati", TimeZone:"Pacific/Kiritimati", GMTOffset:"+1400" },
    { TimeZoneName: "Gilbert Island Time", TimeZoneAbbrevation: "GILT", CountryCode:"KI", CountryName : "Kiribati", TimeZone:"Pacific/Tarawa", GMTOffset:"+1200" },
    { TimeZoneName: "Korea Standard Time ", TimeZoneAbbrevation: "KST", CountryCode:"KP", CountryName : "Korea, Democratic People's Republic of", TimeZone:"Asia/Pyongyang", GMTOffset:"+0900" },
    { TimeZoneName: "Korea Standard Time ", TimeZoneAbbrevation: "KST", CountryCode:"KR", CountryName : "Korea, Republic of", TimeZone:"Asia/Seoul", GMTOffset:"+0900" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"KW", CountryName : "Kuwait", TimeZone:"Asia/Kuwait", GMTOffset:"+0300" },
    { TimeZoneName: "Kyrgyzstan Summer Time	", TimeZoneAbbrevation: "KGST", CountryCode:"KG", CountryName : "Kyrgyzstan", TimeZone:"Asia/Bishkek", GMTOffset:"+0600" },
    { TimeZoneName: "Indochina Time ", TimeZoneAbbrevation: "ICT", CountryCode:"LA", CountryName : "Lao People's Democratic Republic", TimeZone:"Asia/Vientiane", GMTOffset:"+0700" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"LV", CountryName : "Latvia", TimeZone:"Europe/Riga", GMTOffset:"+0300" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"LB", CountryName : "Lebanon", TimeZone:"Asia/Beirut", GMTOffset:"+0300" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "SAST", CountryCode:"LS", CountryName : "Lesotho", TimeZone:"Africa/Maseru", GMTOffset:"+0200" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "GMT", CountryCode:"LR", CountryName : "Liberia", TimeZone:"Africa/Monrovia", GMTOffset:"+0000" },
    { TimeZoneName: "Eastern European Time", TimeZoneAbbrevation: "EET", CountryCode:"LY", CountryName : "Libya", TimeZone:"Africa/Tripoli", GMTOffset:"+0200" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"LI", CountryName : "Liechtenstein", TimeZone:"Europe/Vaduz", GMTOffset:"+0200" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"LT", CountryName : "Lithuania", TimeZone:"Europe/Vilnius", GMTOffset:"+0300" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"LU", CountryName : "Luxembourg", TimeZone:"Europe/Luxembourg", GMTOffset:"+0200" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"MO", CountryName : "Macao", TimeZone:"Asia/Macau", GMTOffset:"+0800" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"MK", CountryName : "Macedonia, the Former Yugoslav Republic of", TimeZone:"Europe/Skopje", GMTOffset:"+0200" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"MG", CountryName : "Madagascar", TimeZone:"Indian/Antananarivo", GMTOffset:"+0300" },
    { TimeZoneName: "Central Africa Time", TimeZoneAbbrevation: "CAT", CountryCode:"MW", CountryName : "Malawi", TimeZone:"Africa/Blantyre", GMTOffset:"+0200" },
    { TimeZoneName: "Malaysia Time", TimeZoneAbbrevation: "MYT", CountryCode:"MY", CountryName : "Malaysia", TimeZone:"Asia/Kuala_Lumpur", GMTOffset:"+0800" },
    { TimeZoneName: "Malaysia Time", TimeZoneAbbrevation: "MYT", CountryCode:"MY", CountryName : "Malaysia", TimeZone:"Asia/Kuching", GMTOffset:"+0800" },
    { TimeZoneName: "Maldives Time", TimeZoneAbbrevation: "MVT", CountryCode:"MV", CountryName : "Maldives", TimeZone:"Indian/Maldives", GMTOffset:"+0500" },
    { TimeZoneName: "Greenwich Mean Time ", TimeZoneAbbrevation: "GMT", CountryCode:"ML", CountryName : "Mali", TimeZone:"Africa/Bamako", GMTOffset:"+0000" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"MT", CountryName : "Malta", TimeZone:"Europe/Malta", GMTOffset:"+0200" },
    { TimeZoneName: "Pacific Time", TimeZoneAbbrevation: "+12", CountryCode:"MH", CountryName : "Marshall Islands", TimeZone:"Pacific/Kwajalein", GMTOffset:"+1200" },
    { TimeZoneName: "Pacific MAjuro Time", TimeZoneAbbrevation: "+12", CountryCode:"MH", CountryName : "Marshall Islands", TimeZone:"Pacific/Majuro", GMTOffset:"+1200" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"MQ", CountryName : "Martinique", TimeZone:"America/Martinique", GMTOffset:"-0400" },
    { TimeZoneName: "Greenwich Mean Time ", TimeZoneAbbrevation: "GMT", CountryCode:"MR", CountryName : "Mauritania", TimeZone:"Africa/Nouakchott", GMTOffset:"+0000" },
    { TimeZoneName: "Mauritius Time", TimeZoneAbbrevation: "MUT", CountryCode:"MU", CountryName : "Mauritius", TimeZone:"Indian/Mauritius", GMTOffset:"+0400" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"YT", CountryName : "Mayotte", TimeZone:"Indian/Mayotte", GMTOffset:"+0300" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Bahia_Banderas", GMTOffset:"-0500" },
    { TimeZoneName: " Eastern Standard Time ", TimeZoneAbbrevation: "EST", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Cancun", GMTOffset:"-0500" },
    { TimeZoneName: " Mountain Daylight Time", TimeZoneAbbrevation: "MDT", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Chihuahua", GMTOffset:"-0600" },
    { TimeZoneName: " Mountain Standard Time ", TimeZoneAbbrevation: "MST", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Hermosillo", GMTOffset:"-0700" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Matamoros", GMTOffset:"-0500" },
    { TimeZoneName: " Mountain Daylight Time", TimeZoneAbbrevation: "MDT", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Mazatlan", GMTOffset:"-0600" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Merida", GMTOffset:"-0500" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Mexico_City", GMTOffset:"-0500" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Monterrey", GMTOffset:"-0500" },
    { TimeZoneName: "Mountain Daylight Time", TimeZoneAbbrevation: "MDT", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Ojinaga", GMTOffset:"-0600" },
    { TimeZoneName: "Pacific Daylight Time", TimeZoneAbbrevation: "PDT", CountryCode:"MX", CountryName : "Mexico", TimeZone:"America/Tijuana", GMTOffset:"-0700" },
    { TimeZoneName: "Chuuk Time ", TimeZoneAbbrevation: "CHUT", CountryCode:"FM", CountryName : "Micronesia, Federated States of", TimeZone:"Pacific/Chuuk", GMTOffset:"+1000" },
    { TimeZoneName: "Kosrae Time", TimeZoneAbbrevation: "KOST", CountryCode:"FM", CountryName : "Micronesia, Federated States of", TimeZone:"Pacific/Kosrae", GMTOffset:"+1100" },
    { TimeZoneName: "Pohnpei Standard Time", TimeZoneAbbrevation: "PONT", CountryCode:"FM", CountryName : "Micronesia, Federated States of", TimeZone:"Pacific/Pohnpei", GMTOffset:"+1100" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"MD", CountryName : "Moldova, Republic of", TimeZone:"Europe/Chisinau", GMTOffset:"+0300" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"MC", CountryName : "Monaco", TimeZone:"Europe/Monaco", GMTOffset:"+0200" },
    { TimeZoneName: "Choibalsan Time ", TimeZoneAbbrevation: "CHOT", CountryCode:"MN", CountryName : "Mongolia", TimeZone:"Asia/Choibalsan", GMTOffset:"+0800" },
    { TimeZoneName: "Hovd Time", TimeZoneAbbrevation: "HOVT", CountryCode:"MN", CountryName : "Mongolia", TimeZone:"Asia/Hovd", GMTOffset:"+0700" },
    { TimeZoneName: "Ulaanbaatar Time", TimeZoneAbbrevation: "ULAT", CountryCode:"MN", CountryName : "Mongolia", TimeZone:"Asia/Ulaanbaatar", GMTOffset:"+0800" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"ME", CountryName : "Montenegro", TimeZone:"Europe/Podgorica", GMTOffset:"+0200" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"MS", CountryName : "Montserrat", TimeZone:"America/Montserrat", GMTOffset:"-0400" },
    { TimeZoneName: "Western European Summer Time", TimeZoneAbbrevation: "WEST", CountryCode:"MA", CountryName : "Morocco", TimeZone:"Africa/Casablanca", GMTOffset:"+0100" },
    { TimeZoneName: "Central Africa Time", TimeZoneAbbrevation: "CAT", CountryCode:"MZ", CountryName : "Mozambique", TimeZone:"Africa/Maputo", GMTOffset:"+0200" },
    { TimeZoneName: "Myanmar Standard Time", TimeZoneAbbrevation: "MMT", CountryCode:"MM", CountryName : "Myanmar", TimeZone:"Asia/Yangon", GMTOffset:"+0630" },
    { TimeZoneName: "Central Africa Time", TimeZoneAbbrevation: "CAT", CountryCode:"NA", CountryName : "Namibia", TimeZone:"Africa/Windhoek", GMTOffset:"+0200" },
    { TimeZoneName: "Nauru Time", TimeZoneAbbrevation: "NRT", CountryCode:"NR", CountryName : "Nauru", TimeZone:"Pacific/Nauru", GMTOffset:"+1200" },
    { TimeZoneName: "Nepal Time ", TimeZoneAbbrevation: "NPT", CountryCode:"NP", CountryName : "Nepal", TimeZone:"Asia/Kathmandu", GMTOffset:"+0545" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"NL", CountryName : "Netherlands", TimeZone:"Europe/Amsterdam", GMTOffset:"+0200" },
    { TimeZoneName: "New Caledonia Time", TimeZoneAbbrevation: "NCT", CountryCode:"NC", CountryName : "New Caledonia", TimeZone:"Pacific/Noumea", GMTOffset:"+1100" },
    { TimeZoneName: "New Zealand Daylight Time", TimeZoneAbbrevation: "NZDT", CountryCode:"NZ", CountryName : "New Zealand", TimeZone:"Pacific/Auckland", GMTOffset:"+1300" },
    { TimeZoneName: "Chatham Standard Time", TimeZoneAbbrevation: "CHAST", CountryCode:"NZ", CountryName : "New Zealand", TimeZone:"Pacific/Chatham", GMTOffset:"+1345" },
    { TimeZoneName: "Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"NI", CountryName : "Nicaragua", TimeZone:"America/Managua", GMTOffset:"-0600" },
    { TimeZoneName: "West Africa Time ", TimeZoneAbbrevation: "WAT", CountryCode:"NE", CountryName : "Niger", TimeZone:"Africa/Niamey", GMTOffset:"+0100" },
    { TimeZoneName: "West Africa Time ", TimeZoneAbbrevation: "WAT", CountryCode:"NG", CountryName : "Nigeria", TimeZone:"Africa/Lagos", GMTOffset:"+0100" },
    { TimeZoneName: "Niue Time", TimeZoneAbbrevation: "NUT", CountryCode:"NU", CountryName : "Niue", TimeZone:"Pacific/Niue", GMTOffset:"-1100" },
    { TimeZoneName: "Norfolk Daylight Time ", TimeZoneAbbrevation: "NFDT", CountryCode:"NF", CountryName : "Norfolk Island", TimeZone:"Pacific/Norfolk", GMTOffset:"+1200" },
    { TimeZoneName: "Chamorro Standard Time  ", TimeZoneAbbrevation: "ChST", CountryCode:"MP", CountryName : "Northern Mariana Islands", TimeZone:"Pacific/Saipan", GMTOffset:"+1000" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"NO", CountryName : "Norway", TimeZone:"Europe/Oslo", GMTOffset:"+0200" },
    { TimeZoneName: "Gulf Standard Time ", TimeZoneAbbrevation: "GST", CountryCode:"OM", CountryName : "Oman", TimeZone:"Asia/Muscat", GMTOffset:"+0400" },
    { TimeZoneName: "Pakistan Standard Time ", TimeZoneAbbrevation: "PKT", CountryCode:"PK", CountryName : "Pakistan", TimeZone:"Asia/Karachi", GMTOffset:"+0500" },
    { TimeZoneName: " ", TimeZoneAbbrevation: "+09", CountryCode:"PW", CountryName : "Palau", TimeZone:"Pacific/Palau", GMTOffset:"+0900" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"PS", CountryName : "Palestine, State of", TimeZone:"Asia/Gaza", GMTOffset:"+0300" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"PS", CountryName : "Palestine, State of", TimeZone:"Asia/Hebron", GMTOffset:"+0300" },
    { TimeZoneName: " Eastern Standard Time", TimeZoneAbbrevation: "EST", CountryCode:"PA", CountryName : "Panama", TimeZone:"America/Panama", GMTOffset:"-0500" },
    { TimeZoneName: "British Summer Time  ", TimeZoneAbbrevation: "BST", CountryCode:"PG", CountryName : "Papua New Guinea", TimeZone:"Pacific/Bougainville", GMTOffset:"+1100" },
    { TimeZoneName: "Papua New Guinea Time", TimeZoneAbbrevation: "PGT", CountryCode:"PG", CountryName : "Papua New Guinea", TimeZone:"Pacific/Port_Moresby", GMTOffset:"+1000" },
    { TimeZoneName: "Paraguay Summer Time", TimeZoneAbbrevation: "PYST", CountryCode:"PY", CountryName : "Paraguay", TimeZone:"America/Asuncion", GMTOffset:"-0300" },
    { TimeZoneName: "Peru Time", TimeZoneAbbrevation: "PET", CountryCode:"PE", CountryName : "Peru", TimeZone:"America/Lima", GMTOffset:"-0500" },
    { TimeZoneName: " Pacific Standard Time ", TimeZoneAbbrevation: "PST", CountryCode:"PH", CountryName : "Philippines", TimeZone:"Asia/Manila", GMTOffset:"+0800" },
    { TimeZoneName: " Pacific Standard Time ", TimeZoneAbbrevation: "PST", CountryCode:"PN", CountryName : "Pitcairn", TimeZone:"Pacific/Pitcairn", GMTOffset:"-0800" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"PL", CountryName : "Poland", TimeZone:"Europe/Warsaw", GMTOffset:"+0200" },
    { TimeZoneName: "Azores Standard Time ", TimeZoneAbbrevation: "AZOST", CountryCode:"PT", CountryName : "Portugal", TimeZone:"Atlantic/Azores", GMTOffset:"+0000" },
    { TimeZoneName: "Western European Summer Time", TimeZoneAbbrevation: "WEST", CountryCode:"PT", CountryName : "Portugal", TimeZone:"Atlantic/Madeira", GMTOffset:"+0100" },
    { TimeZoneName: "Western European Summer Time", TimeZoneAbbrevation: "WEST", CountryCode:"PT", CountryName : "Portugal", TimeZone:"Europe/Lisbon", GMTOffset:"+0100" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"PR", CountryName : "Puerto Rico", TimeZone:"America/Puerto_Rico", GMTOffset:"-0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"QA", CountryName : "Qatar", TimeZone:"Asia/Qatar", GMTOffset:"+0300" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"RO", CountryName : "Romania", TimeZone:"Europe/Bucharest", GMTOffset:"+0300" },
    { TimeZoneName: "Anadyr Time", TimeZoneAbbrevation: "ANAT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Anadyr", GMTOffset:"+1200" },
    { TimeZoneName: "Moscow Standard Time ", TimeZoneAbbrevation: "MSK+4", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Barnaul", GMTOffset:"+0700" },
    { TimeZoneName: "Yakutsk Time", TimeZoneAbbrevation: "YAKT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Chita", GMTOffset:"+0900" },
    { TimeZoneName: "Irkutsk Time", TimeZoneAbbrevation: "IRKT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Irkutsk", GMTOffset:"+0800" },
    { TimeZoneName: "Kamchatka Time", TimeZoneAbbrevation: "PETT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Kamchatka", GMTOffset:"+1200" },
    { TimeZoneName: "Yakutsk Time", TimeZoneAbbrevation: "YAKT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Khandyga", GMTOffset:"+0900" },
    { TimeZoneName: "Krasnoyarsk Time", TimeZoneAbbrevation: "KRAT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Krasnoyarsk", GMTOffset:"+0700" },
    { TimeZoneName: "Magadan Time", TimeZoneAbbrevation: "MAGT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Magadan", GMTOffset:"+1100" },
    { TimeZoneName: "Krasnoyarsk Time", TimeZoneAbbrevation: "KRAT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Novokuznetsk", GMTOffset:"+0700" },
    { TimeZoneName: "Novosibirsk Time", TimeZoneAbbrevation: "NOVT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Novosibirsk", GMTOffset:"+0700" },
    { TimeZoneName: "Omsk Standard Time", TimeZoneAbbrevation: "OMST", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Omsk", GMTOffset:"+0600" },
    { TimeZoneName: "Sakhalin Time ", TimeZoneAbbrevation: "SAKT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Sakhalin", GMTOffset:"+1100" },
    { TimeZoneName: "Srednekolymsk Time ", TimeZoneAbbrevation: "SRET", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Srednekolymsk", GMTOffset:"+1100" },
    { TimeZoneName: "Moscow Daylight Time", TimeZoneAbbrevation: "MSD+3", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Tomsk", GMTOffset:"+0700" },
    { TimeZoneName: "Vladivostok Time", TimeZoneAbbrevation: "VLAT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Ust-Nera", GMTOffset:"+1000" },
    { TimeZoneName: "Vladivostok Time", TimeZoneAbbrevation: "VLAT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Vladivostok", GMTOffset:"+1000" },
    { TimeZoneName: "Yakutsk Time", TimeZoneAbbrevation: "YAKT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Yakutsk", GMTOffset:"+0900" },
    { TimeZoneName: "Yekaterinburg Time ", TimeZoneAbbrevation: "YEKT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Asia/Yekaterinburg", GMTOffset:"+0500" },
    { TimeZoneName: "Moscow Standard Time", TimeZoneAbbrevation: "MSK+1", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Europe/Astrakhan", GMTOffset:"+0400" },
    { TimeZoneName: "Eastern European Time", TimeZoneAbbrevation: "EET", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Europe/Kaliningrad", GMTOffset:"+0200" },
    { TimeZoneName: "Moscow Standard Time", TimeZoneAbbrevation: "MSK", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Europe/Kirov", GMTOffset:"+0300" },
    { TimeZoneName: "Moscow Standard Time", TimeZoneAbbrevation: "MSK", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Europe/Moscow", GMTOffset:"+0300" },
    { TimeZoneName: "Samara Time", TimeZoneAbbrevation: "SAMT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Europe/Samara", GMTOffset:"+0400" },
    { TimeZoneName: "Moscow Daylight Time", TimeZoneAbbrevation: "MSD", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Europe/Saratov", GMTOffset:"+0400" },
    { TimeZoneName: "Moscow Standard Time", TimeZoneAbbrevation: "MSK+1", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Europe/Ulyanovsk", GMTOffset:"+0400" },
    { TimeZoneName: "Volgograd Time", TimeZoneAbbrevation: "VOLT", CountryCode:"RU", CountryName : "Russian Federation", TimeZone:"Europe/Volgograd", GMTOffset:"+0400" },
    { TimeZoneName: "Central Africa Time", TimeZoneAbbrevation: "CAT", CountryCode:"RW", CountryName : "Rwanda", TimeZone:"Africa/Kigali", GMTOffset:"+0200" },
    { TimeZoneName: "Réunion Time ", TimeZoneAbbrevation: "RET", CountryCode:"RE", CountryName : "Réunion", TimeZone:"Indian/Reunion", GMTOffset:"+0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"BL", CountryName : "Saint Barthélemy", TimeZone:"America/St_Barthelemy", GMTOffset:"-0400" },
    { TimeZoneName: "Greenwich Mean Time ", TimeZoneAbbrevation: "GMT", CountryCode:"SH", CountryName : "Saint Helena, Ascension and Tristan da Cunha", TimeZone:"Atlantic/St_Helena", GMTOffset:"+0000" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"KN", CountryName : "Saint Kitts and Nevis", TimeZone:"America/St_Kitts", GMTOffset:"-0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"LC", CountryName : "Saint Lucia", TimeZone:"America/St_Lucia", GMTOffset:"-0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"MF", CountryName : "Saint Martin (French part)", TimeZone:"America/Marigot", GMTOffset:"-0400" },
    { TimeZoneName: "Pierre & Miquelon Standard Time", TimeZoneAbbrevation: "PMST", CountryCode:"PM", CountryName : "Saint Pierre and Miquelon", TimeZone:"America/Miquelon", GMTOffset:"-0200" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"VC", CountryName : "Saint Vincent and the Grenadines", TimeZone:"America/St_Vincent", GMTOffset:"-0400" },
    { TimeZoneName: "Western Standard Time ", TimeZoneAbbrevation: "WST", CountryCode:"WS", CountryName : "Samoa", TimeZone:"Pacific/Apia", GMTOffset:"+1400" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"SM", CountryName : "San Marino", TimeZone:"Europe/San_Marino", GMTOffset:"+0200" },
    { TimeZoneName: "Greenwich Mean Time ", TimeZoneAbbrevation: "GMT", CountryCode:"ST", CountryName : "Sao Tome and Principe", TimeZone:"Africa/Sao_Tome", GMTOffset:"+0000" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"SA", CountryName : "Saudi Arabia", TimeZone:"Asia/Riyadh", GMTOffset:"+0300" },
    { TimeZoneName: "Greenwich Mean Time ", TimeZoneAbbrevation: "GMT", CountryCode:"SN", CountryName : "Senegal", TimeZone:"Africa/Dakar", GMTOffset:"+0000" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"RS", CountryName : "Serbia", TimeZone:"Europe/Belgrade", GMTOffset:"+0200" },
    { TimeZoneName: "Seychelles Time", TimeZoneAbbrevation: "SCT", CountryCode:"SC", CountryName : "Seychelles", TimeZone:"Indian/Mahe", GMTOffset:"+0400" },
    { TimeZoneName: " Greenwich Mean Time ", TimeZoneAbbrevation: "GMT", CountryCode:"SL", CountryName : "Sierra Leone", TimeZone:"Africa/Freetown", GMTOffset:"+0000" },
    { TimeZoneName: "Singapore Standard Time", TimeZoneAbbrevation: "SST", CountryCode:"SG", CountryName : "Singapore", TimeZone:"Asia/Singapore", GMTOffset:"+0800" },
    { TimeZoneName: "Atlantic Standard Time ", TimeZoneAbbrevation: "AST", CountryCode:"SX", CountryName : "Sint Maarten (Dutch part)", TimeZone:"America/Lower_Princes", GMTOffset:"-0400" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"SK", CountryName : "Slovakia", TimeZone:"Europe/Bratislava", GMTOffset:"+0200" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"SI", CountryName : "Slovenia", TimeZone:"Europe/Ljubljana", GMTOffset:"+0200" },
    { TimeZoneName: "Solomon Islands Time", TimeZoneAbbrevation: "SBT", CountryCode:"SB", CountryName : "Solomon Islands", TimeZone:"Pacific/Guadalcanal", GMTOffset:"+1100" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"SO", CountryName : "Somalia", TimeZone:"Africa/Mogadishu", GMTOffset:"+0300" },
    { TimeZoneName: "South African Standard Time", TimeZoneAbbrevation: "SAST", CountryCode:"ZA", CountryName : "South Africa", TimeZone:"Africa/Johannesburg", GMTOffset:"+0200" },
    { TimeZoneName: "Gulf Standard Time ", TimeZoneAbbrevation: "GST", CountryCode:"GS", CountryName : "South Georgia and the South Sandwich Islands", TimeZone:"Atlantic/South_Georgia", GMTOffset:"-0200" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"SS", CountryName : "South Sudan", TimeZone:"Africa/Juba", GMTOffset:"+0300" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"ES", CountryName : "Spain", TimeZone:"Africa/Ceuta", GMTOffset:"+0200" },
    { TimeZoneName: "Western European Summer Time", TimeZoneAbbrevation: "WEST", CountryCode:"ES", CountryName : "Spain", TimeZone:"Atlantic/Canary", GMTOffset:"+0100" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"ES", CountryName : "Spain", TimeZone:"Europe/Madrid", GMTOffset:"+0200" },
    { TimeZoneName: "Indian Standard Time", TimeZoneAbbrevation: "IST", CountryCode:"LK", CountryName : "Sri Lanka", TimeZone:"Asia/Colombo", GMTOffset:"+0530" },
    { TimeZoneName: "Central Africa Time", TimeZoneAbbrevation: "CAT", CountryCode:"SD", CountryName : "Sudan", TimeZone:"Africa/Khartoum", GMTOffset:"+0200" },
    { TimeZoneName: "Suriname Time", TimeZoneAbbrevation: "SRT", CountryCode:"SR", CountryName : "Suriname", TimeZone:"America/Paramaribo", GMTOffset:"-0300" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"SJ", CountryName : "Svalbard and Jan Mayen", TimeZone:"Arctic/Longyearbyen", GMTOffset:"+0200" },
    { TimeZoneName: "South African Standard Time  ", TimeZoneAbbrevation: "SAST", CountryCode:"SZ", CountryName : "Swaziland", TimeZone:"Africa/Mbabane", GMTOffset:"+0200" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"SE", CountryName : "Sweden", TimeZone:"Europe/Stockholm", GMTOffset:"+0200" },
    { TimeZoneName: "Central European Summer Time", TimeZoneAbbrevation: "CEST", CountryCode:"CH", CountryName : "Switzerland", TimeZone:"Europe/Zurich", GMTOffset:"+0200" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"SY", CountryName : "Syrian Arab Republic", TimeZone:"Asia/Damascus", GMTOffset:"+0300" },
    { TimeZoneName: " Central Standard Time", TimeZoneAbbrevation: "CST", CountryCode:"TW", CountryName : "Taiwan, Province of China", TimeZone:"Asia/Taipei", GMTOffset:"+0800" },
    { TimeZoneName: "Tajikistan Time", TimeZoneAbbrevation: "TJT", CountryCode:"TJ", CountryName : "Tajikistan", TimeZone:"Asia/Dushanbe", GMTOffset:"+0500" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"TZ", CountryName : "Tanzania, United Republic of", TimeZone:"Africa/Dar_es_Salaam", GMTOffset:"+0300" },
    { TimeZoneName: "Indochina Time", TimeZoneAbbrevation: "ICT", CountryCode:"TH", CountryName : "Thailand", TimeZone:"Asia/Bangkok", GMTOffset:"+0700" },
    { TimeZoneName: "East Timor Time", TimeZoneAbbrevation: "TLT", CountryCode:"TL", CountryName : "Timor-Leste", TimeZone:"Asia/Dili", GMTOffset:"+0900" },
    { TimeZoneName: "Greenwich Mean Time", TimeZoneAbbrevation: "GMT", CountryCode:"TG", CountryName : "Togo", TimeZone:"Africa/Lome", GMTOffset:"+0000" },
    { TimeZoneName: "Tokelau Time", TimeZoneAbbrevation: "TKT", CountryCode:"TK", CountryName : "Tokelau", TimeZone:"Pacific/Fakaofo", GMTOffset:"+1300" },
    { TimeZoneName: "Tonga Time", TimeZoneAbbrevation: "TOT", CountryCode:"TO", CountryName : "Tonga", TimeZone:"Pacific/Tongatapu", GMTOffset:"+1300" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"TT", CountryName : "Trinidad and Tobago", TimeZone:"America/Port_of_Spain", GMTOffset:"-0400" },
    { TimeZoneName: "Central European Time", TimeZoneAbbrevation: "CET", CountryCode:"TN", CountryName : "Tunisia", TimeZone:"Africa/Tunis", GMTOffset:"+0100" },
    { TimeZoneName: "Turkey Time", TimeZoneAbbrevation: "TRT", CountryCode:"TR", CountryName : "Turkey", TimeZone:"Europe/Istanbul", GMTOffset:"+0300" },
    { TimeZoneName: "Turkmenistan Time", TimeZoneAbbrevation: "TMT", CountryCode:"TM", CountryName : "Turkmenistan", TimeZone:"Asia/Ashgabat", GMTOffset:"+0500" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"TC", CountryName : "Turks and Caicos Islands", TimeZone:"America/Grand_Turk", GMTOffset:"-0400" },
    { TimeZoneName: "Tuvalu Time ", TimeZoneAbbrevation: "TVT", CountryCode:"TV", CountryName : "Tuvalu", TimeZone:"Pacific/Funafuti", GMTOffset:"+1200" },
    { TimeZoneName: "East Africa Time", TimeZoneAbbrevation: "EAT", CountryCode:"UG", CountryName : "Uganda", TimeZone:"Africa/Kampala", GMTOffset:"+0300" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"UA", CountryName : "Ukraine", TimeZone:"Europe/Kiev", GMTOffset:"+0300" },
    { TimeZoneName: "Moscow Standard Time ", TimeZoneAbbrevation: "MSK", CountryCode:"UA", CountryName : "Ukraine", TimeZone:"Europe/Simferopol", GMTOffset:"+0300" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"UA", CountryName : "Ukraine", TimeZone:"Europe/Uzhgorod", GMTOffset:"+0300" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"UA", CountryName : "Ukraine", TimeZone:"Europe/Zaporozhye", GMTOffset:"+0300" },
    { TimeZoneName: "Gulf Standard Time", TimeZoneAbbrevation: "GST", CountryCode:"AE", CountryName : "United Arab Emirates", TimeZone:"Asia/Dubai", GMTOffset:"+0400" },
    { TimeZoneName: "British Summer Time", TimeZoneAbbrevation: "BST", CountryCode:"GB", CountryName : "United Kingdom", TimeZone:"Europe/London", GMTOffset:"+0100" },
    { TimeZoneName: "Hawaii-Aleutian Daylight Time ", TimeZoneAbbrevation: "HDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Adak", GMTOffset:"-0900" },
    { TimeZoneName: "Alaska Daylight Time", TimeZoneAbbrevation: "AKDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Anchorage", GMTOffset:"-0800" },
    { TimeZoneName: "Mountain Daylight Time", TimeZoneAbbrevation: "MDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Boise", GMTOffset:"-0600" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Chicago", GMTOffset:"-0500" },
    { TimeZoneName: "Mountain Daylight Time", TimeZoneAbbrevation: "MDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Denver", GMTOffset:"-0600" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Detroit", GMTOffset:"-0400" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Indiana/Indianapolis", GMTOffset:"-0400" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Indiana/Knox", GMTOffset:"-0500" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Indiana/Marengo", GMTOffset:"-0400" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Indiana/Petersburg", GMTOffset:"-0400" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Indiana/Tell_City", GMTOffset:"-0500" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Indiana/Vevay", GMTOffset:"-0400" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Indiana/Vincennes", GMTOffset:"-0400" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Indiana/Winamac", GMTOffset:"-0400" },
    { TimeZoneName: "Alaska Daylight Time", TimeZoneAbbrevation: "AKDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Juneau", GMTOffset:"-0800" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Kentucky/Louisville", GMTOffset:"-0400" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Kentucky/Monticello", GMTOffset:"-0400" },
    { TimeZoneName: "Pacfic Daylight Time", TimeZoneAbbrevation: "PDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Los_Angeles", GMTOffset:"-0700" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Menominee", GMTOffset:"-0500" },
    { TimeZoneName: "Alaska Daylight Time", TimeZoneAbbrevation: "AKDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Metlakatla", GMTOffset:"-0800" },
    { TimeZoneName: "Eastern Daylight Time", TimeZoneAbbrevation: "EDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/New_York", GMTOffset:"-0400" },
    { TimeZoneName: "Alaska Daylight Time ", TimeZoneAbbrevation: "AKDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Nome", GMTOffset:"-0800" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/North_Dakota/Beulah", GMTOffset:"-0500" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/North_Dakota/Center", GMTOffset:"-0500" },
    { TimeZoneName: "Central Time Zone", TimeZoneAbbrevation: "CDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/North_Dakota/New_Salem", GMTOffset:"-0500" },
    { TimeZoneName: "Mountain Standard Time", TimeZoneAbbrevation: "MST", CountryCode:"US", CountryName : "United States", TimeZone:"America/Phoenix", GMTOffset:"-0700" },
    { TimeZoneName: "Alaska Daylight Time ", TimeZoneAbbrevation: "AKDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Sitka", GMTOffset:"-0800" },
    { TimeZoneName: "Alaska Daylight Time ", TimeZoneAbbrevation: "AKDT", CountryCode:"US", CountryName : "United States", TimeZone:"America/Yakutat", GMTOffset:"-0800" },
    { TimeZoneName: "Hawaii Standard Time ", TimeZoneAbbrevation: "HST", CountryCode:"US", CountryName : "United States", TimeZone:"Pacific/Honolulu", GMTOffset:"-1000" },
    { TimeZoneName: "Samoa Standard Time  ", TimeZoneAbbrevation: "SST", CountryCode:"UM", CountryName : "United States Minor Outlying Islands", TimeZone:"Pacific/Midway", GMTOffset:"-1100" },
    { TimeZoneName: "Wake Time", TimeZoneAbbrevation: "WAKT", CountryCode:"UM", CountryName : "United States Minor Outlying Islands", TimeZone:"Pacific/Wake", GMTOffset:"+1200" },
    { TimeZoneName: "Uruguay Standard Time ", TimeZoneAbbrevation: "UYT", CountryCode:"UY", CountryName : "Uruguay", TimeZone:"America/Montevideo", GMTOffset:"-0300" },
    { TimeZoneName: "Uzbekistan Time ", TimeZoneAbbrevation: "UZT", CountryCode:"UZ", CountryName : "Uzbekistan", TimeZone:"Asia/Samarkand", GMTOffset:"+0500" },
    { TimeZoneName: "Uzbekistan Time", TimeZoneAbbrevation: "UZT", CountryCode:"UZ", CountryName : "Uzbekistan", TimeZone:"Asia/Tashkent", GMTOffset:"+0500" },
    { TimeZoneName: "Vanuatu Standard Time", TimeZoneAbbrevation: "VUT", CountryCode:"VU", CountryName : "Vanuatu", TimeZone:"Pacific/Efate", GMTOffset:"+1100" },
    { TimeZoneName: "Venezuelan Standard Time", TimeZoneAbbrevation: "VET", CountryCode:"VE", CountryName : "Venezuela, Bolivarian Republic of", TimeZone:"America/Caracas", GMTOffset:"-0400" },
    { TimeZoneName: "Israeli Daylight Time ", TimeZoneAbbrevation: "IDT", CountryCode:"VN", CountryName : "Viet Nam", TimeZone:"Asia/Ho_Chi_Minh", GMTOffset:"+0700" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"VG", CountryName : "Virgin Islands, British", TimeZone:"America/Tortola", GMTOffset:"-0400" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"VI", CountryName : "Virgin Islands, U.S.", TimeZone:"America/St_Thomas", GMTOffset:"-0400" },
    { TimeZoneName: "Wallis & Futuna Time", TimeZoneAbbrevation: "WFT", CountryCode:"WF", CountryName : "Wallis and Futuna", TimeZone:"Pacific/Wallis", GMTOffset:"+1200" },
    { TimeZoneName: "Western European Summer Time", TimeZoneAbbrevation: "WEST", CountryCode:"EH", CountryName : "Western Sahara", TimeZone:"Africa/El_Aaiun", GMTOffset:"+0100" },
    { TimeZoneName: "Atlantic Standard Time", TimeZoneAbbrevation: "AST", CountryCode:"YE", CountryName : "Yemen", TimeZone:"Asia/Aden", GMTOffset:"+0300" },
    { TimeZoneName: "Central Africa Time", TimeZoneAbbrevation: "CAT", CountryCode:"ZM", CountryName : "Zambia", TimeZone:"Africa/Lusaka", GMTOffset:"+0200" },
    { TimeZoneName: "Central Africa Time", TimeZoneAbbrevation: "CAT", CountryCode:"ZW", CountryName : "Zimbabwe", TimeZone:"Africa/Harare", GMTOffset:"+0200" },
    { TimeZoneName: "Eastern European Summer Time", TimeZoneAbbrevation: "EEST", CountryCode:"AX", CountryName : "Åland Islands", TimeZone:"Europe/Mariehamn", GMTOffset:"+0300" }
]