export const ApiUrls = {
  GetAllUsers: "User/UsersApi/GetAllUsers",
  GetUsersDropDown: "User/UsersApi/GetUsersDropDown",
  GetDesignations: "HrManagement/HrManagementApi/GetDesignations",
  GetApiData: "Widgets/WidgetsApi/GetApiData",
  GetWidgets: "Widgets/WidgetsApi/GetWidgets",
  UpsertCustomApplicationKeys: "CustomAppplication/CustomApplicationApi/UpsertCustomApplicationKeys",
  GetLoggedInUser: "api/LoginApi/GetLoggedInUser",
  UpsertWidget: "Widgets/WidgetsApi/UpsertWidget",
  UpsertImportWidget: "Widgets/WidgetsApi/UpsertImportWidget",
  UpsertCustomWidget: "Widgets/WidgetsApi/UpsertCustomWidget",
  UpsertCustomApplication: "CustomAppplication/CustomApplicationApi/UpsertCustomApplication",
  GetHumanTaskList: "api/CustomApplicationApi/GetHumanTaskList",
  GenericFormSubmittedData: "GenericForm/GenericFormApi/GenericFormSubmittedData",
  ShareGenericFormSubmitted :"GenericForm/GenericFormApi/ShareGenericFormSubmitted",
  CompleteUserTask: "api/CustomApplicationApi/CompleteUserTask",
  UpsertCustomFormSubmission: "MasterData/GenericFormMasterDataApi/UpsertCustomFormSubmission",
  GetAllButtonTypes: "ButtonType/ButtonTypeApi/GetAllButtonTypes",
  GetGenericFormTypes: "MasterData/GenericFormMasterDataApi/GetGenericFormTypes",
  GetCustomFormSubmissions: "MasterData/GenericFormMasterDataApi/GetCustomFormSubmissions",
  GetMyTeamMembersList: "HrManagement/HrManagementApi/GetMyTeamMembersList",
  GetAllBranches: "Branch/BranchApi/GetAllBranches",
  UpsertGenericFormSubmitted: "GenericForm/GenericFormApi/UpsertGenericFormSubmitted",
  UpsertGenericFormSubmittedUnAuth: "GenericForm/GenericFormApi/UpsertGenericFormSubmittedUnAuth",
  UpsertPublicGenericFormSubmitted: "GenericForm/GenericFormApi/UpsertPublicGenericFormSubmitted",
  GetProjects: "TestRail/TestSuiteApi/GetProjects",
  GetCustomApplication: "CustomAppplication/CustomApplicationApi/GetCustomApplication",
  GetCustomApplicationKeysSelected: "CustomAppplication/CustomApplicationApi/GetCustomApplicationKeysSelected",
  GetFormHistory: "CustomAppplication/CustomApplicationApi/GetFormHistory",
  GetPublicCustomApplicationById: "CustomAppplication/CustomApplicationApi/GetPublicCustomApplicationById",
  GetWidgetFilterQueryBuilder: "Widgets/WidgetsApi/GetWidgetFilterQueryBuilder",
  ImportFormDataFromExcel: "CustomAppplication/CustomApplicationApi/ImportFormDataFromExcel",
  GetAllEntityRoleFeaturesByUserId: "EntityType/EntityRoleFeatureApi/GetAllEntityRoleFeaturesByUserId",
  GetWidgetDynamicQueryResult: "Widgets/WidgetsApi/GetWidgetDynamicQueryResult",
  UploadFile: "File/FileApi/UploadFile",
  GetCustomApplicationWorkflow: "CustomAppplication/CustomApplicationApi/GetCustomApplicationWorkflow",
  GetCustomApplicationWorkflowTypes: "CustomAppplication/CustomApplicationApi/GetCustomApplicationWorkflowTypes",
  GetDepartments: "HrManagement/HrManagementApi/GetDepartments",
  SearchFile: "File/FileApi/SearchFile",
  GetCustomApplicationKeys: "CustomAppplication/CustomApplicationApi/GetCustomApplicationKeys",
  UploadFileAsync: "api/CustomApplicationApi/UploadFileAsync",
  GetGenericFormKey: "GenericForm/GenericFormApi/GetGenericFormKey",
  UpsertCustomApplicationWorkflow: "CustomAppplication/CustomApplicationApi/UpsertCustomApplicationWorkflow",
  CustomWidgetNameValidator: "Widgets/WidgetsApi/CustomWidgetNameValidator",
  GetAllRoles: "Roles/RolesApi/GetAllRoles",
  GetGenericFormSubmitted: "GenericForm/GenericFormApi/GetGenericFormSubmitted",
  GetGenericFormSubmittedUnAuth: "GenericForm/GenericFormApi/GetGenericFormSubmittedUnAuth",
  GetGenericForms: "GenericForm/GenericFormApi/GetGenericForms",
  GetCustomWidgets: "Widgets/WidgetsApi/GetCustomWidgets",
  UpdatePersistance: "Persistance/PersistanceApi/UpdatePersistance",
  GetPersistance: "Persistance/PersistanceApi/GetPersistance",
  ImportVerifiedApplication: "CustomAppplication/CustomApplicationApi/ImportVerifiedApplication",
  UpsertDashboardVisuaizationType: "Widgets/WidgetsApi/UpsertDashboardVisuaizationType",
  UpsertCustomTags: "CustomTags/CustomTagsApi/UpsertCustomTags",
  UpsertTags: "CustomTags/CustomTagsApi/UpsertTags",
  GetCustomTags: "CustomTags/CustomTagsApi/GetCustomTags",
  GetCustomApplicationTag: "GenericForm/GenericFormApi/GetCustomApplicationTag",
  SetCustomAppDashboardPersistanceForUser: "Widgets/WidgetsApi/SetCustomAppDashboardPersistanceForUser",
  GetCustomAppDashboardPersistanceForUser: "Widgets/WidgetsApi/GetCustomAppDashboardPersistanceForUser",
  GetObservationType: "CustomAppplication/CustomApplicationApi/GetObservationType",
  UpsertObservationType: "CustomAppplication/CustomApplicationApi/UpsertObservationType",
  UpdateDashboardName: "Widgets/WidgetsApi/UpdateDashboardName",
  GetResidentObservations: "CustomFields/CustomFieldApi/GetResidentObservations",
  GetWebHooks: "HrManagement/HrManagementApi/GetWebHooks",
  GetEntityDropDown: "ProductivityDashboard/ProductivityDashboardApi/GetEntityDropDown",
  UpsertDashboardFilter: "Widgets/WidgetsApi/UpsertDashboardFilter",
  GetDashboardFilters: "Widgets/WidgetsApi/GetDashboardFilters",
  EmployeeUpload: "HrManagement/HrManagementApi/EmployeeUpload",
  GetAddOrEditCustomAppIsRequired: "MasterData/MasterDataManagementApi/GetAddOrEditCustomAppIsRequired",
  GetCompanySettingsDetails: "MasterData/MasterDataManagementApi/GetCompanySettingsDetails",
  UpsertCustomFieldForm: `CustomFields/CustomFieldApi/UpsertCustomFieldForm`,
  SearchCustomFieldForms: `CustomFields/CustomFieldApi/SearchCustomFieldForms`,
  GetCustomFormFieldById: `CustomFields/CustomFieldApi/GetCustomFormFieldById`,
  UpdateCustomFieldData: `CustomFields/CustomFieldApi/UpdateCustomFieldData`,
  GetWorkFlowsForTriggers: `AutomatedWorkflowManagement/AutomatedWorkflowManagementApi/GetWorkFlowsForTriggers`,
  GetTriggers: `AutomatedWorkflowManagement/AutomatedWorkflowManagementApi/GetTriggers`,
  GetWorkFlowTriggers: `AutomatedWorkflowManagement/AutomatedWorkflowManagementApi/GetWorkFlowTriggers`,
  UpsertWorkFlowTrigger: `AutomatedWorkflowManagement/AutomatedWorkflowManagementApi/UpsertWorkflowTrigger`,
  UpsertWorkFlow: `WorkFlow/WorkFlowApi/UpsertWorkFlow`,
  GetGenericStatus: `AutomatedWorkflowManagement/AutomatedWorkflowManagementApi/GetGenericStatus`,
  SearchTestSuites: `TestRail/TestSuiteApi/SearchTestSuites`,
  GetBusinessUnitDropDown:`MasterData/CompanyStructure/GetBusinessUnitDropDown`,
  GetSources : `Recruitment/RecruitmentMasterDataApi/GetSources`,
  GetJobOpeningStatus :`Recruitment/RecruitmentMasterDataApi/GetJobOpeningStatus`,
  GetHiringStatus : `Recruitment/RecruitmentMasterDataApi/GetHiringStatus`,
  GetEmploymentStatus: `MasterDataManagement/MasterDataManagementApi/GetEmploymentStatus`,
  GetCandidates : `Recruitment/RecruitmentApi/GetCandidates`,
  UpsertLevel : `CustomAppplication/CustomApplicationApi/UpsertLevel`,
  GetLevel : `CustomAppplication/CustomApplicationApi/GetLevels`,
  GetCollectionsList : `Widgets/WidgetsApi/GetMongoCollections`,
  GetCo2EmissionsList : `Widgets/WidgetsApi/GetCO2EmmisionReport`,
  GetRolesDropdown : `Roles/RolesApi/GetAllRolesDropDown`,
  ShareNewGenericForm: `GenericForm/GenericFormApi/SendGeneratedReporttoMail`,
  GetDocumentsForGenericFormSubmitetd: `GenericForm/GenericFormApi/GetAllFilesOfFormSubmitted`,
  ShareNewEmptyForm: `GenericForm/GenericFormApi/MailWorkFlowTrigger`,
  GetUsersList: `User/UsersApi/GetUsersList`,
  DailyUploadExcel:`Excel/ExcelApi/ExcelToCustomApplicationRecords`,
  GetExcelToCustomApplicationsDetails:`Excel/ExcelApi/GetExcelToCustomApplicationsDetails`,
  GetGenericFormHistory : `GenricForm/GenericFormApi/GetGenericFormHistory`,
  TriggerWorkflow: `GenericForm/GenericFormApi/TriggerWorkFlow`
}
