import { Guid } from "guid-typescript";
import { KPIModel } from "./kpi-model";

export const SampleKPIModel: KPIModel[] = [
    {
        programId: Guid.parse('AFB6FB47-FDE5-4D2E-959A-3FF44428BB68'),
        programName: 'SMILE PROGRAM',
        kpiId: Guid.create(),
        kpiName: 'Smallholder Certification',
        targetArea: 'Riau (92,261 ha)',
        sDGIndicator: 'Decent work & economic Growth,Sustainable cities & Communities',
        eSGIndicator: 'Certification Standards,Smallholders & Suppliers',
        totalCount: 3,
        order: 3,
        formName : 'form 1',
        isArchived: false,
        formData: {
            kpi01: 'Smallholder Certification',
            targetAreaInThePhase: '',
            applicableSdGs1: ['Decent work & economic Growth', 'Sustainable cities & Communities'],
            applicableEsgIndicators: ['Certification Standards', 'Smallholders & Suppliers'],
            kpiNumber02: '',
            targetAreaInThePhase1: '',
            applicableSdGsForKpi02: '',
            applicableEsgIndicators1: '',
            kpiNumber03: '',
            targetAreaInThePhase2: '',
            applicableSdGsForKpi03: '',
            applicableEsgIndicators2: '',
            phase: '',
            phase1: '',
            phase2: '',
            phaseNumber3: '',
            phaseNumber4: '',
            phaseNumber5: '',
            targetForKpi02: '',
            targetKpi01: 'Riau (92,261 ha)',
            targetKpi02: '',
            targetShFs: "",
            targetShFs1: "",
            targetShFs2: "",
            taskForAchievingKpi03: "",
            taskForAchievingTargetKpi01: "",
            taskForAchievingTargetKpi02: ""

        }
    },
    {
        programId: Guid.parse('AFB6FB47-FDE5-4D2E-959A-3FF44428BB68'),
        programName: 'SMILE PROGRAM',
        kpiId: Guid.create(),
        kpiName: 'Improvement in FFB productivity',
        targetArea: 'North Sumatera (4,809 ha)',
        sDGIndicator: 'No Poverty,Zero Hunger,Responsible consumption & Production',
        eSGIndicator: 'Deep forestation & Biodiversity,Peat, Fire & Greenhouse  Gas emission,Sustainability & Policy Leadership',
        totalCount: 3,
        order: 2,
        formName : 'form 2',
        isArchived: false,
        formData: {
            kpi01: '',
            targetAreaInThePhase: '',
            applicableSdGs1: '',
            applicableEsgIndicators: '',
            kpiNumber02: 'Improvement in FFB productivity',
            targetAreaInThePhase1: '',
            applicableSdGsForKpi02: ['No Poverty', 'Zero Hunger', 'Responsible consumption & Production'],
            applicableEsgIndicators1: ['Deep forestation & Biodiversity', 'Peat, Fire & Greenhouse  Gas emission', 'Sustainability & Policy Leadership'],
            kpiNumber03: '',
            targetAreaInThePhase2: '',
            applicableSdGsForKpi03: '',
            applicableEsgIndicators2: '',
            phase: '',
            phase1: '',
            phase2: '',
            phaseNumber3: '',
            phaseNumber4: '',
            phaseNumber5: '',
            targetForKpi02: '',
            targetKpi01: '',
            targetKpi02: 'North Sumatera (4,809 ha)',
            targetShFs: "",
            targetShFs1: "",
            targetShFs2: "",
            taskForAchievingKpi03: "",
            taskForAchievingTargetKpi01: "",
            taskForAchievingTargetKpi02: ""

        }
    },
    {
        programId: Guid.parse('AFB6FB47-FDE5-4D2E-959A-3FF44428BB68'),
        programName: 'SMILE PROGRAM',
        kpiId: Guid.create(),
        kpiName: 'Increment in Smallholder monthly income',
        targetArea: 'Jambi  (500 ha)',
        sDGIndicator: 'No Poverty,Reduce Inequalities,Responsible consumption & Production',
        eSGIndicator: 'Community, Land & labor Rights,Smallholder & Suppliers',
        totalCount: 3,
        order: 1,
        isArchived: false,
        formName : 'form 3',
        formData: {
            kpi01: '',
            targetAreaInThePhase: '',
            applicableSdGs1: '',
            applicableEsgIndicators: '',
            kpiNumber02: '',
            targetAreaInThePhase1: '',
            applicableSdGsForKpi02: '',
            applicableEsgIndicators1: '',
            kpiNumber03: 'Increment in Smallholder monthly income',
            targetAreaInThePhase2: '',
            applicableSdGsForKpi03: 'No Poverty,Reduce Inequalities,Responsible consumption & Production',
            applicableEsgIndicators2: 'Community, Land & labor Rights,Smallholder & Suppliers',
            phase: '',
            phase1: '',
            phase2: '',
            phaseNumber3: '',
            phaseNumber4: '',
            phaseNumber5: '',
            targetForKpi02: 'Jambi  (500 ha)',
            targetKpi01: '',
            targetKpi02: '',
            targetShFs: "",
            targetShFs1: "",
            targetShFs2: "",
            taskForAchievingKpi03: "",
            taskForAchievingTargetKpi01: "",
            taskForAchievingTargetKpi02: ""

        }
    }
]