export const ApiUrls = {
  GetAllUsers: `User/UsersApi/GetAllUsers`,
  GetCompanyById: `CompanyStructure/CompanyStructureApi/GetCompanyById`,
  GetTimeFormatById: `CompanyStructure/CompanyStructureApi/GetTimeFormatById`,
  GetDateFormatById: `CompanyStructure/CompanyStructureApi/GetDateFormatById`,
  GetAllUsersByRoles: `User/UsersApi/GetUsersByRoles`,
  GetLoggedInUser: `api/LoginApi/GetLoggedInUser`,
  GetCompanysettings: `MasterData/MasterDataManagementApi/GetCompanysettings`,
  UpsertEmployeePersonalDetails: `HrManagement/HrManagementApi/UpsertEmployeePersonalDetails`,
  UpsertEmployeeContactDetails: `HrManagement/HrManagementApi/UpsertEmployeeContactDetails`,
  GetAllBranches: `Branch/BranchApi/GetAllBranches`,
  GetCurrencies: `HrManagement/HrManagementApi/GetCurrencies`,
  GetEmployeeById: `Employee/EmployeeApi/GetEmployeeById`,
  GetAllEmployees: `Employee/EmployeeApi/GetAllEmployees`,
  GetAllEmployeesDetails: `Employee/EmployeeApi/GetAllEmployeesDetails`,
  GetUserById: `User/UsersApi/GetUserById`,
  GetUsersDropDown: 'User/UsersApi/GetUsersDropDown',
  GetSoftLabelConfigurations: `MasterData/MasterDataManagementApi/GetSoftLabelConfigurations`,
  UpsertSoftLabelConfigurations: `MasterData/MasterDataManagementApi/UpsertSoftLabelConfigurations`,
  GetSoftLabelById: `MasterData/MasterDataManagementApi/GetSoftLabelById`,
  GetEntityDropDown: 'ProductivityDashboard/ProductivityDashboardApi/GetEntityDropDown',
  GetCompanySettingsDetails: `MasterData/MasterDataManagementApi/GetCompanySettingsDetails`,
  UpsertUser: `User/UsersApi/UpsertUser`,
  GetUsers: `User/UsersApi/GetAllUsers`,
  GetJobOpenings : `Recruitment/RecruitmentApi/GetJobOpenings`,
  GetCandidateJobOpenings : `Recruitment/RecruitmentApi/GetCandidateJobOpenings`,
  UpsertJobOpening : `Recruitment/RecruitmentApi/UpsertJobOpening`,
  UpsertCandidateInterviewSchedule : `Recruitment/RecruitmentApi/UpsertCandidateInterviewSchedule`,
  GetCandidateInterviewSchedule : `Recruitment/RecruitmentApi/GetCandidateInterviewSchedule`,
  UpsertCandidateInterviewFeedBack : `Recruitment/RecruitmentApi/UpsertCandidateInterviewFeedBack`,
  GetCandidateInterviewFeedBack : `Recruitment/RecruitmentApi/GetCandidateInterviewFeedBack`,
  GetCandidateInterviewFeedBackComments : `Recruitment/RecruitmentApi/GetCandidateInterviewFeedBackComments`,
  UpsertCandidateInterviewFeedBackComments : `Recruitment/RecruitmentApi/UpsertCandidateInterviewFeedBackComments`,
  GetCandidatesBySkill : `Recruitment/RecruitmentApi/GetCandidatesBySkill`,
  GetCandidateDocuments : `Recruitment/RecruitmentApi/GetCandidateDocuments`,
  UpsertCandidateDocument : `Recruitment/RecruitmentApi/UpsertCandidateDocument`,
  GetCandidateEducation : `Recruitment/RecruitmentApi/GetCandidateEducation`,
  UpsertCandidateEducation : `Recruitment/RecruitmentApi/UpsertCandidateEducation`,
  GetCandidateExperience  : `Recruitment/RecruitmentApi/GetCandidateExperience`,
  UpsertCandidateExperience : `Recruitment/RecruitmentApi/UpsertCandidateExperience`,
  GetCandidateHistory : `Recruitment/RecruitmentApi/GetCandidateHistory`,
  GetCandidateSkills : `Recruitment/RecruitmentApi/GetCandidateSkills`,
  UpsertCandidateSkill : `Recruitment/RecruitmentApi/UpsertCandidateSkill`,
  GetCandidates : `Recruitment/RecruitmentApi/GetCandidates`,
  GetJobOpeningStatus: `Recruitment/RecruitmentMasterDataApi/GetJobOpeningStatus`,
  UpsertInterviewProcessConfiguration : `Recruitment/RecruitmentApi/UpsertInterviewProcessConfiguration`,
  GetInterviewprocessConfiguration : `Recruitment/RecruitmentApi/GetInterviewProcessConfiguration`,
  GetInterviewTypes : `Recruitment/RecruitmentMasterDataApi/GetInterviewTypes`,
  GetInterviewprocess : `Recruitment/RecruitmentApi/GetInterviewProcess`,
  GetSources: `Recruitment/RecruitmentMasterDataApi/GetSources`,
  UpsertInterviewProcess : `Recruitment/RecruitmentApi/UpsertInterviewProcess`,
  ApproveSchedule : `Recruitment/RecruitmentApi/ApproveCandidateInterviewSchedule`,
  GetInterviewRatings : `Recruitment/RecruitmentMasterDataApi/GetInterviewRatings`,
  GetUserCandidateInterviewSchedules : `Recruitment/RecruitmentApi/GetUserCandidateInterviewSchedules`,
  UpsertSource: `Recruitment/RecruitmentMasterDataApi/UpsertSource`,
  GetDocumentTypes: `Recruitment/RecruitmentMasterDataApi/GetDocumentTypes`,
  UpsertDocumentType: `Recruitment/RecruitmentMasterDataApi/UpsertDocumentType`,
  GetHiringStatus: `Recruitment/RecruitmentMasterDataApi/GetHiringStatus`,
  GetScheduleStatus: `Recruitment/RecruitmentMasterDataApi/GetScheduleStatus`,
  UpsertHiringStatus: `Recruitment/RecruitmentMasterDataApi/UpsertHiringStatus`,
  GetInterviewType: `Recruitment/RecruitmentMasterDataApi/GetInterviewTypes`,
  UpsertInterviewType: `Recruitment/RecruitmentMasterDataApi/UpsertInterviewType`,
  UpsertInterviewRating: `Recruitment/RecruitmentMasterDataApi/UpsertInterviewRating`,
  UpsertCandidate: `Recruitment/RecruitmentApi/UpsertCandidate`,
  GetSkills : `MasterData/MasterDataManagementApi/GetSkills`,
  GetSkillsByCandidates : `Recruitment/RecruitmentApi/GetSkillsByCandidates`,
  UpsertSkills: `MasterData/MasterDataManagementApi/UpsertSkills`,
  GetLocations : `Branch/BranchApi/GetAllBranchesDropdown`,
  GetCountries: `CompanyStructureManagement/CompanyStructureManagementApi/GetCountries`,
  GetDesignations: `HrManagement/HrManagementApi/GetDesignations`,
  GetAllRolesDropDown : `Roles/RolesApi/GetAllRolesDropDown`,
  GetJobTypes: `Recruitment/RecruitmentMasterDataApi/GetJobTypes`,
  GetEmploymentStatus: `MasterDataManagement/MasterDataManagementApi/GetEmploymentStatus`,
  UpsertJobOpeningStatus: `Recruitment/RecruitmentMasterDataApi/UpsertJobOpeningStatus`,
  CancelInterviewSchedule : `Recruitment/RecruitmentApi/CancelInterviewSchedule`,
  GetStates: `MasterDataManagement/MasterDataManagementApi/GetStates`,
  HiredDocumentsList : `Recruitment/RecruitmentApi/HiredDocumentsList`,
  UpsertComments: `Comments/CommentsApi/UpsertComment`,
  SendOfferLetter : `Recruitment/RecruitmentMasterDataApi/SendOfferLetter`,
  downloadOfferLetter : `Recruitment/RecruitmentApi/DownloadOfferLetter`,
  GetStoreConfiguration: `DocumentManagement/StoreManagementApi/GetStoreConfiguration`,
  UpsertMultipleFiles: `File/FileApi/UpsertMultipleFiles`,
  SearchFile: `File/FileApi/SearchFile`,
  UploadFileChunks: `File/FileApi/UploadFileChunks`,
  DeleteFile: `File/FileApi/DeleteFile`,
  GetBrytumViewJobDetails: `Recruitment/RecruitmentApi/GetBrytumViewJobDetails`
};
