export const ChannelNames = {
    Channel_TaskAssignments: 'ProjectManagement.TaskAssignments.',
    Channel_RoleUpdates: 'System.RoleUpdates.',
    Channel_StatusReportSubmission : 'StatusReport.ReprotSubmissions.',
    Channel_StatusConfigAssign : 'StatusReport.ConfigurationAssignments.',
    Channel_MultiChartsScheduling : 'MultiCharts.Scheduling.',
    Channel_AssetAssignment: 'AssetManagement.AssetAssigned.',
    Channel_NewProject: 'ProjectManagement.NewProject.',
    Channel_ProjectMemberRole: 'ProjectManagement.ProjectMemberRole.',
    Channel_GoalApprovedFromReplan: 'ProjectManagement.GoalApprovedFromReplan.',
    Channel_UserStoryUpdateNotification : 'ProjectManagement.WorkItemUpdate.',
    Channel_AnnouncementNotification : 'HrManagement.Announcement.',
    Channel_UserStoryComment : 'ProjectManagement.UserStoryCommentNotification.',
    Channel_SprintStarted : 'ProjectManagement.SprintStarted.',
    Channel_SprintRequestedToReplan: 'ProjectManagement.SprintReplan.',
    Channel_PeroformanceNotification: 'HrManagement.Performance.',
    Channel_ReminderNotification: 'HrManagement.Reminder.',
    Channel_ProjectFeature: 'ProjectManagement.ProjectComponent.',
    Channel_UserStoryArchive: 'ProjectManagement.UserStoryArchive.',
    Channel_UserStoryPark: 'ProjectManagement.ParkUserStory.',
    Channel_GenericActivityNotification: 'GenericNotificationActivity.',
    Channel_LeaveApplied: 'LeaveManagement.LeaveNotification.',
    Channel_ApproveLeave: 'LeaveManagement.ApproveLeaveNotification.',
    Channel_RejectLeave: 'LeaveManagement.RejectLeaveNotification.',
    Channel_Resignation: 'Payroll.ResignationNotification.',
    Channel_ApproveResignation: 'Payroll.ResignationApprovalNotification.',
    Channel_RejectResignation: 'Payroll.ResignationRejectionNotification.',
    Channel_AutoTimesheetSubmission: 'TimeSheet.AutoTimeSheetSubmissionNotification.',
    Channel_ProbationAssignNotification: "Probation.Assign.",
    Channel_ReviewAssignToEmployeeNotification: "Probation.ReviewAssignToEmployeeNotification.",
    Channel_ReviewSubmittedByEmployeeNotification: "Probation.ReviewSubmittedByEmployeeNotification.",
    Channel_ReviewInvitationNotificationModel: "Probation.ReviewInvitationNotificationModel.",
    Channel_PerformanceReviewSubmittedByEmployeeNotification: "Performance.PerformanceReviewSubmittedByEmployeeNotification.",
    Channel_PerformanceReviewInvitationNotificationModel: "Performance.PerformanceReviewInvitationNotificationModel.",
    Channel_PerformanceReviewAssignToEmployeeNotification: "Performance.PerformanceReviewAssignToEmployeeNotification.",
    Channel_PurchaseExecutionAssignToEmployeeNotification: "Client.PurchaseExecutionAssignToEmployeeNotification.",
}
