export const ApiUrls = {
  GetAllUsers: `User/UsersApi/GetAllUsers`,
  GetStatusReportingConfigurationForms: `StatusReporting/StatusReportingApi/GetStatusReportingConfigurationForms`,
  UpsertGenericForms: `GenericForm/GenericFormApi/UpsertGenericForms`,
  CreateStatusReport: `StatusReporting/StatusReportingApi/CreateStatusReport`,
  GetMyTeamMembersList: `HrManagement/HrManagementApi/GetMyTeamMembersList`,
  UpsertStatusReportingConfiguration: `StatusReporting/StatusReportingApi/UpsertStatusReportingConfiguration`,
  GetStatusReportings: `StatusReporting/StatusReportingApi/GetStatusReportings`,
  GetGenericFormsByTypeId: `GenericForm/GenericFormApi/GetGenericFormsByTypeId`,
  GetStatusReportingConfigurations: `StatusReporting/StatusReportingApi/GetStatusReportingConfigurations`,
  UploadFile: `File/FileApi/UploadFile`,
  UpsertReportSeenStatus: `StatusReporting/StatusReportingApi/UpsertReportSeenStatus`,
  GetFormTypes: `GenericForm/GenericFormApi/GetFormTypes`,
  GetGenericForms: `GenericForm/GenericFormApi/GetGenericForms`,
  GetPerformanceSubmissions: "Performance/PerformanceApi/GetPerformanceSubmissions",
  GetPerformanceSubmissionDetails: "Performance/PerformanceApi/GetPerformanceSubmissionDetails",
  GetStatusReportingConfigurationOptions: `StatusReporting/StatusReportingApi/GetStatusReportingConfigurationOptions`,
  GetCustomizedDashboardId: `Widgets/WidgetsApi/GetCustomizedDashboardId`,
}
