export class InterviewScheduleModel {
  public candidateInterviewScheduleId: any;
  public interviewTypeId: any;
  public candidateId: any;
  public startTime: any;
  public endTime: any;
  public color: any;
  public interviewDate: Date;
  public isConfirmed: boolean;
  public isCancelled: boolean;
  public isRescheduled: boolean;
  public scheduleComments: string;
  public statusId: string;
  public timeStamp: any;
  public assignee: any;
  public assigneeEmail: any;
  public jobOpeningId: any;
  public cancelComment: any;
  public candidateEmail: any;
  public assigneeIds: any;
  public candidateName: any;
  public interviewTypeName: any;
  public IsInterviewer: boolean;
  public description: string;
  public isVideoCalling: boolean;
  public pageNumber: number;
  public pageSize: number;
  public totalCount: number;
  jobopeningId: any;
}
