import { CompanyIntroducedByComponent } from './lib/admin-module/components/company-structure/company-introduced.component';
import { CompanyLocationComponent } from './lib/admin-module/components/company-structure/company-location.component';
import { DateFormatComponent } from './lib/admin-module/components/company-structure/date-format.component';
import { CustomAccessibleIpAddressComponent } from './lib/admin-module/components/accessible-ip-address/accessible-address.component';
import { MainUseCaseComponent } from './lib/admin-module/components/company-structure/main-usecase.component';
import { NumberFormatComponent } from './lib/admin-module/components/company-structure/number-format.component';
import { TimeFormatComponent } from './lib/admin-module/components/company-structure/time-format.component';
import { ExpenseCategoryDetailsComponent } from './lib/admin-module/components/expense-management/expense-category.component';
import { MerchantDataComponent } from './lib/admin-module/components/expense-management/merchant.component';
import { BranchComponent } from './lib/admin-module/components/hrm/branch.component';
import { ContractTypeComponent } from './lib/admin-module/components/hrm/contract-type.component';
import { CountryComponent } from './lib/admin-module/components/hrm/country.component';
import { CurrencyComponent } from './lib/admin-module/components/hrm/currency.component';
import { DeapartmentComponent } from './lib/admin-module/components/hrm/department.component';
import { DesignationComponent } from './lib/admin-module/components/hrm/designation.component';
import { EducationlevelComponent } from './lib/admin-module/components/hrm/educationlevel.component';
import { EmploymentStatusComponent } from './lib/admin-module/components/hrm/employment-status.component';
import { JobCategoryComponent } from './lib/admin-module/components/hrm/job-category.component';
import { LanguagesComponent } from './lib/admin-module/components/hrm/language.component';
import { LicenseTypeComponent } from './lib/admin-module/components/hrm/license-type.component';
import { MembershipComponent } from './lib/admin-module/components/hrm/memberships.component';
import { NationalityComponent } from './lib/admin-module/components/hrm/nationality.component';
import { PayGradeComponent } from './lib/admin-module/components/hrm/pay-grade.component';
import { PayfrequencyComponent } from './lib/admin-module/components/hrm/payfrequency.component';
import { PaymentMethodComponent } from './lib/admin-module/components/hrm/payment-method.component';
import { PaymentTypeComponent } from './lib/admin-module/components/hrm/payment-type.component';
import { RateTypeComponent } from './lib/admin-module/components/hrm/rate-type.component';
import { RegionComponent } from './lib/admin-module/components/hrm/region.component';
import { ReportingMethodComponent } from './lib/admin-module/components/hrm/reporting-method.component';
import { ShiftTimingComponent } from './lib/admin-module/components/hrm/shift-timing.component';
import { SkillsComponent } from './lib/admin-module/components/hrm/skills.component';
import { StateComponent } from './lib/admin-module/components/hrm/state.component';
import { TimeZoneComponent } from './lib/admin-module/components/hrm/time-zone.component';
import { WebHookComponent } from './lib/admin-module/components/hrm/webhook.component';
import { AppsettingsComponent } from './lib/admin-module/components/mastersettings/appsetting.component';
import { TimeConfigurationSettingsComponent } from './lib/admin-module/components/mastersettings/time-configuration-settings.component';
import { BoardTypeApiComponent } from './lib/admin-module/components/projects/admin/boardtypeapi.component';
import { BoardTypeWorkFlowComponent } from './lib/admin-module/components/projects/admin/boardTypeWorkFlow.component';
import { ConsideredHoursComponent } from './lib/admin-module/components/projects/admin/consideredhours.component';
import { ProcessDashboardStatusComponent } from './lib/admin-module/components/projects/admin/processtdashboardstatus.component';
import { WorkFlowManagementComponent } from './lib/admin-module/components/projects/admin/workFlowMangement.component';
import { WorkFlowComponent } from './lib/admin-module/components/projects/admin/workFlows.component';
import { WorkFlowStatusTransitionComponent } from './lib/admin-module/components/projects/admin/workFlowStatusTransition.component';
import { WorkFlowManagementPageComponent } from './lib/admin-module/components/projects/containers/workFlowManagement.page';
import { BugPriorityComponent } from './lib/admin-module/components/projects/bug-priority.component';
import { GoalReplanTypeComponent } from './lib/admin-module/components/projects/goal-replan-type.component';
import { ProjectTypeComponent } from './lib/admin-module/components/projects/project-type.component';
import { UserStoryReplanTypeComponent } from './lib/admin-module/components/projects/user-story-replan-type.component';
import { UserStoryStatusComponent } from './lib/admin-module/components/projects/user-story-status.component';
import { UserStorySubTypeComponent } from './lib/admin-module/components/projects/user-story-sub-type.component';
import { FormTypeComponent } from './lib/admin-module/components/statusreporting/form-type.component';
import { TestcaseAutomationType } from './lib/admin-module/components/Testrail/test-case-automation-type.component';
import { TestcaseStatusComponent } from './lib/admin-module/components/Testrail/test-case-status-component';
import { TestcaseTemplateComponent } from './lib/admin-module/components/Testrail/test-case-template.component';
import { TestcaseTypeComponent } from './lib/admin-module/components/Testrail/test-case-type.component';
import { ButtonTypeComponent } from './lib/admin-module/components/Timesheet/button-type.component';
import { FeedbackTypeComponent } from './lib/admin-module/components/Timesheet/feedback-type.component';
import { PermissionReasonComponent } from './lib/admin-module/components/Timesheet/permission-reason.component';
import { BadgeComponent } from './lib/admin-module/components/hrm/badge.component';
import { PeakHourComponent } from './lib/admin-module/components/hrm/peakhours.component';
import { RateSheetComponent } from './lib/admin-module/components/hrm/ratesheet.component';
import { HolidayComponent } from './lib/admin-module/components/leaves/holiday.component';
import { LeaveFormulaComponent } from './lib/admin-module/components/leaves/leave-frequency-formula.component';
import { LeaveSessionComponent } from './lib/admin-module/components/leaves/leave-session.component';
import { LeaveStatusComponent } from './lib/admin-module/components/leaves/leave-status.component';
import { RestrictionTypeComponent } from './lib/admin-module/components/leaves/restriction-type.component';
import { TimeSheetManagementService } from './lib/admin-module/services/timesheet-managemet.service';
import { CompanyDetailsComponent } from './lib/admin-module/components/company-structure/company-details.component';
import { ProfessionaltaxrangesComponent } from './lib/admin-module/components/payroll/professionaltaxranges.component';
import { CompanysettingsComponent } from './lib/admin-module/components/mastersettings/companysetting.component';
import { UserStoryTypeComponent } from './lib/admin-module/components/projects/user-story-type.component';
import { PayrollfrequencyComponent } from './lib/admin-module/components/payroll/payrollfrequency.component';
import { TaxslabsComponent } from './lib/admin-module/components/payroll/taxslabs.component';
import { CompanyManagementService } from './lib/admin-module/services/company-management.service';
import { CompanyregistrationService } from './lib/admin-module/services/company-registration.service';
import { HRManagementService } from './lib/admin-module/services/hr-management.service';
import { LeavesManagementService } from './lib/admin-module/services/leaves-management.service';
import { MasterDataManagementService } from './lib/admin-module/services/master-data-management.service';
import { ProjectManagementService } from './lib/admin-module/services/project-management.service';
import { TestrailManagementService } from './lib/admin-module/services/testrail-management.service';
import { CustomWidgetsModel } from './lib/admin-module/models/hr-models/custom-widget-model';
import { CustomQueryModel } from './lib/admin-module/models/hr-models/custom-query-model';
import { DashboardConfiguration } from './lib/admin-module/models/hr-models/dashboard-configuration.model';
import { DesignationModel } from './lib/admin-module/models/hr-models/designation-model';
import { HrBranchModel } from './lib/admin-module/models/hr-models/branch-model';
import { RestrictionTypeModel } from './lib/admin-module/models/leaves-models/restriction-type-model';
import { LeaveFormulaModel } from './lib/admin-module/models/leaves-models/leave-formula-model';
import { ReminderModel } from './lib/admin-module/models/hr-models/reminder.model';
import { ButtonTypeInputModel } from './lib/admin-module/models/button-type-input-model';
import { LeaveStatusModel } from './lib/admin-module/models/leaves-models/leave-status-model';
import { LeaveSessionModel } from './lib/admin-module/models/leaves-models/leave-session-model';
import { EmployeeBadgeModel } from './lib/admin-module/models/hr-models/employee-badge.model';
import { CompanysettingsModel } from './lib/admin-module/models/company-model';
import { UserstoryTypeModel } from './lib/admin-module/models/projects/user-story-type-model';
import { CustomQueryHeadersModel } from './lib/admin-module/models/hr-models/custom-query-headers-model';
import { MaterSettingService } from './lib/admin-module/services/master-setting.services';
import { TimeConfiguration } from './lib/admin-module/models/time-configuration-model';
import { ProjectsService } from './lib/admin-module/services/Projects.service';
import { SignatureModel } from './lib/admin-module/models/hr-models/signature-model';
import { SoftLabelConfigurationService } from './lib/admin-module/services/softlabels.service';
import { EmployeeInductionModel, InductionModel } from './lib/admin-module/models/employee-induction.model';
import { CustomHtmlAppModel } from './lib/admin-module/models/hr-models/custom-html-app-model';
import { WidgetsModel } from './lib/admin-module/models/hr-models/widget-model';
import { CustomQueryOutputModel } from './lib/admin-module/models/hr-models/custom-query-output-model';
import { GridSettings } from './lib/admin-module/models/hr-models/grid-settings-model';
import { UserStory, UserStoryCustomFieldsModel } from './lib/admin-module/models/userStory';
import { DepartmentModel } from './lib/admin-module/models/hr-models/department-model';
import { ProcInputAndOutputModel } from './lib/admin-module/models/proc-inputs-outputs-model';
import { TemplatesComponent } from './lib/admin-module/components/mastersettings/template-management.component';
import { WidgetService } from './lib/admin-module/services/widget.service';
import { CustomAppFilter } from './lib/admin-module/models/customAppFilter';
import { CustomTagModel, CustomTagsModel } from './lib/admin-module/models/customTagsModel';
import { CustomWidgetList } from './lib/admin-module/models/customWidgetList';
import { DashboardList } from './lib/admin-module/models/dashboardList';
import { DynamicDashboardFilterModel, FilterKeyValueModel } from './lib/admin-module/models/dynamicDashboardFilerModel';
import { WidgetList } from './lib/admin-module/models/widgetlist';
import { WorkspaceList } from './lib/admin-module/models/workspaceList';
import { ProjectList } from './lib/admin-module/models/projectlist';
import { DashboardManagementComponent } from './lib/admin-module/components/widgets/dashboard-management.component';
import { PMSoftLabelsComponent } from './lib/admin-module/components/projects/soft-labels.component';
import { WidgetManagementComponent } from './lib/admin-module/components/widgets/widget.component';
import { TagsComponent } from './lib/admin-module/components/widgets/tags.component';
import { SpecificDayComponent } from './lib/admin-module/components/payroll/specificday.component';
import { CompanyHierarchyComponent } from './lib/admin-module/components/mastersettings/company-hierarchy.component';
import { BusinessUnitComponent } from './lib/admin-module/components/mastersettings/business-unit.component';

import { settingsComponent } from './lib/admin-module/components/settings/settings-component';
import { AdminRoutes } from './lib/admin-module/admin-module.routing'
import { productivityAreaComponent } from './lib/admin-module/components/productivity/productivity-area.component';
import { InsightsComponent } from './lib/admin-module/components/productivity/insights.component';
import { CumulativeWorkReportComponent } from './lib/admin-module/components/projects/cumulative-work-report';
import { ProductivityDashboardContainerComponent } from './lib/admin-module/components/productivity/productivity-dashboard-container.component'
import { DashboardLoadingComponent } from './lib/admin-module/components/productivity/dashboard-loading.component';
import { BounceBacksDrilldownComponent } from './lib/admin-module/components/productivity/bouncebacks-drilldown.component';
import { CompletedTasksDrilldownComponent } from './lib/admin-module/components/productivity/completetedtasks-drilldown.component';
import { DeliveredHoursDrilldownComponent } from './lib/admin-module/components/productivity/delivered-hours-drilldown.component';
import { EfficiencyDrilldownComponent } from './lib/admin-module/components/productivity/efficiency-drilldown.component';
import { NoOfBugsDrilldownComponent } from './lib/admin-module/components/productivity/noOfBugs-drilldown.component';
import { PendingTasksDrilldownComponent } from './lib/admin-module/components/productivity/pendingtasks-drilldown.component';
import { PlannedHoursDrilldownComponent } from './lib/admin-module/components/productivity/planned-hours-drilldown.component';
import { ReplansDrilldownComponent } from './lib/admin-module/components/productivity/replans-drilldown.component';
import { SpentHoursDrilldownComponent } from './lib/admin-module/components/productivity/spent-hours-drilldown.component';
import { UtilizationDrilldownComponent } from './lib/admin-module/components/productivity/utilization-drilldown.component';
import { ScriptsComponent } from './lib/admin-module/components/scripts/scriptscomponent';
import { SelectAllComponent } from './lib/admin-module/components/select-all/select-all.component';
import { ProductivityDrilldownComponent } from './lib/admin-module/components/productivity/productivity-drilldown.component';
import { TrendinsightsReportsGraphComponent } from './lib/admin-module/components/productivity/trendInsights-report.component';
import { CustomAppBaseComponent } from './lib/globaldependencies/components/componentbase';
import { SnovasysMessageBoxComponent } from '@thetradeengineorg1/snova-message-box';
import { RouterModule } from '@angular/router';
import { AdminModulesService } from './lib/admin-module/services/admin.module.service';
import { TimesheetStatusComponent } from './lib/admin-module/components/Roster/timesheet-submission-status.component';
export * from './lib/admin-module/admin-module.module';

export { CompanyIntroducedByComponent };
export { CompanyLocationComponent };
export { DateFormatComponent };
export { CustomAccessibleIpAddressComponent };
export { MainUseCaseComponent };
export { NumberFormatComponent };
export { TimeFormatComponent };
export { ExpenseCategoryDetailsComponent };
export { MerchantDataComponent };
export { BranchComponent };
export { ContractTypeComponent };
export { CountryComponent };
export { CurrencyComponent };
export { DeapartmentComponent };
export { DesignationComponent };
export { EducationlevelComponent };
export { EmploymentStatusComponent };
export { JobCategoryComponent };
export { LanguagesComponent };
export { LicenseTypeComponent };
export { MembershipComponent };
export { NationalityComponent };
export { PayGradeComponent };
export { PayfrequencyComponent };
export { PaymentMethodComponent };
export { PaymentTypeComponent };
export { RateTypeComponent };
export { RegionComponent };
export { ReportingMethodComponent };
export { ShiftTimingComponent };
export { SkillsComponent };
export { StateComponent };
export { TimeZoneComponent };
export { WebHookComponent };
export { AppsettingsComponent };
export { TimeConfigurationSettingsComponent };
export { BoardTypeApiComponent };
export { BoardTypeWorkFlowComponent };
export { ConsideredHoursComponent };
export { ProcessDashboardStatusComponent };
export { WorkFlowManagementComponent };
export { WorkFlowComponent };
export { WorkFlowStatusTransitionComponent };
export { WorkFlowManagementPageComponent };
export { BugPriorityComponent };
export { GoalReplanTypeComponent };
export { ProjectTypeComponent };
export { UserStoryReplanTypeComponent };
export { UserStoryStatusComponent };
export { UserStorySubTypeComponent };
export { FormTypeComponent };
export { TestcaseAutomationType };
export { TestcaseStatusComponent };
export { TestcaseTemplateComponent };
export { TestcaseTypeComponent };
export { ButtonTypeComponent };
export { FeedbackTypeComponent };
export { PermissionReasonComponent };
export { BadgeComponent };
export { PeakHourComponent };
export { RateSheetComponent };
export { HolidayComponent };
export { LeaveFormulaComponent };
export { LeaveSessionComponent };
export { LeaveStatusComponent };
export { RestrictionTypeComponent };
export { CompanyDetailsComponent };
export { UserStoryTypeComponent };
export { CompanysettingsComponent };
export { PayrollfrequencyComponent };
export { ProfessionaltaxrangesComponent };
export { TaxslabsComponent };
export { TemplatesComponent };
export { DashboardManagementComponent };
export { PMSoftLabelsComponent };
export { WidgetManagementComponent };
export { TagsComponent };
export { TimeSheetManagementService };
export { CompanyManagementService };
export { CompanyregistrationService };
export { HRManagementService };
export { LeavesManagementService };
export { MasterDataManagementService };
export { ProjectManagementService };
export { TestrailManagementService };
export { MaterSettingService };
export { ProjectsService };
export { SoftLabelConfigurationService };
export { WidgetService };
export { UserstoryTypeModel };
export { CompanysettingsModel };
export { EmployeeBadgeModel };
export { LeaveSessionModel };
export { LeaveStatusModel };
export { ReminderModel };
export { ButtonTypeInputModel };
export { LeaveFormulaModel };
export { RestrictionTypeModel };
export { HrBranchModel };
export { DesignationModel };
export { DashboardConfiguration };
export { CustomQueryModel };
export { CustomWidgetsModel };
export { CustomQueryHeadersModel };
export { TimeConfiguration };
export { SignatureModel };
export { EmployeeInductionModel };
export { InductionModel };
export { CustomHtmlAppModel };
export { WidgetsModel };
export { CustomQueryOutputModel };
export { GridSettings };
export { UserStory };
export { UserStoryCustomFieldsModel };
export { DepartmentModel };
export { ProcInputAndOutputModel };
export { CustomAppFilter };
export { CustomTagModel };
export { CustomTagsModel };
export { CustomWidgetList };
export { DashboardList };
export { DynamicDashboardFilterModel };
export { FilterKeyValueModel };
export { ProjectList };
export { WidgetList };
export { WorkspaceList };
export { SpecificDayComponent };
export { CompanyHierarchyComponent };
export { BusinessUnitComponent };
export { settingsComponent };
export { productivityAreaComponent };
export { InsightsComponent };
export { CumulativeWorkReportComponent };
export { ProductivityDashboardContainerComponent };
export { EfficiencyDrilldownComponent }
export { ScriptsComponent }
export { SelectAllComponent }
export { UtilizationDrilldownComponent }
export { CompletedTasksDrilldownComponent }
export { NoOfBugsDrilldownComponent }
export { PlannedHoursDrilldownComponent }
export { DeliveredHoursDrilldownComponent }
export { SpentHoursDrilldownComponent }
export { BounceBacksDrilldownComponent }
export { PendingTasksDrilldownComponent }
export { ReplansDrilldownComponent }
export { DashboardLoadingComponent }
export { TrendinsightsReportsGraphComponent }
export { ProductivityDrilldownComponent }
export { CustomAppBaseComponent }
export { SnovasysMessageBoxComponent }
export { AdminRoutes }
export { AdminModulesService }
export { TimesheetStatusComponent }