import { MessageService } from '@progress/kendo-angular-l10n';

const data = {
    en: {
        messages: {
            'kendo.scheduler.agendaViewTitle': 'Agenda',
            'kendo.scheduler.allDay': 'all day',
            'kendo.scheduler.allEvents': 'All events',
            'kendo.scheduler.calendarToday': 'TODAY',
            'kendo.scheduler.cancel': 'Cancel',
            'kendo.scheduler.save': 'Save',
            'kendo.scheduler.editorEventTitle': 'Title',
            'kendo.scheduler.editorEventStart': 'Start',
            'kendo.scheduler.editorEventStartTimeZone': 'Start Time Zone',
            'kendo.scheduler.editorEventEnd': 'End',
            'kendo.scheduler.editorEventEndTimeZone': 'End Time Zone',
            'kendo.scheduler.dateHeader': 'Date',
            'kendo.scheduler.dayViewTitle': 'Day',
            'kendo.scheduler.deleteConfirmation': 'Are you sure you want to delete this event?',
            'kendo.scheduler.deleteDialogTitle': 'Delete Event',
            'kendo.scheduler.deleteOccurrence': 'Delete current occurrence',
            'kendo.scheduler.deleteRecurringConfirmation': 'Do you want to delete only this event occurrence or the whole series?',
            'kendo.scheduler.deleteRecurringDialogTitle': 'Delete Recurring Item',
            'kendo.scheduler.deleteSeries': 'Delete the series',
            'kendo.scheduler.deleteTitle': 'Delete',
            'kendo.scheduler.destroy': 'Delete',
            'kendo.scheduler.editOccurrence': 'Edit current occurrence',
            'kendo.scheduler.editorEventAllDay': 'All Day Event',
            'kendo.scheduler.editorEventDescription': 'Description',
            'kendo.scheduler.editorEventSeparateTimeZones': 'End in different Time Zone',
            'kendo.scheduler.editorEventTimeZone': 'Specify Time Zone',
            'kendo.scheduler.editorTitle': 'Event',
            'kendo.scheduler.editRecurringConfirmation': 'Do you want to edit only this event occurrence or the whole series?',
            'kendo.scheduler.editRecurringDialogTitle': 'Edit Recurring Item',
            'kendo.scheduler.editSeries': 'Edit the series',
            'kendo.scheduler.eventHeader': 'Event',
            'kendo.scheduler.monthViewTitle': 'Month',
            'kendo.scheduler.multiDayViewTitle': 'Multi-Day',
            'kendo.scheduler.nextTitle': 'Next',
            'kendo.scheduler.previousTitle': 'Previous',
            'kendo.scheduler.recurrenceEditorDailyInterval': 'day(s)',
            'kendo.scheduler.recurrenceEditorDailyRepeatEvery': 'Repeat every',
            'kendo.scheduler.recurrenceEditorEndAfter': 'After',
            'kendo.scheduler.recurrenceEditorEndLabel': 'End',
            'kendo.scheduler.recurrenceEditorEndNever': 'Never',
            'kendo.scheduler.recurrenceEditorEndOccurrence': 'occurrence(s)',
            'kendo.scheduler.recurrenceEditorEndOn': 'On',
            'kendo.scheduler.recurrenceEditorFrequenciesDaily': 'Daily',
            'kendo.scheduler.recurrenceEditorFrequenciesMonthly': 'Monthly',
            'kendo.scheduler.recurrenceEditorFrequenciesNever': 'Never',
            'kendo.scheduler.recurrenceEditorFrequenciesWeekly': 'Weekly',
            'kendo.scheduler.recurrenceEditorFrequenciesYearly': 'Yearly',
            'kendo.scheduler.recurrenceEditorMonthlyDay': 'Day',
            'kendo.scheduler.recurrenceEditorMonthlyInterval': 'month(s)',
            'kendo.scheduler.recurrenceEditorMonthlyRepeatEvery': 'Repeat every',
            'kendo.scheduler.recurrenceEditorMonthlyRepeatOn': 'Repeat on',
            'kendo.scheduler.recurrenceEditorOffsetPositionsFirst': 'First',
            'kendo.scheduler.recurrenceEditorOffsetPositionsFourth': 'Fourth',
            'kendo.scheduler.recurrenceEditorOffsetPositionsLast': 'Last',
            'kendo.scheduler.recurrenceEditorOffsetPositionsSecond': 'Second',
            'kendo.scheduler.recurrenceEditorOffsetPositionsThird': 'Third',
            'kendo.scheduler.recurrenceEditorRepeat': 'Repeat',
            'kendo.scheduler.recurrenceEditorWeekdaysDay': 'Day',
            'kendo.scheduler.recurrenceEditorWeekdaysWeekday': 'Weekday',
            'kendo.scheduler.recurrenceEditorWeekdaysWeekendday': 'Weekend Day',
            'kendo.scheduler.recurrenceEditorWeeklyInterval': 'week(s)',
            'kendo.scheduler.recurrenceEditorWeeklyRepeatEvery': 'Repeat every',
            'kendo.scheduler.recurrenceEditorWeeklyRepeatOn': 'Repeat on',
            'kendo.scheduler.recurrenceEditorYearlyInterval': 'year(s)',
            'kendo.scheduler.recurrenceEditorYearlyOf': 'of',
            'kendo.scheduler.recurrenceEditorYearlyRepeatEvery': 'Repeat every',
            'kendo.scheduler.recurrenceEditorYearlyRepeatOn': 'Repeat on',
            'kendo.scheduler.showFullDay': 'Show full day',
            'kendo.scheduler.showWorkDay': 'Show business hours',
            'kendo.scheduler.timeHeader': 'Time',
            'kendo.scheduler.timelineMonthViewTitle': 'Timeline Month',
            'kendo.scheduler.timelineViewTitle': 'Timeline',
            'kendo.scheduler.timelineWeekViewTitle': 'Timeline Week',
            'kendo.scheduler.today': 'Today',
            'kendo.scheduler.weekViewTitle': 'Week',
            'kendo.scheduler.workWeekViewTitle': 'Work Week'
        }
    },
    te: {
        messages: {
            'kendo.scheduler.agendaViewTitle': 'అజెండా',
            'kendo.scheduler.allDay': 'రోజంతా',
            'kendo.scheduler.allEvents': 'అన్ని సంఘటనలు',
            'kendo.scheduler.calendarToday': 'ఈ రోజు',
            'kendo.scheduler.cancel': 'రద్దు చేయండి',
            'kendo.scheduler.save': 'సేవ్ చేయండి',
            'kendo.scheduler.editorEventTitle': 'శీర్షిక',
            'kendo.scheduler.editorEventStart': 'ప్రారంభించండి',
            'kendo.scheduler.editorEventStartTimeZone': 'సమయ మండలాన్ని ప్రారంభించండి',
            'kendo.scheduler.editorEventEnd': 'ముగింపు',
            'kendo.scheduler.editorEventEndTimeZone': 'ఎండ్ టైమ్ జోన్',
            'kendo.scheduler.dateHeader': 'తేదీ',
            'kendo.scheduler.dayViewTitle': 'రోజు',
            'kendo.scheduler.deleteConfirmation': 'మీరు ఖచ్చితంగా ఈ ఈవెంట్‌ను తొలగించాలనుకుంటున్నారా?',
            'kendo.scheduler.deleteDialogTitle': 'ఈవెంట్‌ను తొలగించండి',
            'kendo.scheduler.deleteOccurrence': 'ప్రస్తుత సంఘటనను తొలగించండి',
            'kendo.scheduler.deleteRecurringConfirmation': 'మీరు ఈ సంఘటన లేదా మొత్తం సిరీస్‌ను మాత్రమే తొలగించాలనుకుంటున్నారా?',
            'kendo.scheduler.deleteRecurringDialogTitle': 'పునరావృత అంశాన్ని తొలగించండి',
            'kendo.scheduler.deleteSeries': 'సిరీస్‌ను తొలగించండి',
            'kendo.scheduler.deleteTitle': 'తొలగించు',
            'kendo.scheduler.destroy': 'తొలగించు',
            'kendo.scheduler.editOccurrence': 'ప్రస్తుత సంఘటనను సవరించండి',
            'kendo.scheduler.editorEventAllDay': 'ఆల్ డే ఈవెంట్',
            'kendo.scheduler.editorEventDescription': 'వివరణ',
            'kendo.scheduler.editorEventSeparateTimeZones': 'వేర్వేరు సమయ మండలంలో ముగుస్తుంది',
            'kendo.scheduler.editorEventTimeZone': 'సమయ మండలాన్ని పేర్కొనండి',
            'kendo.scheduler.editorTitle': 'ఈవెంట్',
            'kendo.scheduler.editRecurringConfirmation': 'మీరు ఈ సంఘటన లేదా మొత్తం సిరీస్‌ను మాత్రమే సవరించాలనుకుంటున్నారా?',
            'kendo.scheduler.editRecurringDialogTitle': 'పునరావృత అంశాన్ని సవరించండి',
            'kendo.scheduler.editSeries': 'సిరీస్‌ను సవరించండి',
            'kendo.scheduler.eventHeader': 'ఈవెంట్',
            'kendo.scheduler.monthViewTitle': 'నెల',
            'kendo.scheduler.multiDayViewTitle': 'బహుళ-రోజు',
            'kendo.scheduler.nextTitle': 'తరువాత',
            'kendo.scheduler.previousTitle': 'మునుపటి',
            'kendo.scheduler.recurrenceEditorDailyInterval': 'రోజులు',
            'kendo.scheduler.recurrenceEditorDailyRepeatEvery': 'ప్రతి పునరావృతం',
            'kendo.scheduler.recurrenceEditorEndAfter': 'తరువాత',
            'kendo.scheduler.recurrenceEditorEndLabel': 'ముగింపు',
            'kendo.scheduler.recurrenceEditorEndNever': 'ఎప్పుడూ',
            'kendo.scheduler.recurrenceEditorEndOccurrence': 'సంభవించడం (లు)',
            'kendo.scheduler.recurrenceEditorEndOn': 'పై',
            'kendo.scheduler.recurrenceEditorFrequenciesDaily': 'రోజువారీ',
            'kendo.scheduler.recurrenceEditorFrequenciesMonthly': 'నెలవారీ',
            'kendo.scheduler.recurrenceEditorFrequenciesNever': 'ఎప్పుడూ',
            'kendo.scheduler.recurrenceEditorFrequenciesWeekly': 'వీక్లీ',
            'kendo.scheduler.recurrenceEditorFrequenciesYearly': 'వార్షిక',
            'kendo.scheduler.recurrenceEditorMonthlyDay': 'రోజు',
            'kendo.scheduler.recurrenceEditorMonthlyInterval': 'నెలల',
            'kendo.scheduler.recurrenceEditorMonthlyRepeatEvery': 'ప్రతి పునరావృతం',
            'kendo.scheduler.recurrenceEditorMonthlyRepeatOn': 'పునరావృతం చేయండి',
            'kendo.scheduler.recurrenceEditorOffsetPositionsFirst': 'ప్రధమ',
            'kendo.scheduler.recurrenceEditorOffsetPositionsFourth': 'నాల్గవది',
            'kendo.scheduler.recurrenceEditorOffsetPositionsLast': 'చివరిది',
            'kendo.scheduler.recurrenceEditorOffsetPositionsSecond': 'రెండవ',
            'kendo.scheduler.recurrenceEditorOffsetPositionsThird': 'మూడవది',
            'kendo.scheduler.recurrenceEditorRepeat': 'పునరావృతం చేయండి',
            'kendo.scheduler.recurrenceEditorWeekdaysDay': 'రోజు',
            'kendo.scheduler.recurrenceEditorWeekdaysWeekday': 'వారపు రోజు',
            'kendo.scheduler.recurrenceEditorWeekdaysWeekendday': 'వీకెండ్ డే',
            'kendo.scheduler.recurrenceEditorWeeklyInterval': 'వారాలు',
            'kendo.scheduler.recurrenceEditorWeeklyRepeatEvery': 'ప్రతి పునరావృతం',
            'kendo.scheduler.recurrenceEditorWeeklyRepeatOn': 'పునరావృతం చేయండి',
            'kendo.scheduler.recurrenceEditorYearlyInterval': 'సంవత్సరం (లు)',
            'kendo.scheduler.recurrenceEditorYearlyOf': 'యొక్క',
            'kendo.scheduler.recurrenceEditorYearlyRepeatEvery': 'ప్రతి పునరావృతం',
            'kendo.scheduler.recurrenceEditorYearlyRepeatOn': 'పునరావృతం చేయండి',
            'kendo.scheduler.showFullDay': 'పూర్తి రోజు చూపించు',
            'kendo.scheduler.showWorkDay': 'వ్యాపార సమయాన్ని చూపించు',
            'kendo.scheduler.timeHeader': 'సమయం',
            'kendo.scheduler.timelineMonthViewTitle': 'కాలక్రమం నెల',
            'kendo.scheduler.timelineViewTitle': 'కాలక్రమం',
            'kendo.scheduler.timelineWeekViewTitle': 'కాలక్రమం వారం',
            'kendo.scheduler.today': 'ఈ రోజు',
            'kendo.scheduler.weekViewTitle': 'వారం',
            'kendo.scheduler.workWeekViewTitle': 'పని వారం'
        }
    },
    ko: {
        messages: {
            'kendo.scheduler.agendaViewTitle': '의제',
            'kendo.scheduler.allDay': '하루 종일',
            'kendo.scheduler.allEvents': '모든 이벤트',
            'kendo.scheduler.calendarToday': '오늘',
            'kendo.scheduler.cancel': '취소',
            'kendo.scheduler.save': '저장',
            'kendo.scheduler.editorEventTitle': '표제',
            'kendo.scheduler.editorEventStart': '스타트',
            'kendo.scheduler.editorEventStartTimeZone': '시작 시간대',
            'kendo.scheduler.editorEventEnd': '종료',
            'kendo.scheduler.editorEventEndTimeZone': '종료 시간대',
            'kendo.scheduler.dateHeader': '데이트',
            'kendo.scheduler.dayViewTitle': '일',
            'kendo.scheduler.deleteConfirmation': '이 이벤트를 삭제 하시겠습니까?',
            'kendo.scheduler.deleteDialogTitle': '이벤트 삭제',
            'kendo.scheduler.deleteOccurrence': '현재 발생 삭제',
            'kendo.scheduler.deleteRecurringConfirmation': '이 이벤트 발생 만 삭제 하시겠습니까, 아니면 전체 시리즈를 삭제 하시겠습니까?',
            'kendo.scheduler.deleteRecurringDialogTitle': '반복 항목 삭제',
            'kendo.scheduler.deleteSeries': '시리즈 삭제',
            'kendo.scheduler.deleteTitle': '지우다',
            'kendo.scheduler.destroy': '지우다',
            'kendo.scheduler.editOccurrence': '현재 발생 수정',
            'kendo.scheduler.editorEventAllDay': '하루 종일 이벤트',
            'kendo.scheduler.editorEventDescription': '기술',
            'kendo.scheduler.editorEventSeparateTimeZones': '다른 시간대로 종료',
            'kendo.scheduler.editorEventTimeZone': '시간대 지정',
            'kendo.scheduler.editorTitle': '행사',
            'kendo.scheduler.editRecurringConfirmation': '이 이벤트 발생 만 편집 하시겠습니까, 아니면 전체 시리즈를 편집 하시겠습니까?',
            'kendo.scheduler.editRecurringDialogTitle': '반복 항목 편집',
            'kendo.scheduler.editSeries': '시리즈 편집',
            'kendo.scheduler.eventHeader': '행사',
            'kendo.scheduler.monthViewTitle': '달',
            'kendo.scheduler.multiDayViewTitle': '여러 날',
            'kendo.scheduler.nextTitle': '다음',
            'kendo.scheduler.previousTitle': '이전',
            'kendo.scheduler.recurrenceEditorDailyInterval': '일',
            'kendo.scheduler.recurrenceEditorDailyRepeatEvery': '반복',
            'kendo.scheduler.recurrenceEditorEndAfter': '후',
            'kendo.scheduler.recurrenceEditorEndLabel': '종료',
            'kendo.scheduler.recurrenceEditorEndNever': '못',
            'kendo.scheduler.recurrenceEditorEndOccurrence': '발생',
            'kendo.scheduler.recurrenceEditorEndOn': '의 위에',
            'kendo.scheduler.recurrenceEditorFrequenciesDaily': '매일',
            'kendo.scheduler.recurrenceEditorFrequenciesMonthly': '월간 간행물',
            'kendo.scheduler.recurrenceEditorFrequenciesNever': '못',
            'kendo.scheduler.recurrenceEditorFrequenciesWeekly': '주간',
            'kendo.scheduler.recurrenceEditorFrequenciesYearly': '매년',
            'kendo.scheduler.recurrenceEditorMonthlyDay': '일',
            'kendo.scheduler.recurrenceEditorMonthlyInterval': '개월',
            'kendo.scheduler.recurrenceEditorMonthlyRepeatEvery': '반복',
            'kendo.scheduler.recurrenceEditorMonthlyRepeatOn': '반복',
            'kendo.scheduler.recurrenceEditorOffsetPositionsFirst': '먼저',
            'kendo.scheduler.recurrenceEditorOffsetPositionsFourth': '네번째',
            'kendo.scheduler.recurrenceEditorOffsetPositionsLast': '마지막',
            'kendo.scheduler.recurrenceEditorOffsetPositionsSecond': '둘째',
            'kendo.scheduler.recurrenceEditorOffsetPositionsThird': '제삼',
            'kendo.scheduler.recurrenceEditorRepeat': '반복',
            'kendo.scheduler.recurrenceEditorWeekdaysDay': '일',
            'kendo.scheduler.recurrenceEditorWeekdaysWeekday': '주일',
            'kendo.scheduler.recurrenceEditorWeekdaysWeekendday': '주말',
            'kendo.scheduler.recurrenceEditorWeeklyInterval': '주',
            'kendo.scheduler.recurrenceEditorWeeklyRepeatEvery': '반복',
            'kendo.scheduler.recurrenceEditorWeeklyRepeatOn': '반복',
            'kendo.scheduler.recurrenceEditorYearlyInterval': '연령',
            'kendo.scheduler.recurrenceEditorYearlyOf': '의',
            'kendo.scheduler.recurrenceEditorYearlyRepeatEvery': '반복',
            'kendo.scheduler.recurrenceEditorYearlyRepeatOn': '반복',
            'kendo.scheduler.showFullDay': '하루 종일 표시',
            'kendo.scheduler.showWorkDay': '영업 시간 표시',
            'kendo.scheduler.timeHeader': '시각',
            'kendo.scheduler.timelineMonthViewTitle': '타임 라인 월',
            'kendo.scheduler.timelineViewTitle': '타임 라인',
            'kendo.scheduler.timelineWeekViewTitle': '타임 라인 주',
            'kendo.scheduler.today': '오늘',
            'kendo.scheduler.weekViewTitle': '주',
            'kendo.scheduler.workWeekViewTitle': '작업 주'
        }
    },
    ar: {
        messages: {
            'kendo.scheduler.agendaViewTitle': 'جدول أعمال',
            'kendo.scheduler.allDay': 'طوال اليوم',
            'kendo.scheduler.allEvents': 'كل الأحداث',
            'kendo.scheduler.calendarToday': 'اليوم',
            'kendo.scheduler.cancel': 'إلغاء',
            'kendo.scheduler.save': 'حفظ',
            'kendo.scheduler.editorEventTitle': 'عنوان',
            'kendo.scheduler.editorEventStart': 'بداية',
            'kendo.scheduler.editorEventStartTimeZone': 'المنطقة الزمنية للبدء',
            'kendo.scheduler.editorEventEnd': 'النهاية',
            'kendo.scheduler.editorEventEndTimeZone': 'المنطقة الزمنية للانتهاء',
            'kendo.scheduler.dateHeader': 'تاريخ',
            'kendo.scheduler.dayViewTitle': 'يوم',
            'kendo.scheduler.deleteConfirmation': 'هل أنت متأكد من حذف هذا الحدث؟',
            'kendo.scheduler.deleteDialogTitle': 'حذف الحدث',
            'kendo.scheduler.deleteOccurrence': 'حذف التواجد الحالي',
            'kendo.scheduler.deleteRecurringConfirmation': 'هل تريد حذف هذا الحدث فقط أم السلسلة بأكملها؟',
            'kendo.scheduler.deleteRecurringDialogTitle': 'حذف العنصر المتكرر',
            'kendo.scheduler.deleteSeries': 'احذف السلسلة',
            'kendo.scheduler.deleteTitle': 'حذف',
            'kendo.scheduler.destroy': 'حذف',
            'kendo.scheduler.editOccurrence': 'تحرير التواجد الحالي',
            'kendo.scheduler.editorEventAllDay': 'حدث طوال اليوم',
            'kendo.scheduler.editorEventDescription': 'وصف',
            'kendo.scheduler.editorEventSeparateTimeZones': 'انتهى في منطقة زمنية مختلفة',
            'kendo.scheduler.editorEventTimeZone': 'حدد المنطقة الزمنية',
            'kendo.scheduler.editorTitle': 'حدث',
            'kendo.scheduler.editRecurringConfirmation': 'هل تريد تحرير هذا الحدث فقط أم السلسلة بأكملها؟',
            'kendo.scheduler.editRecurringDialogTitle': 'تحرير العنصر المتكرر',
            'kendo.scheduler.editSeries': 'قم بتحرير السلسلة',
            'kendo.scheduler.eventHeader': 'حدث',
            'kendo.scheduler.monthViewTitle': 'شهر',
            'kendo.scheduler.multiDayViewTitle': 'عدة أيام',
            'kendo.scheduler.nextTitle': 'التالى',
            'kendo.scheduler.previousTitle': 'السابق',
            'kendo.scheduler.recurrenceEditorDailyInterval': 'أيام)',
            'kendo.scheduler.recurrenceEditorDailyRepeatEvery': 'تكرار كل',
            'kendo.scheduler.recurrenceEditorEndAfter': 'بعد',
            'kendo.scheduler.recurrenceEditorEndLabel': 'النهاية',
            'kendo.scheduler.recurrenceEditorEndNever': 'أبدا',
            'kendo.scheduler.recurrenceEditorEndOccurrence': 'تواجد (حالات)',
            'kendo.scheduler.recurrenceEditorEndOn': 'على',
            'kendo.scheduler.recurrenceEditorFrequenciesDaily': 'اليومي',
            'kendo.scheduler.recurrenceEditorFrequenciesMonthly': 'شهريا',
            'kendo.scheduler.recurrenceEditorFrequenciesNever': 'أبدا',
            'kendo.scheduler.recurrenceEditorFrequenciesWeekly': 'أسبوعي',
            'kendo.scheduler.recurrenceEditorFrequenciesYearly': 'سنوي',
            'kendo.scheduler.recurrenceEditorMonthlyDay': 'يوم',
            'kendo.scheduler.recurrenceEditorMonthlyInterval': 'الشهور)',
            'kendo.scheduler.recurrenceEditorMonthlyRepeatEvery': 'تكرار كل',
            'kendo.scheduler.recurrenceEditorMonthlyRepeatOn': 'كرر على',
            'kendo.scheduler.recurrenceEditorOffsetPositionsFirst': 'أول',
            'kendo.scheduler.recurrenceEditorOffsetPositionsFourth': 'الرابعة',
            'kendo.scheduler.recurrenceEditorOffsetPositionsLast': 'الاخير',
            'kendo.scheduler.recurrenceEditorOffsetPositionsSecond': 'ثانيا',
            'kendo.scheduler.recurrenceEditorOffsetPositionsThird': 'الثالث',
            'kendo.scheduler.recurrenceEditorRepeat': 'كرر',
            'kendo.scheduler.recurrenceEditorWeekdaysDay': 'يوم',
            'kendo.scheduler.recurrenceEditorWeekdaysWeekday': 'يوم من أيام الأسبوع',
            'kendo.scheduler.recurrenceEditorWeekdaysWeekendday': 'يوم عطلة نهاية الأسبوع',
            'kendo.scheduler.recurrenceEditorWeeklyInterval': 'أسبوع (أسابيع)',
            'kendo.scheduler.recurrenceEditorWeeklyRepeatEvery': 'تكرار كل',
            'kendo.scheduler.recurrenceEditorWeeklyRepeatOn': 'كرر على',
            'kendo.scheduler.recurrenceEditorYearlyInterval': 'سنوات)',
            'kendo.scheduler.recurrenceEditorYearlyOf': 'من',
            'kendo.scheduler.recurrenceEditorYearlyRepeatEvery': 'تكرار كل',
            'kendo.scheduler.recurrenceEditorYearlyRepeatOn': 'كرر على',
            'kendo.scheduler.showFullDay': 'عرض يوم كامل',
            'kendo.scheduler.showWorkDay': 'عرض ساعات العمل',
            'kendo.scheduler.timeHeader': 'زمن',
            'kendo.scheduler.timelineMonthViewTitle': 'شهر المخطط الزمني',
            'kendo.scheduler.timelineViewTitle': 'الجدول الزمني',
            'kendo.scheduler.timelineWeekViewTitle': 'أسبوع المخطط الزمني',
            'kendo.scheduler.today': 'اليوم',
            'kendo.scheduler.weekViewTitle': 'أسبوع',
            'kendo.scheduler.workWeekViewTitle': 'أسبوع العمل'
        }
    }
};

export class ShedularTranslateService extends MessageService {
    public set language(value: string) {
        const lang = data[value];
        if (lang) {
            this.localeId = value;
        }
    }

    public get language(): string {
        return this.localeId;
    }

    private localeId = 'es';
    private get messages(): any {
        const lang = data[this.localeId];

        if (lang) {
            return lang.messages;
        }
    }

    public get(key: string): string {
        if(this.messages)
        return this.messages[key];
        else
        return null;
    }
}
