import { Component, OnInit } from "@angular/core";
import { FeatureIds } from '../../globaldependencies/constants/feature-ids';
import * as _ from "underscore";
import { LocalStorageProperties } from '../constants/localstorage-properties';

@Component({
  template: ""
})
export class AppBaseComponent implements OnInit {
  canAccess_feature_ManageRegion: boolean;
  canAccess_feature_AddOrUpdateClient: boolean;
  canAccess_feature_ViewRecentlyActiveClients: boolean;
  canAccess_feature_ManageImportOrExportClient: boolean;
  canAccess_feature_ViewEstimate: boolean;
  canAccess_feature_AddOrUpdateEstimate: boolean;
  canAccess_feature_ArchiveOrUnarchiveEstimate: boolean;
  canAccess_feature_AddOrUpdateInvoice: boolean;
  canAccess_feature_ViewOrManageInvoiceStatus: boolean;
  canAccess_feature_ViewInvoice: boolean;
  canAccess_feature_DownloadOrShareInvoice: boolean;
  canAccess_feature_ArchiveOrUnarchiveInvoice: boolean;
  canAccess_feature_ConfigureKYC: boolean;
  canAccess_feature_ManageLeadTemplates: boolean;
  canAccess_feature_AddLeadTemplates: boolean;
  canAccess_feature_ManagePurchaseContract: boolean;
  canAccess_feature_ManageSite: boolean;
  canAccess_feature_ManageGRD: boolean;
  canAccess_feature_ManageTVA: boolean;
  canAccess_feature_ManageSolarLog: boolean;
  canAccess_feature_ManageManageEntryFormField: boolean;
  canAccess_feature_ManageGrades: boolean;
  canAccess_feature_ManageProduct: boolean;
  canAccess_feature_ManagePortDetails: boolean;
  canAccess_feature_ManageModeorTermsofPayment: boolean;
  canAccess_feature_ViewClientInvoices: boolean;
  canAccess_feature_CreateClientInvoice: boolean;
  canAccess_feature_ViewContracts: boolean;
  canAccess_feature_AddContracts: boolean;
  canAccess_feature_EditContracts: boolean;
  canAccess_feature_ArchiveContracts: boolean;
  canAccess_feature_ViewLeads: boolean;
  canAccess_feature_CreateLeads: boolean;
  canAccess_feature_ViewCreditLogs: boolean;
  canAccess_feature_ManageConsignee: boolean;
  canAccess_feature_ManageConsigner: boolean;
  canAccess_feature_ManageVessels: boolean;
  canAccess_feature_AddPurchaseExecution: boolean;
  canAccess_feature_ViewPurchaseExecution: boolean;
  canAccess_feature_ManageExpenseBooking: boolean;
  canAccess_feature_ManagePaymentReceipt: boolean;
  canAccess_feature_ManageMasterAccount: boolean;
  canAccess_feature_ManageCreditNote: boolean;
  canAccess_feature_ManageLegalEntities: boolean;
  canAccess_feature_ManageClientTypes: boolean;
  canAccess_feature_ManageAddresses: boolean;
  canAccess_feature_ManageClientSettings: boolean;
  canAccess_feature_ManageKycStatus: boolean;
  canAccess_feature_ViewClientKycHistory: boolean;
  canAccess_feature_ViewEmailTemplates: boolean;
  canAccess_feature_EditEmailTemplates: boolean;
  canAccess_feature_ManageContractStatus: boolean;
  canAccess_feature_ManageInvoiceStatus: boolean;
  canAccess_feature_ManageTolerance: boolean;
  canAccess_feature_ManagePaymentCondition: boolean;
  canAccess_feature_ManageContractTemplates: boolean;
  canAccess_feature_ManageTradeTemplates: boolean;
  canAccess_feature_CancelPurchaseContracts: boolean;
  canAccess_feature_ArchivePurchaseContracts: boolean;
  canAccess_feature_EditPurchaseContracts: boolean;
  canAccess_feature_ViewPurchaseContracts: boolean;
  canAccess_feature_SharePurchaseContracts: boolean;
  canAccess_feature_CancelSaleContracts: boolean;
  canAccess_feature_ArchiveSaleContracts: boolean;
  canAccess_feature_EditSaleContracts: boolean;
  canAccess_feature_ViewSaleContracts: boolean;
  canAccess_feature_ShareSaleContracts: boolean;
  canAccess_feature_CancelVesselContracts: boolean;
  canAccess_feature_EditVesselContracts: boolean;
  canAccess_feature_ViewVesselContracts: boolean;
  canAccess_feature_ShareVesselContracts: boolean;
  canAccess_feature_EditLinkedContracts: boolean;
  canAccess_feature_ViewLinkedContracts: boolean;
  canAccess_feature_ViewInvoiceQueues: boolean;
  canAccess_feature_ViewPayables: boolean;
  canAccess_feature_ManagePayableStatus: boolean;
  canAccess_feature_ManageReceivableStatus: boolean;
  canAccess_feature_ViewReceivables: boolean;
  canAccess_feature_EditInvoiceQueue: boolean;
  canAccess_feature_ShareInvoiceQueue: boolean;
  canAccess_feature_ViewAllPurchaseContracts: boolean;
  canAccess_feature_ViewAllSaleContracts: boolean;
  canAccess_feature_ViewAllVesselContracts: boolean;
  canAccess_feature_ViewAllInvoiceQueues: boolean;
  canAccess_feature_ViewAllLinkedContracts: boolean;
  canAccess_feature_AddRfq: boolean;
  canAccess_feature_ConvertRfqToVessel: boolean;
  canAccess_feature_ViewRfqs: boolean;
  canAccess_feature_ShareRfqs: boolean;
  canAccess_feature_ApproveorRejectSaleContract: boolean;
  canAccess_feature_GeneratePurchaseContract: boolean;
  canAccess_feature_ApproveorRejectPurchaseContract: boolean;
  canAccess_feature_GenerateSalesContract: boolean;
  canAccess_feature_ApproveorRejectExecutionSteps: boolean;
  canAccess_feature_GenerateExecutionSteps: boolean;
  canAccess_feature_ShareExecutionSteps: boolean;
  canAccess_feature_ViewPurchaseContractHistory: boolean;
  canAccess_feature_ViewVesselContractHistory: boolean;
  canAccess_feature_ViewSalesContractHistory: boolean;
  canAccess_feature_ViewInvoiceQueueHistory: boolean;
  canAccess_feature_ViewSwitchBl: boolean;
  canAccess_feature_AddorUpdateSwitchBl: boolean;
  canAccess_feature_CanReUploadFile : boolean;
  canAccess_feature_CanReInitiateStep : boolean;
  canAccess_feature_ResendKycMail: boolean;
  canAccess_feature_CanStampPdf : boolean;
  canAccess_feature_ManageaRfqStatus: boolean;
  ngOnInit(): void {
    var roles = JSON.parse(localStorage.getItem(LocalStorageProperties.RoleFeatures));
    this.canAccess_feature_ManageRegion = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageRegion.toString().toLowerCase(); }) != null;
    this.canAccess_feature_AddOrUpdateClient = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_AddOrUpdateClient.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewRecentlyActiveClients = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ViewRecentlyActiveClients.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageImportOrExportClient = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageImportOrExportClient.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewEstimate = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ViewEstimate.toString().toLowerCase(); }) != null;
    this.canAccess_feature_AddOrUpdateEstimate = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_AddOrUpdateEstimate.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ArchiveOrUnarchiveEstimate = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ArchiveOrUnarchiveEstimate.toString().toLowerCase(); }) != null;
    this.canAccess_feature_AddOrUpdateInvoice = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_AddOrUpdateInvoice.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewOrManageInvoiceStatus = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ViewOrManageInvoiceStatus.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewInvoice = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ViewInvoice.toString().toLowerCase(); }) != null;
    this.canAccess_feature_DownloadOrShareInvoice = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_DownloadOrShareInvoice.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ArchiveOrUnarchiveInvoice = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ArchiveOrUnarchiveInvoice.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ConfigureKYC = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ConfigureKYC.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageLeadTemplates = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageLeadtemplates.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManagePurchaseContract = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManagePurchaseContract.toString().toLowerCase(); }) != null;
    this.canAccess_feature_AddLeadTemplates = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_AddLeadtemplates.toString().toLowerCase(); }) != null;

    this.canAccess_feature_ManageSite = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageSite.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageGRD = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageGRD.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageTVA = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageTVA.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageSolarLog = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageSolarLog.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageManageEntryFormField = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageManageEntryFormField.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageProduct = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageProduct.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageModeorTermsofPayment = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageModeorTermsofPayment.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManagePortDetails = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManagePortDetails.toString().toLowerCase(); }) != null;
    this.canAccess_feature_CreateClientInvoice = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_CreateClientInvoice.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewClientInvoices = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ViewClientInvoices.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageGrades = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageGrades.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewContracts = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ViewContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_AddContracts = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_AddContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_EditContracts = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_EditContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ArchiveContracts = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ArchiveContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewLeads = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ViewLeads.toString().toLowerCase(); }) != null;
    this.canAccess_feature_CreateLeads = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_CreateLeads.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewCreditLogs = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ViewCreditLogs.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageConsignee = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageConsignee.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageConsigner = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ManageConsigner.toString().toLowerCase(); }) != null;
    this.canAccess_feature_AddPurchaseExecution = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_AddPurchaseExecution.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewPurchaseExecution = _.find(roles, function (role) { return role.featureId.toLowerCase() == FeatureIds.Feature_ViewPurchaseExecution.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageSite = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageSite.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageGRD = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageGRD.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageTVA = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageTVA.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageSolarLog = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageSolarLog.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageManageEntryFormField = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageManageEntryFormField.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageExpenseBooking = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageExpenseBookingId.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManagePaymentReceipt = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManagePaymentReceiptId.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageCreditNote = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageCreditNoteId.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageMasterAccount = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageMasterAccountId.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageLegalEntities = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageLegalEntities.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageClientTypes = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageClientTypes.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageVessels = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageVessels.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageAddresses = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageAddresses.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageClientSettings = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageClientSettings.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageKycStatus = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageKycStatus.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewClientKycHistory = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewClientKycHistory.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewEmailTemplates = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewEmailTemplates.toString().toLowerCase(); }) != null;
    this.canAccess_feature_EditEmailTemplates = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_EditEmailTemplates.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageContractStatus = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageContractSatus.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageInvoiceStatus = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageInvoiceSatus.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageTolerance = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageTolerance.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManagePaymentCondition = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManagePaymentCondition.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageContractTemplates = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageContractTemplates.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageTradeTemplates = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageTradeTemplates.toString().toLowerCase(); }) != null;
    this.canAccess_feature_CancelPurchaseContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_CancelPurchaseContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ArchivePurchaseContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ArchivePurchaseContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_EditPurchaseContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_EditPurchaseContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewPurchaseContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewPurchaseContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_SharePurchaseContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_SharePurchaseContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_CancelSaleContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_CancelSaleContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ArchiveSaleContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ArchiveSaleContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_EditSaleContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_EditSaleContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewSaleContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewSaleContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ShareSaleContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ShareSaleContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_CancelVesselContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_CancelVesselContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_EditVesselContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_EditVesselContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewVesselContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewVesselContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ShareVesselContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ShareVesselContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_EditLinkedContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_EditLinkedContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewLinkedContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewLinkedContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewInvoiceQueues = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewInvoiceQueues.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewPayables = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewPayables.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManagePayableStatus = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManagePayableStatus.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageReceivableStatus = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageReceivableStatus.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewReceivables = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewReceivables.toString().toLowerCase(); }) != null;
    this.canAccess_feature_EditInvoiceQueue = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_EditInvoiceQueue.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ShareInvoiceQueue = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ShareInvoiceQueue.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewAllPurchaseContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewAllPurchaseContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewAllSaleContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewAllSaleContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewAllVesselContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewAllVesselContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewAllInvoiceQueues = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewAllInvoiceQueues.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewAllLinkedContracts = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewAllLinkedContracts.toString().toLowerCase(); }) != null;
    this.canAccess_feature_AddRfq = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_AddRfq.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ConvertRfqToVessel = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ConvertRfqToVessel.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewRfqs = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewRfqs.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ShareRfqs = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ShareRfqs.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ApproveorRejectPurchaseContract = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ApproveorRejectPurchaseContract.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ApproveorRejectSaleContract = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ApproveorRejectSaleContract.toString().toLowerCase(); }) != null;
    this.canAccess_feature_GeneratePurchaseContract = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_GeneratePurchaseContract.toString().toLowerCase(); }) != null;
    this.canAccess_feature_GenerateSalesContract = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_GenerateSalesContract.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ShareExecutionSteps = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ShareExecutionSteps.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ApproveorRejectExecutionSteps = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ApproveorRejectExecutionSteps.toString().toLowerCase(); }) != null;
    this.canAccess_feature_GenerateExecutionSteps = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_GenerateExecutionSteps.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewPurchaseContractHistory = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewPurchaseContractHistory.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewSalesContractHistory = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewSalesContractHistory.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewVesselContractHistory = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewVesselContractHistory.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewInvoiceQueueHistory = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewInvoiceQueueHistory.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ViewSwitchBl = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ViewSwitchBl.toString().toLowerCase(); }) != null;
    this.canAccess_feature_AddorUpdateSwitchBl = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_AddorUpdateSwitchBl.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ResendKycMail = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ResendKycMail.toString().toLowerCase(); }) != null;
    this.canAccess_feature_CanReUploadFile = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_CanReUploadFile.toString().toLowerCase(); }) != null;
    this.canAccess_feature_CanReInitiateStep = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_CanReInitiateStep.toString().toLowerCase(); }) != null;
    this.canAccess_feature_CanStampPdf = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_CanStampDocument.toString().toLowerCase(); }) != null;
    this.canAccess_feature_ManageaRfqStatus = _.find(roles, function(role){ return role.featureId.toLowerCase() == FeatureIds.Feature_ManageRfqStatus.toString().toLowerCase(); }) != null;

  }

  constructor() {
    this.logNavigation();
  }

  protected logError(errorMessage: string) {

  }

  private logNavigation() {
  }
}
