export const ConstantVariables = {
    FormNameMaxLength100: "Form name should not exceed 100 characters",
    ActiveGoalStatusId: "7A79AB9F-D6F0-40A0-A191-CED6C06656DE",
    BacklogGoalStatusId: "F6F118EA-7023-45F1-BCF6-CE6DB1CEE5C3",
    ReplanGoalStatusId: "5AF65423-AFC4-4E9D-A011-F4DF97ED5FAF",
    ParkedGoalStatusId: "B328CFA8-6D63-4F2C-9EF1-3359E8DD35C7",
    ArchivedGoalStatusId: "B25B79E1-82E5-40BC-9D1A-4591E620D895",
    StartButtonTypeId: "0693F575-D25D-49F3-8E94-142AE33C7EFC",
    FinishButtonTypeId: "B1BA3B9A-F5EB-4985-A80B-4479637E140F",
    BreakInButtonTypeId: "D8AE4F48-9022-458A-AB10-F56E31F0ED9F",
    BreakOutButtonTypeId: "06D1A79D-852A-4E7E-8BEA-C7E731C3E691",
    LunchEndButtonTypeId: " 67584D1C-3D85-488E-9624-976EFDF7ADB3",
    LunchStartButtonTypeId: "2D5AEE6C-BC6B-47D6-B84A-84D7A2605B25",
    INRCurrencyId: "DF549957-74CC-4622-A094-05F64973F092",
    FailedStatusId: "63D3D282-76DB-4E95-96D6-0C368681E3DB",
    UserStoryReferenceTypeId: "1B35F2D3-1972-491F-8DC8-0A2A1F429934",
    SprintReferenceTypeId: "38148E7C-9B2F-4735-848D-BD703195A395",
    ProjectReferenceTypeId: "26A91CCF-504A-479C-8E8F-92128FB03AF6",
    GoalReferenceTypeId: "A40F3109-F880-4214-9367-4D5E86864649",
    SprintUserStoryReferenceId: "FFD17211-18F0-4954-A2E5-251671E937B8",
    CustomApllicationReferenceTypeId: "360F040E-D4C4-42DC-B687-262F4E28B0BD",
    CustomReferenceTypeId: "DF52BB58-F895-4C7F-B0C1-5D3C5737CC3E",
    StatusreportingReferenceTypeId: "244F513B-214B-4919-A0B4-766EE5FFF6BB",
    FoodOrderReferenceTypeId: "B367553E-79BE-4E37-8D3A-8906793BA0A8",
    EmergencyContactsReferenceTypeId: "FBDE7023-69A9-4400-8852-81B6AD86E2C5",
    DependentsReferenceTypeId: "40B1D262-C2AE-421D-96E3-9ABFC6383DF9",
    JobDetailsReferenceTypeId: "CC4826BF-5E8E-472C-A44F-F8DB6BE32593",
    BankDetailsReferenceTypeId: "A593FBE8-DD0A-4B0C-BAC9-79D03BB173A8",
    LanguageReferenceTypeId: "5234405A-A2FC-40E9-ABC2-EDA24F4B8CC3",
    SkillDetailsReferenceTypeId: "D9E47257-0C4B-4A74-95B5-69FD9CA3C344",
    ImmigrationReferenceTypeId: "563D8A1B-5C33-43C9-8923-8A6982FE2AE9",
    BadgeReferenceTypeId: "86BAB18A-95F0-4B22-9544-6887141E1D2A",
    PersonalDetailsReferenceTypeId: "B3A25B57-9451-426F-92BE-37E44DAC7251",
    EducationReferenceTypeId: "22DC965A-F3B9-4FCE-A093-942454A5D552",
    SalaryReferenceTypeId: "6EE25290-8D7A-49A1-9DA7-99BB1555F473",
    LicenceReferenceTypeId: "7C246F5A-12B3-4938-8208-AD572044CD48",
    WorkexperienceReferenceTypeId: "7F65B187-8035-4966-B425-D4B29D24AB2D",
    MembershipReferenceTypeId: "4AA9C448-A227-4C93-AF08-EDD967494669",
    ContractReferenceTypeId: "99F52614-3394-44FE-8C7F-F308B00E472D",
    LeaveReferenceTypeId: "e1f5d8ad-b150-4aaa-b78b-362662708e4d",
    TestSuiteCaseReferenceTypeId: "FFDFBE28-D3D9-49F9-9018-50E02D9C8F5B",
    TestSuiteStepDescriptionReferenceTypeId: "225BEB5C-1A53-40BB-A29B-B03BE3FA2779",
    TestSuiteStepExpectedReferenceTypeId: "3A3E185B-BD74-4DB6-86BC-677EB9AB1609",
    TestRunStatusCommentReferenceTypeId: "37EF5578-77AA-4A44-AB1E-BE76B585B2CE",
    TestRunAssigneeCommentReferenceTypeId: "E6A6B453-3D12-4F24-894F-E923FFB1C154",
    TestRunActualResultReferenceTypeId: "F86D67E1-D351-4A76-9FDD-06D1A9D84181",
    TestSuiteCaseMissionReferenceTypeId: "77F086EA-E23F-414D-AD14-D4725CEF36C2",
    TestSuiteCaseGoalReferenceTypeId: "CFB83453-60DD-4EB5-9818-95CDB3478AC5",
    TestSuiteCasePreconditionReferenceTypeId: "ED61D300-9A7C-450F-8942-2444DACEAD0F",
    TestSuiteTextDescriptionReferenceTypeId: "4232A177-164E-456C-B427-7BDEED92DA1D",
    TestSuiteTextExpectedReferenceTypeId: "6520F42D-DA2E-40E2-BAFA-D5EE4D37F4A3",
    ContactDetailsReferenceTypeId: "257E4D44-653F-453F-A957-1242C1ECDDD1",
    ExpenseReferenceTypeId: "B7E64259-2F29-4006-A997-13F94CE73B10",
    MasterContractReferenceTypeId: "F62846D0-3BF5-4D9C-9A56-B5CBEAEE7D5D",
    MasterBillOfEntryDraftReferenceTypeId: "A2875520-A4B5-4483-8761-BA8F2B1594FE",
    MasterBillOfEntryConfirmReferenceTypeId: "5DD38C29-AD68-4F07-B3AF-EB20F236D2DF",
    TaskStatusIdForDone: "FF7CAC88-864C-426E-B52B-DFB5CA1AAC76",
    CompanyStructureReferenceTypeId: '5CDE441F-818A-4EEC-BA45-AF3A636C815D',
    DocumentStoreRefrenceTypeId:'2039EE64-BB6E-4757-9E33-55521DC7CC46',
    MissingFeaturesGoalId: "7813E1DB-4610-4567-B2B6-D12E67FE274E",
    FeedbackBugsGoalId: "C934BC33-037B-452D-B6BA-01AC55345D52",
    SalaryLogReferenceTypeId: "AB672B97-2B44-4B6E-A4B6-FA051629CA0C",
    Q88ReferenceTypeId: "88944C8E-97F3-4736-935F-4A0530E39876",
    ClientSettingsReferenceTypeId : "B79A8DD7-A83C-45D3-9365-18503A07B3BF",
    ClientStampReferenceTypeId : '26D4C6C2-B698-4D79-8A52-0014E9045D60',
    FailedStatusShortName: "Failed",
    ProjectNameMaxLength250: 100,
    DescriptionLength: 250,
    MaxLength: 50,
    Length: 3,
    NameLength: 100,
    DescriptionIdealLengh: 800,
    IdealTimeLength: 600,
    announcementMaxLenght: 600,
    CommentsMaxLength: 800,
    UserStoryNameMaxLength: 800,
    WorkflowId: "b7a0a6e4-fa8f-4600-894d-0c66d89456d9",
    WorkflowType1Id: "0361770a-3f6d-4c86-ac7d-e2fa0de428ca",
    WorkflowType2Id: "93bb9e02-41d2-4402-b53d-ff919217072b",
    ValidationForAssigneeReplanType: "Need to select replan type for assignee",
    ValidationForEstimatedTimeReplanType: "Need to select replan type for estimated time",
    ValidationForDeadlineDateReplanType: "Need to select replan type for deadline date",
    ValidationForUserStoryStatusReplanType: "Need to select replan type for user story status",
    ValidationForDependencyOwnerReplanType: "Need to select replan type for dependency owner",
    UserStoryReplanTypeIdForAssignee: "4B285F45-C06D-44D5-BC7E-E3CA3F02B179",
    UserStoryReplanTypeIdForEstimatedTime: "DE88FF80-B0A0-4399-A933-5B2B948329ED",
    UserStoryReplanTypeIdForEstimatedTimeInSP: "6E256158-9366-4221-8534-F8A90AE7E4F3",
    UserStoryReplanTypeIdForDependancy: "0ED76463-B136-447F-895D-B5AD258EF481",
    UserStoryReplanTypeIdForDeadlineDate: "F31341B2-7F08-4BDD-AD1B-7DC6B3824593",
    UserStoryReplanTypeIdForUserStory: "F116F495-8E21-4F8F-A7B9-EE1E82E5B1D9",
    UserStoryStatusIdForNotStarted: "67260E91-CDEF-41D0-AEBC-C48FD4DE814D",
    UserStoryStatusIdForInProgress: "e1418ce8-a51b-4de5-aff3-42f8a588e3ae",
    UserStoryStatusIdForQAApproved: "b3b17186-6d07-4416-878d-f78a73a753fc",
    UserStoryStatusIdForSignedOff: "d348204e-a7d4-40c1-a5ad-7a667d8f4216",
    UserStoryStatusIdForCompleted: "7503dace-d75a-4df1-b687-64334263b908",
    UserStoryStatusIdForVerified: "C6E85DA3-649B-45FF-83B0-3C127BDD7712",
    UserStoryStatusIdForNew: "A50D34C9-F1C5-41B3-A9B9-63759FA3446F",
    UserStoryStatusIdForBlocked: "4B959CA8-1B72-45C0-9199-1B274B099860",
    BoardTypeUiIdForSuperagile: "D0C55A82-303C-4976-8884-026441BA75BF",
    BoardTypeUiIdForKanban: "2F4A6A4F-D04A-42CA-9E87-C4FF95747288",
    BoardTypeuiIdForKanbanBugs: "E3F924E2-9858-4B8D-BB30-16C64860BBD8",
    BoardTypeIdForAPI: "9b5f4791-684b-4caa-979b-3ecd8b3629c3",
    BoardTypeIdForKanbanBugs: "f28643ca-9f23-42e0-b51e-03f82a99a281",
    UserStoryStatusNameFotNotStarted: "Not Started",
    logTimeOptionForSetTo: "e4155596-282f-40ee-bf83-7e996454ae66",
    logTimeOptionForReducedBy: "60aa43ab-fd07-4654-a0e1-f1572c1e79de",
    logTimeOptionForExistingHours: "8008e5e4-9060-41af-80ec-bcb5baf7c22c",
    UserStoryTypeIdForUserStory: "6C32EE90-F5C4-4081-94B3-8143A4C4847D",
    UserStoryTypeIdForBug: "16E881A4-9C6D-4021-AA2A-E84C05FB608A",
    AdhocWorkflowId: "89E017F7-065B-40A9-A0CC-8066A2E53CD4",
    CaseViewFieldName: "TestCaseViewed",
    CaseViewConfigurationId: "94113d41-8034-4320-94c0-7752b3e663c6",
    ExploratorySession: "Exploratory Session",
    TestCaseSteps: "Test Case (Steps)",
    TestCaseText: "Test Case (Text)",
    TestCaseDefaultType: "Other",
    TestCaseDefaultPriority: "Medium",
    TestCaseDefaultAutomation: "None",
    Projects: "projects",
    SectionNotEditable: "notedit",
    SuccessMessageForUserStory: "USERSTORY.USERSTORYADDEDSUCCESSFULLY",
    SuccessMessageForBug: "USERSTORY.BUGADDEDSUCCESSFULLY",
    SuccessMessageForBugEdit: "USERSTORY.BUGEDITSUCCESSFULLY",
    SuccessMessageForUserStoryEdit: "USERSTORY.USERSTORYUPDATEDSUCCESSFULLY",
    SuccessMessageForUserStoryPark: "USERSTORY.USERSTORYPARKEDSUCCESSFULLY",
    SuccessMessageForUserStoryArchive: "USERSTORY.USERSTORYARCHIVEDSUCCESSFULLY",
    SuccessMessageForUserStoryResume: "USERSTORY.USERSTORYRESUMEDSUCCESSFULLY",
    SuccessMessageForUserStoryUnArchive: "USERSTORY.USERSTORYUNARCHIVEDSUCCESSFULLY",
    SuccessMessageForUserStoryStatusChange: "User story status changed successfully",
    SuccessMessageForMultipleUserStories: "USERSTORY.MULTIPLEUSERSTORIESADDEDSUCCESSFULLY",
    SuccessMessageForMultipleUserStoriesUpdate: "USERSTORY.MULTIPLEUSERSTORIESUPDATEDSUCCESSFULLY",
    ArchivedSuccessFully: "USERSTORY.ARCHIVEDSUCCESSFULLY",
    SuccessMessageForUserStoryUpdatedGoal: "USERSTORY.USERSTORYGOALUPDATEDSUCCESSFULLY",
    SuccessMessageForUserStoryReplan: "USERSTORY.USERSTORYREPLANNEDSUCCESSFULLY",
    SuccessMessageForGoal: "GOAL.GOALCREATEDSUCCESSFULLY",
    SuccessMessageForGoalEdit: "GOAL.GOALUPDATEDSUCCESSFULLY",
    SuccessMessageForGoalPark: "GOAL.GOALPARKEDSUCCESSFULLY",
    SuccessMessageForGoalArchive: "GOAL.SUCCESSFULARCHIVE",
    SuccessMessageForGoalResume: "GOAL.GOALRESUMEDSUCCESSFULLY",
    SuccessMessageForGoalUnArchive: "GOAL.GOALUNARCHIVEDSUCCESSFULLY",
    SuccessMessageForGoalApproved: "GOAL.GOALAPPROVEDSUCCESSFULLY",
    SuccessMessageForGoalReplan: "GOAL.GOALREPLANNEDSUCCESSFULLY",
    SuccessMessageForProjectArchive: "PROJECTS.PROJECTARCHIVEDSUCCESSFULLY",
    SuccessMessageForProjectUnArchive: "PROJECTS.PROJECTUNARCHIVEDSUCCESSFULLY",
    SuccessMessageForProjectCreate: "PROJECTS.PROJECTCREATEDSUCCESSFULLY",
    SuccessMessageForProjectUpdate: "PROJECTS.PROJECTUPDATEDSUCCESSFULLY",
    SuccessMessageForProjectMember: "MEMBER.PROJECTMEMBERCREATEDSUCCESSFULLY",
    SuccessMessageForProjectMemberUpdate: "MEMBER.PROJECTMEMBERUPDATEDSUCCESSFULLY",
    SuccessMessageForProjectMemberDeletion: "MEMBER.MEMBERDELETEDSUCCESSFULLY",
    SuccessMessageForProjectFeatureCreate: "COMPONENT.COMPONENTCREATEDSUCCESSFULLY",
    SuccessMessageForProjectFeatureUpdate: "COMPONENT.COMPONENTUPDATEDSUCCESSFULLY",
    SuccessMessageForProjectFeatureDelete: "COMPONENT.COMPONENTDELETEDSUCCESSFULLY",
    SuccessMessageForProjectFeatureUnArchive: "COMPONENT.COMPONENTUNARCHIVEDSUCCESSFULLY",
    UserStoriesCountForGoalApproval: "GOAL.PLEASEADDATLEASTONEUSERSTORY",
    ErrorMessageForUserStoryStatus: "USERSTORY.PLEASESELECTASSIGNEEFORANUSERSTORY",
    ErrorMessageForDependencyPerson: "USERSTORY.PLEASESELECTDEPENDENCYPERSONFORANUSERSTORY",
    ErrorMessageForLogTime: "Please update status for user story",
    WarningMessageForEmptyClient: "BILLINGMANAGEMENT.EMPTYCLIENT",
    WarningMessageForEmptyNumber: "BILLINGMANAGEMENT.EMPTYINVOICENUMBER",
    WarningMessageForEstimateEmptyNumber: "BILLINGMANAGEMENT.EMPTYESTIMATENUMBER",
    WarningMessageForEmptyTask: "BILLINGMANAGEMENT.EMPTYINVOICETASK",
    WarningMessageForEmptyItem: "BILLINGMANAGEMENT.EMPTYINVOICEITEM",
    WarningMessageForTaskExceed: "BILLINGMANAGEMENT.TASKDESEXCEED",
    WarningMessageForItemExceed: "BILLINGMANAGEMENT.ITEMDESEXCEED",
    WarningMessageForTaskTitleExceed: "BILLINGMANAGEMENT.TASKTITLEEXCEED",
    WarningMessageForItemTitleExceed: "BILLINGMANAGEMENT.ITEMTITLEEXCEED",
    WarningMessageForInvoiceTitleExceed: "BILLINGMANAGEMENT.INVOICETITLEEXCEED",
    WarningMessageForInvoiceNumberExceed: "BILLINGMANAGEMENT.INVOICENUMBEREXCEED",
    WarningMessageForInvoicePONumberExceed: "BILLINGMANAGEMENT.INVOICEPONUMBEREXCEED",
    WarningMessageForInvoiceNotesExceed: "BILLINGMANAGEMENT.INVOICENOTESEXCEED",
    WarningMessageForInvoiceTermsExceed: "BILLINGMANAGEMENT.INVOICETERMSEXCEED",
    WarningMessageForInvoiceAmountExceed: "BILLINGMANAGEMENT.INVOICEAMOUNTEXCEED",
    WarningMessageForDiscountExceed: "BILLINGMANAGEMENT.DISCOUNTAMOUNTEXCEED",
    WarningMessageForEstimateAmountExceed: "BILLINGMANAGEMENT.ESTIMATEAMOUNTEXCEED",
    WarningMessageForInvoiceToBeUnArchived: "BILLINGMANAGEMENT.INVOICETOBEUNARCHIVED",
    WarningMessageForEmptyEstimateNumber: "BILLINGMANAGEMENT.EMPTYESTIMATENUMBER",
    WarningMessageForEmptyEstimateTask: "BILLINGMANAGEMENT.EMPTYESTIMATETASK",
    WarningMessageForEmptyEstimateItem: "BILLINGMANAGEMENT.EMPTYESTIMATEITEM",
    WarningMessageForEstimateTitleExceed: "BILLINGMANAGEMENT.ESTIMATETITLEEXCEED",
    WarningMessageForEstimateNumberExceed: "BILLINGMANAGEMENT.ESTIMATENUMBEREXCEED",
    WarningMessageForEstimatePONumberExceed: "BILLINGMANAGEMENT.ESTIMATEPONUMBEREXCEED",
    WarningMessageForEstimateNotesExceed: "BILLINGMANAGEMENT.ESTIMATENOTESEXCEED",
    WarningMessageForEstimateTermsExceed: "BILLINGMANAGEMENT.ESTIMATETERMSEXCEED",
    WarningMessageForEstimateToBeUnArchived: "BILLINGMANAGEMENT.ESTIMATETOBEUNARCHIVED",
    InvoiceMailSentSuccessfully: "BILLINGMANAGEMENT.MAILSENT",
    MultipleImagesNotAllowed: "BILLINGMANAGEMENT.MULTIPLEIMAGESNOTALLOWED",
    // Asset related constant variables
    SuccessMessageForAssetCreated: "ASSETS.ASSETCREATEDSUCCESSFULLY",
    SuccessMessageForAssetArchived: "ASSETS.ASSETARCHIVEDSUCCESSFULLY",
    SuccessMessageForAssetUpdated: "ASSETS.ASSETUPDATEDSUCCESSFULLY",
    SuccessMessageForLocationCreated: "LOCATION.CREATEDSUCCESSFULLY",
    SuccessMessageForLocationArchived: "LOCATION.DELETEDSUCCESSFULLY",
    SuccessMessageForLocationUpdated: "LOCATION.UPDATEDSUCCESSFULLY",
    SuccessMessageForProductDetailsCreated: "PRODUCTDETAILS.PRODUCTDETAILSCREATEDSUCCESSFULLY",
    SuccessMessageForProductDetailsDeleted: "PRODUCTDETAILS.PRODUCTDETAILSDELETEDSUCCESSFULLY",
    SuccessMessageForProductDetailsUpdated: "PRODUCTDETAILS.PRODUCTDETAILSUPDATEDSUCCESSFULLY",
    LocationWithSeatCode: "LOCATION.LOCATIONWITHSEATCODE",
    ProductDetailsWithManufactureCode: "Product details with manufacture code",
    SuccessMessageForCreated: "CREATEDSUCCESSFULLY",
    SuccessMessageForCredited: "CREDITEDSUCCESSFULLY",
    SuccessMessageForArchived: "ARCHIVEDSUCCESSFULLY",
    SuccessMessageForUpdated: "UPDATEDSUCCESSFULLY",
    FoodOrderText: "HRMANAGAMENT.FOODORDERMESSAGE",
    Rejectorder: "HRMANAGAMENT.STATUSCHANGED",
    SuccessMessageForProductCreated: "PRODUCT.PRODUCTCREATEDSUCCESSFULLY",
    SuccessMessageForProductArchived: "PRODUCT.PRODUCTARCHIVEDSUCCESSFULLY",
    SuccessMessageForProductUpdated: "PRODUCT.PRODUCTUPDATEDSUCCESSFULLY",
    SuccessMessageForSupplierCreated: "SUPPLIER.SUPPLIERCREATEDSUCCESSFULLY",
    SuccessMessageForSupplierArchived: "SUPPLIER.SUPPLIERARCHIVEDSUCCESSFULLY",
    SuccessMessageForSupplierUpdated: "SUPPLIER.SUPPLIERUPDATEDSUCCESSFULLY",
    SuccessMessageForUserCreated: "HRMANAGAMENT.USERCREATEDSUCCESSFULLY",
    SuccessMessageForUserArchived: "HRMANAGAMENT.USERARCHIVEDSUCCESSFULLY",
    SuccessMessageForUserUpdated: "HRMANAGAMENT.USERUPDATEDSUCCESSFULLY",
    SuccessMessageForPasswordCreated: "HRMANAGAMENT.PASSWORDCREATEDSUCCESSFULLY",
    SuccessMessageForPasswordChanged: "HRMANAGAMENT.PASSWORDCHANGEDSUCCESSFULLY",
    SuccessMessageForPurchaseCanteenItem: "CANTEEN.PURCHASEDITEMSINCANTEENSUCCESSFULLY",
    CanteenFoodItem: "CANTEEN.FOODITEM",
    PurchaseItem: "CANTEEN.PURCHASEITEM",
    SuccessMessageForRelationshipDetailsCreated: "Relationship created successfully",
    SuccessMessageForRelationshipDetailsArchived: "Relationship archived successfully",
    SuccessMessageForRelationshipDetailsUpdated: "Relationship updated successfully",
    SuccessMessageForEmployeeContactDetailsCreated: "HRMANAGAMENT.EMPLOYEECONTACTDETAILSCREATEDSUCCESSFULLY",
    SuccessMessageForEmployeeContactDetailsUpdated: "HRMANAGAMENT.EMPLOYEECONTACTDETAILSUPDATEDSUCCESSFULLY",
    WorkflowType3Id: "ab71a18f-4a69-4bc5-88ae-7598bf3ab695",
    WorkflowType4Id: "cc2fa695-aaf0-44f0-9b22-b03fa0d7fe63",
    // Asset related constant variables
    SuccessMessageForContactDetailsCreated: "HRMANAGAMENT.CONTACTDETAILSCREATEDSUCCESSFULLY",
    SuccessMessageForContactDetailsUpdated: "HRMANAGAMENT.CONTACTDETAILSUPDATEDSUCCESSFULLY",
    SuccessMessageForEducationDetailsDeleted: "EMPLOYEEEDUCATIONDETAILS.SUCCESSMESSAGEFORDELETED",
    SuccessMessageForEducationDetailsUpdated: "EMPLOYEEEDUCATIONDETAILS.SUCCESSMESSAGEFORUPDATED",
    SuccessMessageForEducationDetailsCreated: "EMPLOYEEEDUCATIONDETAILS.SUCCESSMESSAGEFORCREATED",
    SuccessMessageForWorkExperienceCreated: "HRMANAGAMENT.WORKEXPERIENCEDETAILSCREATEDSUCCESSFULLY",
    SuccessMessageForWorkExperienceDeleted: "HRMANAGAMENT.WORKEXPERIENCEDETAILSDELETEDSUCCESSFULLY",
    SuccessMessageForWorkExperienceUpdated: "HRMANAGAMENT.WORKEXPERIENCEDETAILSUPDATEDSUCCESSFULLY",
    SuccessMessageForMembershipDetailsDeleted: "EMPLOYEEMEMBERSHIP.SUCCESSMESSAGEFORDELETED",
    SuccessMessageForMembershipDetailsUpdated: "EMPLOYEEMEMBERSHIP.SUCCESSMESSAGEFORUPDATED",
    SuccessMessageForMembershipDetailsCreated: "EMPLOYEEMEMBERSHIP.SUCCESSMESSAGEFORCREATED",
    SuccessMessageForImmigrationDetailsCreated: "EMPLOYEEIMMIGRATIONDETAILS.SUCCESSMESSAGECREATED",
    SuccessMessageForImmigrationDeleted: "EMPLOYEEIMMIGRATIONDETAILS.SUCCESSMESSAGEDELETED",
    SuccessMessageForImmigrationDetailsUpdated: "EMPLOYEEIMMIGRATIONDETAILS.SUCCESSMESSAGEUPDATED",
    Visa: "Visa",
    Passport: "Passport",
    CreatedDate: "CreatedDate",
    SuccessMessageForSalaryDetailsCreated: "HRMANAGAMENT.SALARYDETAILSCREATEDSUCCESSFULLY",
    SuccessMessageForSalaryDetailsDeleted: "HRMANAGAMENT.SALARYDETAILSDELETEDSUCCESSFULLY",
    SuccessMessageForSalaryDetailsUpdated: "HRMANAGAMENT.SALARYDETAILSUPDATEDSUCCESSFULLY",
    SuccessMessageForBankDetailsCreated: "HRMANAGAMENT.BANKDETAILSCREATEDSUCCESSFULLY",
    SuccessMessageForBankDetailsDeleted: "HRMANAGAMENT.BANKDETAILSDELETEDSUCCESSFULLY",
    SuccessMessageForBankDetailsUpdated: "HRMANAGAMENT.BANKDETAILSUPDATEDSUCCESSFULLY",
    DefaultLoanDocTemplate: "https://bviewstorage.blob.core.windows.net/96da99f6-1fda-4013-a0d2-8583d3bcc431/hrm/bc94a162-dd15-43fc-8425-255761a9ffb8/employeeloan-c7185755-cd02-4669-ab5c-76999d6fda4c.doc",
    DefaultStampDocument : '',
    DefaultPaySlipLogo: "https://bviewstorage.blob.core.windows.net/6671cd0d-5b91-4044-bdcc-e1f201c086c5/projects/d72d1c2f-dfbe-4d48-9605-cd3b7e38ed17/Main-Logo-9277cc4b-0c1f-4093-a917-1a65e874b3c9.png",

    // Time Punch constant variables
    Start: "START",
    Finish: "FINISH",
    Lunch: "LUNCH",
    LunchStart: "LUNCHSTART",
    LunchEnd: "LUNCHEND",
    Break: "BREAK",
    BreakIn: "BREAKIN",
    BreakOut: "BREAKOUT",
    // Feed time sheet
    TimeSheetSavedSuccessfully: "FEEDTIMESHEET.TIMESHEETSAVEDSUCCESSFULLY",
    PermissionReasonSavedSuccessfully: "FEEDTIMESHEET.PERMISSIONREASONSAVEDSUCCESSFULLY",
    SuccessMessageForSkillCreated: "HRMANAGAMENT.SKILLSCREATEDSUCCESSFULLY",
    SuccessMessageForSkillDeleted: "HRMANAGAMENT.SKILLSDELETEDSUCCESSFULLY",
    SuccessMessageForSkillUpdated: "HRMANAGAMENT.SKILLSUPDATEDSUCCESSFULLY",
    SuccessMessageForReportCreated: "REPORTTO.REPORTSCREATEDSUCCESSFULLY",
    SuccessMessageForReportDeleted: "REPORTTO.REPORTDELETEDSUCCESSFULLY",
    SuccessMessageForReportUpdated: "REPORTTO.REPORTUPDATEDSUCCESSFULLY",
    SuccessMessageForEmergencyContactCreated: "HRMANAGAMENT.EMERGENCYCONTACTCREATEDSUCCESSFULLY",
    SuccessMessageForEmergencyContactDeleted: "HRMANAGAMENT.EMERGENCYCONTACTDELETEDSUCCESSFULLY",
    SuccessMessageForEmergencyContactUpdated: "HRMANAGAMENT.EMERGENCYCONTACTUPDATEDSUCCESSFULLY",
    SuccessMessageForMilestoneAdded: "TESTMANAGEMENT.MILESTONEADDEDSUCCESSFULLY",
    SuccessMessageForMilestoneEdited: "TESTMANAGEMENT.MILESTONEEDITEDSUCCESSFULLY",
    SuccessMessageForMilestoneDeleted: "TESTMANAGEMENT.MILESTONEDELETEDSUCCESSFULLY",
    SuccessMessageForMilestoneCreated: "TESTMANAGEMENT.MILESTONECREATEDSUCCESSFULLY",
    SuccessMessageForTestRunEdited: "TESTMANAGEMENT.TESTRUNEDITEDSUCCESSFULLY",
    SuccessMessageForTestRunCreated: "TESTMANAGEMENT.TESTRUNCREATEDSUCCESSFULLY",
    SuccessMessageForTestRunDeleted: "TESTMANAGEMENT.TESTRUNDELETEDSUCCESSFULLY",
    SuccessMessageForTestCaseEdited: "TESTMANAGEMENT.TESTCASEEDITEDSUCCESSFULLY",
    SuccessMessageForTestCaseCreated: "TESTMANAGEMENT.TESTCASECREATEDSUCCESSFULLY",
    SuccessMessageForCaseTitleCreated: "TESTMANAGEMENT.CASETITLECREATEDSUCCESSFULLY",
    SuccessMessageForCaseTitleEdited: "TESTMANAGEMENT.CASETITLEEDITEDSUCCESSFULLY",
    SuccessMessageForCaseTitleDeleted: "TESTMANAGEMENT.CASETITLEDELETEDSUCCESSFULLY",
    ScenarioCreatedOrUpdated: "TESTMANAGEMENT.SCENARIOCREATEDORUPDATED",
    RunCreatedOrUpdated: "TESTMANAGEMENT.RUNCREATEDORUPDATED",
    VersionCreatedOrUpdated: "TESTMANAGEMENT.VERSIONCREATEDORUPDATED",
    ReportCreatedOrUpdated: "TESTMANAGEMENT.TESTREPORTCREATEDORUPDATED",
    ScenarioSectionCreatedOrUpdated: "TESTMANAGEMENT.SCENARIOSECTIONCREATEDORUPDATED",
    DuplicateDashboard: "WIDGETS.DUPLICATEDASHBOARD",
    TestRunDeleted: "TESTMANAGEMENT.TESTRUNDELETED",
    SuccessMessageForCaseAssignToUpdated: "TESTMANAGEMENT.ASSIGNTOUPDATEDSUCCESSFULLY",
    SuccessMessageForStatusUpdated: "TESTMANAGEMENT.UPDATEDSUCCESSFULLY",
    SuccessMessageForTestSuiteDeleted: "TESTMANAGEMENT.TESTSUITEDELETEDSUCCESSFULLY",
    SuccessMessageForTestSuiteEdited: "TESTMANAGEMENT.TESTSUITEEDITEDSUCCESSFULLY",
    SuccessMessageFortestSuiteCreated: "TESTMANAGEMENT.TESTSUITECREATEDSUCCESSFULLY",
    SuccessMessageForTestSuiteSectionDeleted: "TESTMANAGEMENT.SECTIONDELETEDSUCCESSFULLY",
    SuccessMessageForTestSuiteSectionEdited: "TESTMANAGEMENT.SECTIONEDITEDSUCCESSFULLY",
    SuccessMessageForTestSuiteSectionCreated: "TESTMANAGEMENT.SECTIONCREATEDSUCCESSFULLY",
    SuccessMessageForTestCaseUpdated: "TESTMANAGEMENT.UPDATEDSUCCESSFULLY",
    SuccessMessageForReportShared: "TESTMANAGEMENT.REPORTSHAREDSUCCESSFULLY",
    SuccessMessageForExportShared: "TESTMANAGEMENT.EXPORTSHAREDSUCCESSFULLY",
    ErrorMessageForOpeningArchivedProject: "TESTMANAGEMENT.ERROROPENINGARCHIVEDPROJECT",
    ErrorMessageForExceedingTestCaseHours: "TESTMANAGEMENT.TIMEREACHEDMAXIMUM",
    WarningMessageForExceedingTimeConfiguration: "TIMECONFIGURATIONSETTINGS.TIMEREACHEDMAXIMUM",
    WarningMessageForWrongTimeConfiguration: "TIMECONFIGURATIONSETTINGS.TIMEWRONG",
    TestCaseNotValid: "TESTMANAGEMENT.THISISNOTAVALIDTESTCASE",
    TestCaseReport: "TESTMANAGEMENT.TESTCASEREPORT",
    XAxisNameForSplitBarReport: "TESTMANAGEMENT.DAYS",
    YAxisNameForSplitBarReport: "TESTMANAGEMENT.ORIGINALSPENTTIME",
    TestCaseUpdated: "TESTMANAGEMENT.TESTCASEUPDATED",
    TestSuiteUpdated: "TESTMANAGEMENT.TESTSUITEUPDATED",
    TestRunUpdated: "TESTMANAGEMENT.TESTRUNUPDATED",
    TestCaseStatusUpdated: "TESTMANAGEMENT.TESTCASESTATUSUPDATED",
    BugUpdated: "TESTMANAGEMENT.BUGUPDATED",
    BugCreatedToday: "TESTMANAGEMENT.BUGCREATEDTODAY",
    MilestoneUpdated: "TESTMANAGEMENT.MILESTONEUPDATED",
    ReportUpdated: "TESTMANAGEMENT.REPORTUPDATED",
    TestCaseViewed: "TESTMANAGEMENT.TESTCASEVIEWED",
    PleaseFillTestCaseTitle: "TESTMANAGEMENT.PLEASEFILLTESTCASETITLE",
    TestCaseTitleShouldNotExceed500Characters: "TESTMANAGEMENT.TESTCASETITLENOTEXCEED500CHARACTERS",
    TestSuiteSectionUpdated: "TESTMANAGEMENT.TESTSUITESECTIONUPDATED",
    success: "SUCCESS",
    SelectAtleastOneCase: "TESTMANAGEMENT.SELECTATLEASTONECASE",
    Month: "Month",
    REQUIREDPRODUCTIVITY: "Required productivity",
    EXISTINGPRODUCTIVITY: "Existing productivity",
    WEEK: "PRODUCTIVITYDASHBOARD.WEEK",
    MONTH: "PRODUCTIVITYDASHBOARD.MONTH",
    DefaultTime: "12:00",
    DefaultDateFilterForReport: "Last7Days",
    // workflowstatus
    Addtransition: "WORKFLOWTRANSITION.ADDNEWTRANSITION",
    Worktransition: "WORKFLOWTRANSITION.ADDNEWSTRANSITION",
    Toasterdeleted: "WORKFLOWTRANSITION.TOASTERDELETED",
    Toasteradded: "WORKFLOWTRANSITION.TOASTERADDED",
    Updated: "WORKFLOWTRANSITION.TOASTERUPDATED",
    ToasterCreated: "WORKFLOWTRANSITION.TOASTERCREATED",
    Status: "WORKFLOWTRANSITION.STATUS",
    FlowCreated: "WORKFLOWTRANSITION.WORKFLOWCREATED",
    // boardtype
    Created: "BOARDTYPE.CREATEBOARDTYPE",
    Add: "BOARDTYPE.ADDBOARDTYPE",
    Plus: "BOARDTYPE.PLUS",
    Toaster: "BOARDTYPE.TOASTERCREATED",
    ToasterUpdated: "BOARDTYPE.TOASTERUPDATED",
    Edit: "BOARDTYPE.EDIT",
    Update: "BOARDTYPE.UPDATE",
    BoardTypeCreated: "BOARDTYPE.CREATED",
    // permission
    AddPermission: "PERMISSION.ADD",
    PlusPermission: "PERMISSION.PLUS",
    PermissionCreated: "PERMISSION.CREATEPERMISSION",
    UpdatedPermission: "PERMISSION.UPDATE",
    Permission: "PERMISSION.UPDATEPERMISSION",
    CreatedPermission: "PERMISSION.TOASTERCREATED",
    PermissionUpdated: "PERMISSION.PERMISSIONUPDATED",
    Ok: "PERMISSION.OK",

    // designation
    Editdesignation: "DESIGNATION.EDITDESIGNATIONTITLE",

    // activity tracker
    Apps: "8119b40c-834c-4721-80e0-0c8257c3e977",
    Urls: "468e34ec-53d6-444a-9434-7bc185c4cb6d",
    off: "d823d2eb-d592-4957-867c-a204c633eac7",
    AppsUrls: "d1376714-5db6-4d14-8e11-b5aac2c7c662",
    AppUrlsDetailed: "83824c7a-eec0-4f64-a1ee-d9967aa59536",

    ProfileImageUpdatedSuccessfully: "MYPROFILE.PROFILEIMAGEUPDATEDSUCCESSFULLY",
    ProfileImageRemovedSuccessfully: "MYPROFILE.PROFILEIMAGEREMOVEDSUCCESSFULLY",

    // HRManagement
    ContractDetailsCreatedSuccessfully: "HRMANAGAMENT.CONTRACTDETAILSCREATEDSUCCESSFULLY",
    ContractDetailsUpdatedSuccessfully: "HRMANAGAMENT.CONTRACTDETAILSUPDATEDSUCCESSFULLY",
    ContractDetailsDeletedSuccessfully: "HRMANAGAMENT.CONTRACTDETAILSDELETEDSUCCESSFULLY",
    DependentDetailsCreatedSuccessfully: "HRMANAGAMENT.DEPENDENTDETAILSCREATEDSUCCESSFULLY",
    DependentDetailsUpdatedSuccessfully: "HRMANAGAMENT.DEPENDENTDETAILSUPDATEDSUCCESSFULLY",
    DependentDetailsDeletedSuccessfully: "HRMANAGAMENT.DEPENDENTDETAILSDELETEDSUCCESSFULLY",
    JobDetailsCreatedSuccessfully: "HRMANAGAMENT.JOBDETAILSCREATEDSUCCESSFULLY",
    JobDetailsUpdatedSuccessfully: "HRMANAGAMENT.JOBDETAILSUPDATEDSUCCESSFULLY",
    JobDetailsDeletedSuccessfully: "HRMANAGAMENT.JOBDETAILSDELETEDSUCCESSFULLY",
    LanguageDetailsCreatedSuccessfully: "HRMANAGAMENT.LANGUAGEDETAILSCREATEDSUCCESSFULLY",
    LanguageDetailsUpdatedSuccessfully: "HRMANAGAMENT.LANGUAGEDETAILSUPDATEDSUCCESSFULLY",
    LanguageDetailsDeletedSuccessfully: "HRMANAGAMENT.LANGUAGEDETAILSDELETEDSUCCESSFULLY",
    LicenceDetailsCreatedSuccessfully: "HRMANAGAMENT.LICENCEDETAILSCREATEDSUCCESSFULLY",
    LicenceDetailsUpdatedSuccessfully: "HRMANAGAMENT.LICENCEDETAILSUPDATEDSUCCESSFULLY",
    LicenceDetailsDeletedSuccessfully: "HRMANAGAMENT.LICENCEDETAILSDELETEDSUCCESSFULLY",
    PersonalDetailsCreatedSuccessfully: "HRMANAGAMENT.PERSONALDETAILSCREATEDSUCCESSFULLY",
    PersonalDetailsUpdatedSuccessfully: "HRMANAGAMENT.PERSONALDETAILSUPDATEDSUCCESSFULLY",

    // Status Reporting
    Configuration: "STATUSREPORT.CONFIGURATION",
    StatusReportCreatedSuccessfully: "STATUSREPORT.CREATEDSUCCESSFULLY",
    StatusReportUpdatedSuccessfully: "STATUSREPORT.UPDATEDSUCCESSFULLY",
    StatusReportDeletedSuccessfully: "STATUSREPORT.DELETEDSUCCESSFULLY",
    StatusReportSubmission: "STATUSREPORT.STATUSREPORTSUBMISSION",
    FormDeletionMessage: "STATUSREPORT.FORMDELETIONMESSAGE",
    FormUpdationMessage: "STATUSREPORT.FORMUPDATIONMESSAGE",
    FormCreationMessage: "STATUSREPORT.FORMCREATIONMESSAGE",

    // clients
    CLIENTCREATEDSUCCESSFULLY: "CLIENTS.CLIENTCREATEDSUCCESSFULLY",
    CLIENTDETAILSUPDATEDSUCCESSFULLY: "CLIENTS.CLIENTDETAILSUPDATEDSUCCESSFULLY",
    SECONDARYCONTACTDETAILSADDEDSUCCESSFULLY: "CLIENTS.SECONDARYCONTACTDETAILSADDEDSUCCESSFULLY",
    SECONDARYCONTACTDETAILSUPDATEDSUCCESSFULLY: "CLIENTS.SECONDARYCONTACTDETAILSUPDATEDSUCCESSFULLY",
    ENTERSECONDARYCONTACTDETAILS: "CLIENTS.ENTERSECONDARYCONTACTDETAILS",
    UPDATESECONDARYCONTACTDETAILS: "CLIENTS.UPDATESECONDARYCONTACTDETAILS",
    ADDNEWCLIENT: "CLIENTS.ADDNEWCLIENT",
    EDITCLIENTDETAILS: "CLIENTS.EDITCLIENTDETAILS",
    CLIENTSARCHIVEDSUCCESSFULLY: "CLIENTS.CLIENTSARCHIVEDSUCCESSFULLY",
    CLIENTSUNARCHIVEDSUCCESSFULLY: "CLIENTS.CLIENTSUNARCHIVEDSUCCESSFULLY",
    SELECTCLIENTTOARCHIVE: "CLIENTS.SELECTCLIENTTOARCHIVE",

    SuccessMessageForFormSubmission: "GENERICFORM.APPLICATIONSUBMITTED",
    SuccessMessageForTimeLog: "USERSTORY.TIMELOGGEDSUCCESSFULLY",
    SuccessMessageForAutoTimeLog: "USERSTORY.AUTOTIMELOGGEDSUCCESSFULLY",
    SuccessMessageForAutoTimeLogCompleted: "USERSTORY.AUTOTIMELOGCOMPLETDSUCCESSFULLY",

    FolderCreatedSuccessfully: "DOCUMENTMANAGEMENT.FOLDERCREATEDSUCCESSFULLY",
    FolderDeletedSuccessfully: "DOCUMENTMANAGEMENT.FOLDERDELETEDSUCCESSFULLY",
    FolderUpdatedSuccessfully: "DOCUMENTMANAGEMENT.FOLDERUPDATEDSUCCESSFULLY",
    FileCreatedSuccessfully: "DOCUMENTMANAGEMENT.FILECREATEDSUCCESSFULLY",
    FileDeletedSuccessfully: "DOCUMENTMANAGEMENT.FILEDELETEDSUCCESSFULLY",
    FileUpdatedSuccessfully: "DOCUMENTMANAGEMENT.FILEUPDATEDSUCCESSFULLY",
    FileSizeShouldNotExceed: "DOCUMENTMANAGEMENT.FILESIZESHOULDNOTEXCEED",
    ThisFileTypeIsNotAllowed: "DOCUMENTMANAGEMENT.THISFILETYPEISNOTALLOWED",
    MultipleFilesNotAllowed: "DOCUMENTMANAGEMENT.MULTIPLEFILESNOTALLOWED",
    DocumentManagementRouteConstant: "documents",
    DragAndDropFilesHere: "DOCUMENTMANAGEMENT.DRAGANDDROPFILESHERE",
    AddReceiptsHere: "DOCUMENTMANAGEMENT.ADDRECEIPTSHERE",
    FileNameAlreadyExists: "DOCUMENTMANAGEMENT.FILENAMEALREADYEXISTS",

    LeaveTypeAddedSuccessfully: "LEAVETYPES.LEAVETYPEADDEDSUCCESSFULLY",
    LeaveTypeUpdatedSuccessfully: "LEAVETYPES.LEAVESTYPEUPDATEDSUCCESSFULLY",
    LeaveFrequencyAddedSuccessfully: "LEAVETYPES.LEAVEFREQUENCYADDEDSUCCESSFULLY",
    LeaveFrequencyUpdatedSuccessfully: "LEAVETYPES.LEAVEFREQUENCYUPDATEDSUCCESSFULLY",
    LeaveApplicabilityDetailsAddedSuccessfully: "LEAVETYPES.LEAVEAPPLICABILITYADDEDSUCCESSFULLY",
    LeaveApplicabilityDetailsUpdatedSuccessfully: "LEAVETYPES.LEAVEAPPLICABILITYUPDATEDSUCCESSFULLY",

    HOLIDAY: "LOGTIMEREPORT.HOLIDAY",
    WEEKOFF: "LOGTIMEREPORT.WEEKOFF",
    LOGTIMEGREATERTHANOREQUALTOSPENTTIME: "LOGTIMEREPORT.LOGTIMEGREATERTHANOREQUALTOSPENTTIME",
    LOGTIMELESSTHANSPENTTIME: "LOGTIMEREPORT.LOGTIMELESSTHANSPENTTIME",
    CASUALLEAVESICKLEAVE: "LOGTIMEREPORT.CASUALLEAVE/SICKLEAVE",
    FUTUREDAYSINACTIVE: "LOGTIMEREPORT.FUTUREDAYS/INACTIVE",
    WORKFROMHOMEONSITE: "LOGTIMEREPORT.WORKFROMHOME/ON-SITE",
    LEAVEWITHOUTINTIMATION: "LOGTIMEREPORT.LEAVEWITHOUTINTIMATION",
    FIRSTORSECONDHALFLEAVE: "LOGTIMEREPORT.FIRSTORSECONDHALFLEAVE",

    DashboardDuplicatedSuccessfully: "APP.DASHBOARDDUPLICATEDSUCCESSFULLY",

    // Logo details
    DefaultMainLogo: "https://bviewstorage.blob.core.windows.net/6671cd0d-5b91-4044-bdcc-e1f201c086c5/projects/d72d1c2f-dfbe-4d48-9605-cd3b7e38ed17/Main-Logo-9277cc4b-0c1f-4093-a917-1a65e874b3c9.png",
    DefaultMiniLogo: "https://bviewstorage.blob.core.windows.net/4afeb444-e826-4f95-ac41-2175e36a0c16/hrm/0b2921a9-e930-4013-9047-670b5352f308/Logo-favicon-6b9022d6-7175-4f55-b4da-d5b2e5c98d4e.png",
    DefaultLogoJpg: "https://bviewstorage.blob.core.windows.net/4afeb444-e826-4f95-ac41-2175e36a0c16/hrm/127133f1-4427-4149-9dd6-b02e0e036972/snovasybuisinesssuite-4b2eeef7-01ef-4ad8-9d24-a1d6c6cd4487.jpg",
    SuccessMessageForEmployeeRateSheetDeleted: "RATESHEET.RATESHEETDELETEDSUCCESFULLY",
    SuccessMessageForEmployeeRateSheetCreated: "RATESHEET.RATESHEETCREATEDSUCCESFULLY",
    SuccessMessageForEmployeeRateSheetUpdated: "RATESHEET.RATESHEETUPDATEDSUCCESFULLY",

    RosterMaxEmployee: "ROSTER.ROSTERMAXEMPLOYEE",
    RosterEmployeeCountMismatch: "ROSTER.ROSTEREMPLOYEECOUNTMISMATCH",
    RosterRecurringSchedule: "ROSTER.ROSTERRECCURRINGSCHEDULER",
    RosterEmployeeCountGreaterThanZero: "ROSTER.ROSTERMAXEMPLOYEE",
    RosterNoShiftllocated: "ROSTER.ROSTERNOSHIFTALLOCATED",
    RosterNameAlreadyAvailable: "ROSTER.ROSTERNAMEALREADYAVAILABLE",
    RosterEndTimeShouldBeValid: "ROSTER.ROSTERSHIFTTIMESHOULDBEVALID",
    RoterCantBeCreated: "ROSTER.ROSTERCANTBECREATED",
    RosterEmployeeRepeat: "ROSTER.ROSTEREMPLOYEEREPEAT",
    SuccessMessageForRosterPlanArchived: "ROSTER.ROSTERARCHIVEDSUCCESSFULLY",
    SuccessMessageForRosterPlanUnArchived: "ROSTER.ROSTERUNARCHIVEDSUCCESSFULLY",
    EmployeeTaxAllowanceProofsReferenceTypeId: 'F127D3A8-4BE6-40B8-93B3-9397FD830458',
    MaxInvestedAmountValue: 50000,
    ThisUserStoryIsArchived:"HISTORICALREPORT.ARCHIVEDUSERSTORY",
    ThisUserStoryIsParked:"HISTORICALREPORT.PARKEDUSERSTORY",
    //Audits
    SuccessMessageForAuditArchived: "AUDIT.ARCHIVED",
    SuccessMessageForAuditEdited: "AUDIT.EDITED",
    SuccessMessageForAuditCreated: "AUDIT.CREATED",
    SuccessMessageForAuditUnArchived: "AUDIT.UNARCHIVED",
    SuccessMessageForAuditDeleted: "AUDIT.DELETED",
    WarningMessageForTypeName: "AUDIT.PLEASEENTERQUESTIONTYPENAME",
    WarningMessageForTypeNameExceed: "AUDIT.QUESTIONTYPENAMEEXCEED150CHARACTERS",
    WarningMessageForOptionName: "AUDIT.OPTIONNAME",
    WarningMessageForOptionNameExceed: "AUDIT.OPTIONEXCEED150CHARACTERS",
    WarningMessageForOptionResult: "AUDIT.OPTIONRESULT",
    WarningMessageForOptionOrder: "AUDIT.OPTIONORDER",
    WarningMessageForOptionOrderEmpty: "AUDIT.OPTIONORDEREMPTY",
    WarningMessageForOptionScore: "AUDIT.OPTIONSCOREEMPTY",
    WarningMessageForOptionsExceed: "AUDIT.OPTIONSEXCEED",
    WarningMessageForOptionNameDuplicte: "AUDIT.OPTIONNAMEDUPLICATE",
    WarningMessageForResultError: "AUDIT.RESULTERROR",
    WarningMessageForResultMoreError: "AUDIT.RESULTMOREERROR",
    WarningMessageForSelectAtleastOneQuestion: "AUDIT.SELECTATLEASTONEQUESTION",
    WarningMessageForQuestionsCount: "AUDIT.DELETECATEGORYFORQUESTIONSCOUNT",
    WarningMessageForQuestionTypeOption: "AUDIT.OPTIONCANTBEDELETED",
    WarningMessageForQuestionType: "AUDIT.QUESTIONTYPECANTBEDELETED",
    SuccessMessageForQuestionsMoved: "AUDIT.QUESTIONSMOVED",
    WarningMessageForAuditError: "AUDIT.AUDITARCHIVEERROR",
    MessageForQuestionSubmitted: "AUDIT.SUBMITTED",
    MessageForActionSubmitted: "AUDIT.ACTIONCREATED",
    MessageForAuditCloned: "AUDIT.CLONEDAUDIT",
    WarningMessageForQuestionMandatory: "AUDIT.SUBMITQUESTIONMANDATORY",
    WarningMessageForQuestionActionAdded: "AUDIT.QUESTIONACTION",
    WarningMessageForConductArchived: "AUDIT.CONDUCTISARCHIVED",
    AuditReport: "AUDIT.AUDITREPORTSENT",


    RosterPlanDateOtherThanHolidays: "ROSTER.PLEASESELECTDATEOTHERTHANHOLIDAYS",
    RosterEnterValidStartAndEndDates: "ROSTER.PLEASEENTERVALIDFROMTODATES",
    RosterSelectedHoliday: "ROSTER.YOUHAVESELECTEDONHOLIDAY",
    RosterSelectedWeekEnd: "ROSTER.YOUHAVESELECTEDONWEEKEND",
    RosterTemplateSOMEEmployeeNotAvailable: "ROSTER.NOTEMPLOYEEALLEMPLOYEEAREAVAILABLE",
    RosterTemplateALLEmployeeNotAvailable: "ROSTER.NOEMPLOYEEISAVAILABLE",
    RosterSelectEmployee: "ROSTER.SELECTEMPLOYEEATLEASTONE",
    RosterBetweenStartDateAndEndDate: "ROSTER.PLANBETWEENSTARTANDEND",
    RosterMaxBudget: "ROSTER.MAXBUDGETREACHED",
    RosterNoRateSheet: "ROSTER.NORATESHEET",
    RosterEmployeeUnavailableInShift: "ROSTER.EMPLOYEEUNAVAILABLESHIFT",
    RosterNoPlansToProceed: "ROSTER.NOPLANSTOPROCEED",

    //Master question type Id's
    DropdownQuestionTypeId:'D628F2C7-6B90-41F6-986A-86105E2BF1A2',
    BooleanQuestionTypeId:'C1CEE1F5-B2D9-4015-BA8D-C0E28D637A2D',
    DateQuestionTypeId:'37094A98-C1E8-4536-A3FD-7621B8538C1F',
    NumericQuestionTypeId:'9F0068F6-B128-4F70-8449-E286EC548AFA',
    TextQuestionTypeId:'2A65297E-BDAF-4F0F-B485-2F7B9F4BFC08',
    TimeQuestionTypeId:'3379266F-C49F-444C-BF07-3CA88313D8F8',

    //purchase bl document ids 
    IntialDocumentTypeBlId: '1912F3AC-5BAA-4EDC-894D-10103F96AF58',
    FinalDocumentTypeBlId: '8A3E9EDC-A5F1-42D5-896E-AF1FFAF04A02'

}
