export class CreateGenericForm {
    Id: string;
    FormTypeId: string;
    FormType: string;
    formTypeName: string;
    formName: string;
    workflowTrigger: string;
    formJson: string;
    createdDateTime: Date;
    CreatedByUserId: string;
    UpdatedDateTime: Date;
    UpdatedByUserId: string;
    IsArchived: boolean;
    ArchivedDateTime: Date;
    ArchivedByUserId: string;
    IsDeleted: boolean;
    TimeStamp: any;
    roleIds : string;
    formKeys: string;
    profileImage: string;
    fullName: string;
    statusReportingConfigurationId: string;
    isSubmitted: boolean;
    statusReportingConfigurationOptionId: string;
    isAbleToLogin: boolean;
    customApplicationNames: string[];
    isFromEmployeeList: boolean;
    columns: any[];
    gridData: any;
    pageSize: any;
    skip: any;
    gridDataResult: any;
}
