export const ConstantVariables = {
    SuccessMessageForProjectArchive: "PROJECTS.PROJECTARCHIVEDSUCCESSFULLY",
    SuccessMessageForProjectUnArchive: "PROJECTS.PROJECTUNARCHIVEDSUCCESSFULLY",
    SuccessMessageForProjectCreate: "PROJECTS.PROJECTCREATEDSUCCESSFULLY",
    SuccessMessageForProjectUpdate: "PROJECTS.PROJECTUPDATEDSUCCESSFULLY",
    SuccessMessageForCreated: "CREATEDSUCCESSFULLY",
    SuccessMessageForArchived: "ARCHIVEDSUCCESSFULLY",
    SuccessMessageForUpdated: "UPDATEDSUCCESSFULLY",
    SuccessMessageForPasswordCreated: "HRMANAGAMENT.PASSWORDCREATEDSUCCESSFULLY",
    SuccessMessageForPasswordChanged: "HRMANAGAMENT.PASSWORDCHANGEDSUCCESSFULLY",
    SuccessMessageForPurchaseCanteenItem: "CANTEEN.PURCHASEDITEMSINCANTEENSUCCESSFULLY",
    PurchaseItem: "CANTEEN.PURCHASEITEM",
    success: "SUCCESS",
    Month: "Month",
    REQUIREDPRODUCTIVITY: "Required productivity",
    EXISTINGPRODUCTIVITY: "Existing productivity",
    ProfileImageUpdatedSuccessfully: "MYPROFILE.PROFILEIMAGEUPDATEDSUCCESSFULLY",
    ProfileImageRemovedSuccessfully: "MYPROFILE.PROFILEIMAGEREMOVEDSUCCESSFULLY",
    ThisUserStoryIsArchived: "HISTORICALREPORT.ARCHIVEDUSERSTORY",
    ThisUserStoryIsParked: "HISTORICALREPORT.PARKEDUSERSTORY",
}
