export class CreateForm {
    Id: string;
    FormTypeId: string;
    DataSourceId: string;
    companiesList: string;
    FormType: string;
    formTypeName: string;
    formBgColor:string;
    formName: string;
    workflowTrigger: string;
    formJson: any;
    createdDateTime: Date;
    CreatedByUserId: string;
    UpdatedDateTime: Date;
    UpdatedByUserId: string;
    IsArchived: boolean;
    ArchivedDateTime: Date;
    ArchivedByUserId: string;
    IsDeleted: boolean;
    TimeStamp: any;
    roleIds : string;
    formKeys: string;
    profileImage: string;
    fullName: string;
    statusReportingConfigurationId: string;
    isSubmitted: boolean;
    statusReportingConfigurationOptionId: string;
    isAbleToLogin: boolean;
    allowAnnonymous: boolean;
    customApplicationNames: string[];
    dataSourceId: string;
    companyModuleId: string;
    dataSourceTypeNumber: number;
    viewFormRoleIds: any;
    editFormRoleIds: any;
}
