export const ApiUrls = {
  UpsertCustomFieldForm: `CustomFields/CustomFieldApi/UpsertCustomFieldForm`,
  UpdateCustomFieldData: `CustomFields/CustomFieldApi/UpdateCustomFieldData`,
  SearchCustomFieldForms: `CustomFields/CustomFieldApi/SearchCustomFieldForms`,
  GetCustomFormFieldById: `CustomFields/CustomFieldApi/GetCustomFormFieldById`,
  GetCustomFieldHistory: `CustomFields/CustomFieldApi/GetCustomFieldHistory`,
  UpdateDashboardName: `Widgets/WidgetsApi/UpdateDashboardName`,
  GetSoftLabelConfigurations: `MasterData/MasterDataManagementApi/GetSoftLabelConfigurations`,
  UpsertSoftLabelConfigurations: `MasterData/MasterDataManagementApi/UpsertSoftLabelConfigurations`,
  GetSoftLabelById: `MasterData/MasterDataManagementApi/GetSoftLabelById`,
  UploadFileChunks: `File/FileApi/UploadFileChunks`,


  
  UploadFile: `File/FileApi/UploadFile`,
  SearchFile: `File/FileApi/SearchFile`,
  EmployeeUpload: `HrManagement/HrManagementApi/EmployeeUpload`,
  SearchFolder: 'File/FileApi/SearchFolder',
  UpsertFolder: 'File/FileApi/UpsertFolder',
  ReviewFile: 'File/FileApi/ReviewFile',
  UpsertFileName: 'File/FileApi/UpsertFileName',
  UpsertFileDetails: 'File/FileApi/UpsertFileDetails',
  GetFileDetailById: `File/FileApi/GetFileDetailById`,
  GetFolderDetailById : `File/FileApi/GetFolderDetailById`,
  UpsertFile: `File/FileApi/UpsertFile`,
  DeleteFile: `File/FileApi/DeleteFile`,
  DeleteFileByReferenceId: `File/FileApi/DeleteFileByReferenceId`,
  UpsertMultipleFiles: `File/FileApi/UpsertMultipleFiles`,
  GetStoreConfiguration: `DocumentManagement/StoreManagementApi/GetStoreConfiguration`,
  IsUsersStore: `DocumentManagement/StoreManagementApi/IsUsersStore`,
  UpsertFolderDescription: `File/FileApi/UpsertFolderDescription`,
  DownloadFile: `FileStore/FileStoreApi/DownloadFile`,
  FolderTreeView: 'DocumentManagement/StoreManagementApi/FolderTreeView',
  GetStores: 'DocumentManagement/StoreManagementApi/GetStores',
  UpsertStore: 'DocumentManagement/StoreManagementApi/UpsertStore',
  GetGenericFileDetails: 'File/FileApi/GetGenericFileDetails',
}
