export const ApiUrls = {
  UploadFile: `File/FileApi/UploadFile`,
  SearchFile: `File/FileApi/SearchFile`,
  EmployeeUpload: `HrManagement/HrManagementApi/EmployeeUpload`,
  SearchFolder: 'File/FileApi/SearchFolder',
  UpsertFolder: 'File/FileApi/UpsertFolder',
  ReviewFile: 'File/FileApi/ReviewFile',
  UpsertFileName: 'File/FileApi/UpsertFileName',
  UpsertFileDetails: 'File/FileApi/UpsertFileDetails',
  GetFileDetailById: `File/FileApi/GetFileDetailById`,
  GetFolderDetailById : `File/FileApi/GetFolderDetailById`,
  UpsertFile: `File/FileApi/UpsertFile`,
  DeleteFile: `File/FileApi/DeleteFile`,
  DeleteFileByReferenceId: `File/FileApi/DeleteFileByReferenceId`,
  UpsertMultipleFiles: `File/FileApi/UpsertMultipleFiles`,
  GetStoreConfiguration: `DocumentManagement/StoreManagementApi/GetStoreConfiguration`,
  IsUsersStore: `DocumentManagement/StoreManagementApi/IsUsersStore`,
  UpsertFolderDescription: `File/FileApi/UpsertFolderDescription`,
  DownloadFile: `FileStore/FileStoreApi/DownloadFile`,
  FolderTreeView: 'DocumentManagement/StoreManagementApi/FolderTreeView',
  UploadFileChunks: `File/FileApi/UploadFileChunks`,
  GetStores: 'DocumentManagement/StoreManagementApi/GetStores',
  UpsertStore: 'DocumentManagement/StoreManagementApi/UpsertStore',
  GetSoftLabelConfigurations: `MasterData/MasterDataManagementApi/GetSoftLabelConfigurations`,
  GetSoftLabelById: `MasterData/MasterDataManagementApi/GetSoftLabelById`,
  UpsertSoftLabelConfigurations: `MasterData/MasterDataManagementApi/UpsertSoftLabelConfigurations`,
  GetChunkBlobUrl:`File/FileApi/GetChunkBlobUrl`
}
