export const ConstantVariables = {
    FolderCreatedSuccessfully: "DOCUMENTMANAGEMENT.FOLDERCREATEDSUCCESSFULLY",
    FolderDeletedSuccessfully: "DOCUMENTMANAGEMENT.FOLDERDELETEDSUCCESSFULLY",
    FolderUpdatedSuccessfully: "DOCUMENTMANAGEMENT.FOLDERUPDATEDSUCCESSFULLY",
    FileCreatedSuccessfully: "DOCUMENTMANAGEMENT.FILECREATEDSUCCESSFULLY",
    FileDeletedSuccessfully: "DOCUMENTMANAGEMENT.FILEDELETEDSUCCESSFULLY",
    FileUpdatedSuccessfully: "DOCUMENTMANAGEMENT.FILEUPDATEDSUCCESSFULLY",
    FileSizeShouldNotExceed: "DOCUMENTMANAGEMENT.FILESIZESHOULDNOTEXCEED",
    ThisFileTypeIsNotAllowed: "DOCUMENTMANAGEMENT.THISFILETYPEISNOTALLOWED",
    MultipleFilesNotAllowed: "DOCUMENTMANAGEMENT.MULTIPLEFILESNOTALLOWED",
    DocumentManagementRouteConstant: "documents",
    DragAndDropFilesHere: "DOCUMENTMANAGEMENT.DRAGANDDROPFILESHERE",
    AddReceiptsHere: "DOCUMENTMANAGEMENT.ADDRECEIPTSHERE",
    FileNameAlreadyExists: "DOCUMENTMANAGEMENT.FILENAMEALREADYEXISTS",
    success: "SUCCESS",

}
