export const LocalStorageProperties = {
    CurrentUserId: 'CurrentUserId',
    CurrentUser: 'CurrentUser',
    UserModel: 'UserModel',
    CurrentCulture: 'CurrentCulture',
    CompanyId: 'CompanyId',
    CompanyName: 'CompanyName',
    CompanyMainLogo:'CompanyMainLogo',
    CompanyMiniLogo:'CompanyMiniLogo',
    DefaultDashboard: 'DefaultDashboard',
    CompanyDetails: 'CompanyDetails',
    FromLogIn: 'FromLogIn',
    CompanyTheme: 'CompanyTheme',
    SearchClick: 'SearchClick',
    RoleFeatures:'RoleFeatures',
    EntityRoleFeatures: 'EntityRoleFeatures',
    UserRoleFeatures: 'UserRoleFeatures',
    SoftLabels: 'SoftLabels',
    CompanySettings: 'CompanySettings',
    RecentSearches: 'RecentSearches',
    Dashboards: 'Dashboards',
    ExpensesFileCount: 'ExpensesFilesCount',
    Branches: 'Branches',
    Designations: 'Designations',
    EmploymentStatus: 'EmploymentStatus',
    Departments: 'Departments',
    Entities: 'Entities',
    TeamMembersList: 'TeamMembersList',
    Currencies: 'Currencies',
    TimeZones: 'TimeZones',
    JobCategories: 'JobCategories',
    ShiftTimings: 'ShiftTimings',
    Roles: 'Roles',
    Environment: 'Environment',
    Modules: 'Modules',
    DefaultLogin: 'DefaultLogin',
    SideBarMenuItems: 'SideBarMenuItems',
    PageTitle:'PageTitle',
    DefaultAppId:'DefaultAppId'
}