export const LocalStorageProperties = {
    AddOrEditCustomAppIsRequired: 'AddOrEditCustomAppIsRequired',
    CurrentUserId: 'CurrentUserId',
    CurrentUser: 'CurrentUser',
    CurrentCulture: 'CurrentCulture',
    CompanyId: 'CompanyId',
    CompanyName: 'CompanyName',
    CompanyMainLogo:'CompanyMainLogo',
    CompanyMiniLogo:'CompanyMiniLogo',
    DefaultDashboard: 'DefaultDashboard',
    CompanyDetails: 'CompanyDetails',
    FromLogIn: 'FromLogIn',
    CompanyTheme: 'CompanyTheme',
    SearchClick: 'SearchClick',
    RoleFeatures:'RoleFeatures',
    SoftLabels: 'SoftLabels',
    RecentSearches: 'RecentSearches',
    Dashboards: 'Dashboards',
    ExpensesFileCount: 'ExpensesFilesCount',
    UserModel: 'UserModel',
    Environment: 'Environment',
    Modules: 'Modules',
    AllDashboards: 'AllDashboards',
    UserReferenceId: 'UserReferenceId',
    ReloadDashboards: 'ReloadDashboards'
}