export const ApiUrls = {

  DownloadFile: `FileStore/FileStoreApi/DownloadFile`,
  UpsertMultipleFiles: `File/FileApi/UpsertMultipleFiles`,
  UpsertFile: `File/FileApi/UpsertFile`,
  GetFileDetailById: `File/FileApi/GetFileDetailById`,
  GetFolderDetailById: `File/FileApi/GetFolderDetailById`,
  UploadFile: `File/FileApi/UploadFile`,
  SearchFile: `File/FileApi/SearchFile`,
  GetUsersDropDown: 'User/UsersApi/GetUsersDropDown',
  DeleteFile: `File/FileApi/DeleteFile`,
  GetStoreConfiguration: `DocumentManagement/StoreManagementApi/GetStoreConfiguration`,
  IsUsersStore: `DocumentManagement/StoreManagementApi/IsUsersStore`,
  GetSoftLabelConfigurations: `MasterData/MasterDataManagementApi/GetSoftLabelConfigurations`,
  UpsertSoftLabelConfigurations: `MasterData/MasterDataManagementApi/UpsertSoftLabelConfigurations`,
  GetSoftLabelById: `MasterData/MasterDataManagementApi/GetSoftLabelById`,
  UpdateDashboardName: `Widgets/WidgetsApi/UpdateDashboardName`,
  UpsertWorkspaceDashboardFilter: `Widgets/WidgetsApi/UpsertWorkspaceDashboardFilter`,
  GetWorkspaceDashboardFilters: `Widgets/WidgetsApi/GetWorkspaceDashboardFilters`,
  UpsertFolderDescription: `File/FileApi/UpsertFolderDescription`,
  DeleteFileByReferenceId: `File/FileApi/DeleteFileByReferenceId`,
  UpsertSignature: "HrDashboard/HrDashboardApi/UpsertSignature",
  GetSignature: "HrDashboard/HrDashboardApi/GetSignature",
  UploadFileChunks: `File/FileApi/UploadFileChunks`,
  UpsertStore: 'DocumentManagement/StoreManagementApi/UpsertStore',
  GetStores: 'DocumentManagement/StoreManagementApi/GetStores',
  UpsertFileName: 'File/FileApi/UpsertFileName',
  ReviewFile: 'File/FileApi/ReviewFile',
  UpsertFileDetails: 'File/FileApi/UpsertFileDetails',
  UpsertFolder: 'File/FileApi/UpsertFolder',
  SearchFolder: 'File/FileApi/SearchFolder',
  FolderTreeView: 'DocumentManagement/StoreManagementApi/FolderTreeView',
  EmployeeUpload: `HrManagement/HrManagementApi/EmployeeUpload`,
  GetGenericFileDetails: `File/FileApi/GetGenericFileDetails`,
}
