export const ApiUrls = {
  Getstarttime :`ActivityTracker/ActivityTrackerApi/GetUserStartTime`,
  Getfinishtime :`ActivityTracker/ActivityTrackerApi/GetUserFinishTime`,
  GetActTrackerRoleConfigurationRoles: `ActTracker/ActTrackerApi/GetActTrackerRoleConfigurationRoles`,
  GetActTrackerScreenShotFrequencyRoles: `ActTracker/ActTrackerApi/GetActTrackerScreenShotFrequencyRoles`,
  GetActTrackerRolePermissionRoles: `ActTracker/ActTrackerApi/GetActTrackerRolePermissionRoles`,
  UpsertActTrackerRolePermission: `ActTracker/ActTrackerApi/UpsertActTrackerRolePermission`,
  UpsertActTrackerRoleConfiguration: `ActTracker/ActTrackerApi/UpsertActTrackerRoleConfiguration`,
  UpsertActTrackerScreenShotFrequency: `ActTracker/ActTrackerApi/UpsertActTrackerScreenShotFrequency`,
  GetApplicationCategory: "ActivityTracker/ActivityTrackerApi/GetApplicationCategory",
  UpsertApplicationCategory: "ActivityTracker/ActivityTrackerApi/UpsertApplicationCategory",
  GetActTrackerRoleDropDown: `ActTracker/ActTrackerApi/GetActTrackerRoleDropDown`,
  getActTrackerAppUrlType: `ActTracker/ActTrackerApi/GetActTrackerAppUrlType`,
  UpsertActTrackerAppUrls: `ActTracker/ActTrackerApi/UpsertActTrackerAppUrls`,
  GetActTrackerAppUrls: `ActTracker/ActTrackerApi/GetActTrackerAppUrls`,
  GetActTrackerAppReportUsage: `ActTracker/ActTrackerApi/GetActTrackerAppReportUsage`,
  GetActTrackerUserActivityScreenshots: `ActTracker/ActTrackerApi/GetActTrackerUserActivityScreenshots`,
  MultipleDeleteScreenShot: `ActTracker/ActTrackerApi/MultipleDeleteScreenShot`,
  GetActTrackerRecorder: `ActTracker/ActTrackerApi/GetActTrackerRecorder`,
  UpsertActivityTrackerConfigurationState: `ActTracker/ActTrackerApi/UpsertActivityTrackerConfigurationState`,
  GetActivityTrackerConfigurationState: `ActTracker/ActTrackerApi/GetActivityTrackerConfigurationState`,
  GetActTrackerUserStatus: `ActTracker/ActTrackerApi/GetActTrackerUserStatus`,
  GetAppUsageCompleteReport: `ActivityTracker/ActivityTrackerApi/GetAppUsageCompleteReport`,
  GetAppUsageUserStoryReport: `ActivityTracker/ActivityTrackerApi/GetAppUsageUserStoryReport`,
  GetAppUsageTimesheetReport: `ActivityTracker/ActivityTrackerApi/GetAppUsageTimesheetReport`,
  GetWebAppUsageTime: `ActivityTracker/ActivityTrackerApi/GetWebAppUsageTime`,
  GetTrackedInformationOfUserStory: `ActivityTracker/ActivityTrackerApi/GetTrackedInformationOfUserStory`,
  GetTotalTimeUsageOfApplicationsByUsers: `ActivityTracker/ActivityTrackerApi/GetTotalTimeUsageOfApplicationsByUsers`,
  GetTimeUsageDrillDown: `ActivityTracker/ActivityTrackerApi/GetTimeUsageDrillDown`,
  GetEmployees: `ActivityTracker/ActivityTrackerApi/GetEmployees`,
  GetLoggedInUser: `api/LoginApi/GetLoggedInUser`,
  GetAllBranches: `Branch/BranchApi/GetAllBranches`,
  UpdatePersistance: `Persistance/PersistanceApi/UpdatePersistance`,
  GetPersistance: `Persistance/PersistanceApi/GetPersistance`,
  GetDepartments: `HrManagement/HrManagementApi/GetDepartments`,
  GetEmployeeDetails: `HrManagement/HrManagementApi/GetEmployeeDetails`,
  GetSoftLabelConfigurations: `MasterData/MasterDataManagementApi/GetSoftLabelConfigurations`,
  UpsertActivityTrackerUserConfiguration: `ActTracker/ActTrackerApi/UpsertActivityTrackerUserConfiguration`,
  GetAllRoles: `Roles/RolesApi/GetAllRoles`,
  UploadFile: `File/FileApi/UploadFile`,
  GetIdleAndInactiveTimeForEmployee: `ActivityTracker/ActivityTrackerApi/GetIdleAndInactiveTimeForEmployee`,
  GetUserTrackerTimeline: "ActivityTracker/ActivityTrackerApi/GetUserTrackerTimeline",
  GetAvailabilityCalendar: "ActivityTracker/ActivityTrackerApi/GetAvailabilityCalendar",
  GetMyTeamMembersList: `HrManagement/HrManagementApi/GetMyTeamMembersList`,
  GetMostProductiveUsers: `ActTracker/ActTrackerApi/GetMostProductiveUsers`,
  GetActivityReport: `ActivityTracker/ActivityTrackerApi/GetActivityReport`,
  GetProductive: 'ActivityTracker/ActivityTrackerApi/GetProductiveTime',
  GetUnproductive :'ActivityTracker/ActivityTrackerApi/GetUnproductiveTime',
  GetIdleTime :'ActivityTracker/ActivityTrackerApi/GetIdleTime',
  GetNeutralTime: 'ActivityTracker/ActivityTrackerApi/GetNeutralTime',
  GetDeskTime:'ActivityTracker/ActivityTrackerApi/GetDeskTime',
  GetTrackingUsers: `ActTracker/ActTrackerApi/GetTrackingUsers`,
  GetTeamMembers:`ActivityTracker/ActivityTrackerApi/GetTotalTeamMembers`,
  GetTeamActivity: `ActivityTracker/ActivityTrackerApi/GetTeamActivity`,
  GetLateEmployees:`ActivityTracker/ActivityTrackerApi/GetLateEmployees`,
  GetPresentUsers:'ActivityTracker/ActivityTrackerApi/GetPresentEmployees',
  GetAbsentEmployees:`ActivityTracker/ActivityTrackerApi/GetAbsentEmployees`
}
