export const environment = {
  production: true,
  apiURL: 'http://localhost:55226/',
  artificialDelay: 0,
  version: '#{Octopus.Release.Number}',
  useTestAuthenticator: false,
  cookiePath: '/',
  domain: '#{Btrak.DomainName}',
  documentStorageApiURL: 'https://documentsstorage.nxussaas.com/',
  notificationUrl: "https://datastorageservice.nxussaas.com/lookupsync",
  pdfDesignerApiUrl: "https://pdfhtmlservice.nxussaas.com/",
  fileExtensions: ['jpg', 'jpeg', 'png', 'csv', 'txt', 'xls', 'xls', 'xml'],
  maxFileSize: 10485760,
  deployedEnvironment: '#{Octopus.Environment.Name}',
  publishKey: '#{BTrak.Pubnub.PublishKey}',
  subscribeKey: '#{BTrak.Pubnub.SubscribeKey}',
  canAllowCompanyCreation: '#{Btrak.AllowCompanyCreation}',
  zendeskAccountUrl: '#{BTrak.Zendesk.AccountUrl}',
  isShowZendesk: '#{BTrak.Zendesk.ShowZendesk}',
  trackingId: '#{BTrak.Google.Analytics.TrackingId}',
  domainAddress: '#{BTrak.DomainAddress}',
  isShowGoogleAnalytics: '#{BTrak.Zendesk.ShowGoogleAnalytics}',
  stripeAPIKey: '#{Btrak.StripeApiKey}'
};
